CREATE TABLE IF NOT EXISTS shabad(
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    shabad_no TEXT, 
    source_id TEXT,
    ang_id TEXT, 
    line_id TEXT, 
    writer_id TEXT, 
    raag_id TEXT, 
    vishraam TEXT, 
    green_vishraam TEXT, 
    first_ltr_start TEXT,
    first_ltr_any TEXT  ,
    gurmukhi TEXT ,
    english_ssk TEXT  ,
    english_bms TEXT  ,
    punjabi_bms TEXT,
    transliteration TEXT ,
    sggs_darpan TEXT ,
    faridkot_teeka TEXT
);