DROP TABLE IF EXISTS `shabad`;
CREATE TABLE `shabad`(
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    shabad_no TEXT, 
    source_id TEXT,
    ang_id TEXT, 
    line_id TEXT, 
    writer_id TEXT, 
    raag_id TEXT, 
    vishraam TEXT, 
    green_vishraam TEXT, 
    first_ltr_start TEXT,
    first_ltr_any TEXT  ,
    gurmukhi TEXT ,
    english_ssk TEXT  ,
    english_bms TEXT  ,
    punjabi_bms TEXT,
    transliteration TEXT ,
    sggs_darpan TEXT ,
    faridkot_teeka TEXT
);


INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
1,1,'G',1,1,1,1,'30','17,43,55','115,107,112,110,110,065,109,065,115,103,','115 107 112 110 110 065 109 065 115 103 ','<> siqnwmu krqw purKu inrBau inrvYru Akwl mUriq AjUnI sYBM gurpRswid ]','One Universal Creator God, TheName Is Truth  Creative Being Personified No Fear No Hatred Image Of The Undying, Beyond Birth, Self-Existent. By Guru''s Grace~','There is but one God. True is His Name, creative His personality and immortal His form. He is without fear sans enmity, unborn and self-illumined. By the Guru''s grace He is obtained.','ਵਾਹਿਗੁਰੂ ਕੇਵਲ ਇਕ ਹੈ। ਸੱਚਾ ਹੈ ਉਸ ਦਾ ਨਾਮ, ਰਚਨਹਾਰ ਉਸ ਦੀ ਵਿਅਕਤੀ ਅਤੇ ਅਮਰ ਉਸ ਦਾ ਸਰੂਪ। ਉਹ ਨਿਡਰ, ਕੀਨਾ-ਰਹਿਤ, ਅਜਨਮਾ ਤੇ ਸਵੈ-ਪ੍ਰਕਾਸ਼ਵਾਨ ਹੈ। ਗੁਰਾਂ ਦੀ ਦਯਾ ਦੁਆਰਾ ਉਹ ਪਰਾਪਤ ਹੁੰਦਾ ਹੈ।','Ikoankaar Sathnaam Karathaa Purakh Nirabho Niravair Akaal Moorath Ajoonee Saibhan Gurprasaadh||','ਅਕਾਲ ਪੁਰਖ ਇੱਕ ਹੈ, ਜਿਸ ਦਾ ਨਾਮ ''ਹੋਂਦ ਵਾਲਾ'' ਹੈ ਜੋ ਸ੍ਰਿਸ਼ਟੀ ਦਾ ਰਚਨਹਾਰ ਹੈ, ਜੋ ਸਭ ਵਿਚ ਵਿਆਪਕ ਹੈ, ਭੈ ਤੋਂ ਰਹਿਤ ਹੈ, ਵੈਰ-ਰਹਿਤ ਹੈ, ਜਿਸ ਦਾ ਸਰੂਪ ਕਾਲ ਤੋਂ ਪਰੇ ਹੈ, (ਭਾਵ, ਜਿਸ ਦਾ ਸਰੀਰ ਨਾਸ-ਰਹਿਤ ਹੈ), ਜੋ ਜੂਨਾਂ ਵਿਚ ਨਹੀਂ ਆਉਂਦਾ, ਜਿਸ ਦਾ ਪ੍ਰਕਾਸ਼ ਆਪਣੇ ਆਪ ਤੋਂ ਹੋਇਆ ਹੈ ਅਤੇ ਜੋ ਸਤਿਗੁਰੂ ਦੀ ','ਬੇਦ ਸੂਪੁ ਉਪਦੇਸ ਮੇ ''ਓਂ'' ਕੇ ਆਦਿ ਮੇ ''ਏਕ'' ਅੰਗੁ ਨਹੀਂ ਕਹਾ, ਈਹਾਂ ਕਹਾ ਹੈ। ਤਿਸ ਕਾ ਏਹਿ ਤਾਤਪਰਯੁ ਹੈ, ਸੋ ਸਭ ਕੋ ਪ੍ਰਤੀਤ ਹੋ ਜਾਵੇ, ਜੋ ਸਿਧਾਂਤ ਵਸਤੂ ਅਦ੍ਵੈਤ ਹੈ, ਦ੍ਵੈਤ ਨਹੀਂ। ਯਾਂ ਤੇ ਜੀਵ ਈਸ ਏਕ ਰੂਪੁ ਹੈਂ, ਭੇਦ ਵਾਦੀਯੋਂ ਕੇ ਮਤ ਵਤ ਦੋ ਨਹੀਂ। ਕੇਈ ਕਿ ਏਕ ਅੰਗੁ ਆਦਿ ਮੇ ਕਹਿਨੇ ਕਾ ਏਹਿ ਹੇਤੂ ਕਹਤੇ ਹ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
2,1,'G',1,3,1,1,'','','106,','106 ','] jpu ]','Chant And Meditate:','Embrace His meditation.','ਉਸ ਦਾ ਸਿਮਰਨ ਕਰ।','|| Jap ||','(ਬਾਣੀ ਦਾ ਨਾਮ ਹੈ)','ਇਸ ਅਸਥਾਨ ਮੈ ਜਪ ਸਬਦ ਕੇ ਕਹਿਨੇ ਸੇ ਇਸ ਬਾਣੀ ਕਾ ਨਾਮੁ ਜਪੁ ਹੀ ਕਹਤੇ ਹੈਂ। ਜਿਸ ਪ੍ਰਮਾਤਮਾ ਕੇ ਨਾਮ ਕਾ ਜਪੁ ਵਿਧਾਨ ਕੀਆ ਹੈ ਸੋ ਪਰਮਾਤਮਾ ਕੈਸਾ ਹੈ ਤਿਸੁ ਪਰ ਕਹਤੇ ਹੈਂ (ਕਰਤਾ) ਨਿਖਲ ਸੰਸਾਰ ਕਾਕਾਰਣੁ ਹੈ ਭਾਵ ਯੇਹ ਹੈ ਕਿ ਯਾਵਤ ਕਾਲ ਕਿਸੀ ਬਸਤੂ ਕਾ ਲਛਨੁ ਨਹੀਂ ਕੀਆ ਜਾਤਾ ਹੈ ਤਾਵਤ ਕਾਲ ਪਰਯੰਤ ਵਸਤੂ ਕੀ ਸਿੱਧੀ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
3,1,'G',1,4,1,1,'6','','065,115,106,115,','065 115 106 115 ','Awid scu jugwid scu ]','True In The Primal Beginning. True Throughout The Ages.','True in the prime, True in the beginning of ages,','ਪਰਾਰੰਭ ਵਿੱਚ ਸੱਚਾ, ਯੁਗਾਂ ਦੇ ਸ਼ੁਰੂ ਵਿੱਚ ਸੱਚਾ,','Aadh Sach Jugaadh Sach ||','ਅਕਾਲ ਪੁਰਖ ਮੁੱਢ ਤੋਂ ਹੋਂਦ ਵਾਲਾ ਹੈ, ਜੁਗਾਂ ਦੇ ਮੁੱਢ ਤੋਂ ਮੌਜੂਦ ਹੈ।','ਆਦਿ ਕਹੀਏ ਸਰਬ ਕੀ ਉਤਪਤੀ ਸੇ ਪਹਿਲੇ ਭੀ ਵਹੁ ਪੁਰਖੁ ਸਚੁ ਹੀ ਥਾ। ਜਬ ਸੂਖਮੁ ਔਰ ਅਸਥੂਲੁ ਪਰਪੰਚੁ ਹੋ ਗ੍ਯਾ ਪਰੰਤੂ ਸਤਜੁਗ ਆਦਿਕੋਂ ਕੇ ਧਰਮ ਕਾ ਵਿਸਤਾਰੁ ਨਹੀਂ ਹੂਆ ਥਾ, ਉਸ ਕਾਲ ਕਾ ਨਾਮੁ ਜੁਗਾਦਿ ਹੈ, ਤਿਸ ਕਾਲ ਮੈ ਭੀ ਸੱਚੁ ਹੀ ਥਾ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
4,1,'G',1,4,1,1,'7','','104,066,115,110,104,066,115,','104 066 115 110 104 066 115 ','hY BI scu nwnk hosI BI scu ]1]','True Here And Now. O Nanak, Forever And Ever True. ||1||','True He is even now and True He verily, shall be, O Nanak!','ਅਤੇ ਸੱਚਾ ਉਹ ਹੁਣ ਭੀ ਹੈ, ਹੇ ਨਾਨਕ! ਨਿਸਚਿਤ ਹੀ, ਉਹ ਸੱਚਾ ਹੋਵੇਗਾ।','Hai Bhee Sach Naanak Hosee Bhee Sach ||1||','ਹੇ ਨਾਨਕ! ਇਸ ਵੇਲੇ ਭੀ ਮੌਜੂਦ ਹੈ ਤੇ ਅਗਾਂਹ ਨੂੰ ਭੀ ਹੋਂਦ ਵਾਲਾ ਰਹੇਗਾ ॥੧॥','''ਹੈ ਭੀ ਸਚੁ'' ਹੁਣ ਸਾਰੇ ਜਗਤ ਕੀ ਇਸਥਿਤੀ ਕਾਲ ਮੇ ਭੀ ਸੱਚੁ ਹੈ। ਸ੍ਰੀ ਗੁਰੂ ਨਾਨਕ ਜੀ ਕਹਤੇ ਹੈਂ: ''ਹੋਸੀ ਭੀ ਸਚੁ'' ਅੱਗੇ ਨੂੰ ਸਾਰੇ ਜਗਤ ਕੇ ਪ੍ਰਲਯ ਕਾਲ ਮੇ ਭੀ ਸੱਚੁ ਹੀ ਹੋਵੇਗਾ ॥੧॥☬ਪੁਨਾ ਜਗ੍ਯਾਸੂਓਂ ਕੇ ਸੁਖੇਨ ਬੋਧ ਨਮਿੱਤ ਸੰਕੋਚ ਕਰ ਇਸ ਮੰਤ੍ਰ ਕਾ ਅਰਥੁ ਕਹਤੇ ਹੈਂ:☬ਏਕ ਜੋ ''ਓਂ'' ਮੰਗਲ ਰੂਪੁ ਪਰਮਾਤਮਾ ਹੈ। ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
5,1,'G',1,5,1,1,'13','1','115,115,110,104,106,115,108,118,','115 115 110 104 106 115 108 118 ','socY soic n hoveI jy socI lK vwr ]','By thinking, He cannot be reduced to thought, even by thinking hundreds of thousands of times.','By pondering on God, man cannot have a conception of Him, even though he may ponder over lacs of times.','ਵਿਚਾਰ ਕਰਨ ਦੁਆਰਾ ਵਾਹਿਗੁਰੂ ਦੀ ਗਿਆਤ ਨਹੀਂ ਹੁੰਦੀ, ਭਾਵੇਂ ਆਦਮੀ ਲੱਖਾਂ ਵਾਰੀ ਵਿਚਾਰ ਪਿਆ ਕਰੇ।','Sochai Soch N Hovee Jae Sochee Lakh Vaar ||','ਜੇ ਮੈਂ ਲੱਖ ਵਾਰੀ (ਭੀ) (ਇਸ਼ਨਾਨ ਆਦਿਕ ਨਾਲ ਸਰੀਰ ਦੀ) ਸੁੱਚ ਰੱਖਾਂ, (ਤਾਂ ਭੀ ਇਸ ਤਰ੍ਹਾਂ) ਸੁੱਚ ਰੱਖਣ ਨਾਲ (ਮਨ ਦੀ) ਸੁੱਚ ਨਹੀਂ ਰਹਿ ਸਕਦੀ।','ਸੋਚ, ਪਵਿੱਤ੍ਰਤਾ ਕਰਨੇ ਸੇ ਅੰਤਹਕਰਣ ਰਾਗ ਦ੍ਵੈਖ ਸੇ ਰਹਿਤ ਸੁੱਧ ਨਹੀਂ ਹੋਤਾ, ਭਾਵੇਂ ਲਾਖੋਂ ਵਾਰ ਪਵਿੱਤ੍ਰਤਾ ਕਰੀਏ। ਵਾ ਆਤਮ ਵਿਚਾਰ ਜੋ ਹੈ, ਸੋ (ਸੋਚਿ) ਪਵਿੱਤ੍ਰਤਾ ਕਰਨੇ ਸੇ ਨਹੀਂ ਪ੍ਰਾਪਤਿ ਹੋਤਾ, ਜੇ ਕਰ ਲੱਖਾਂ ਵਾਰੀ ਪਵਿੱਤ੍ਰਤਾ ਕਰੀਏ। ਭਾਵ ਯੇਹ ਹੈ, ਬਾਹਿਰ ਕੀ ਪਵਿੱਤ੍ਰਤਾ ਸਰੀਰ ਕੀ ਸੁੱਧੀ ਕਾ ਕਾਰਣੁ ਹੈ। ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
6,1,'G',1,5,1,1,'13','1','099,099,110,104,106,108,114,108,113,','099 099 110 104 106 108 114 108 113 ','cupY cuip n hoveI jy lwie rhw ilv qwr ]','By remaining silent, inner silence is not obtained, even by remaining lovingly absorbed deep within.','Even though one be silent and remains absorbed in Lord''s constant love he obtains not mind''s silence.','ਭਾਵੇਂ ਬੰਦਾ ਚੁਪ ਕਰ ਰਹੇ ਅਤੇ ਲਗਾਤਾਰ ਧਿਆਨ ਅੰਦਰ ਲੀਨ ਰਹੇ, ਉਸ ਨੂੰ ਮਨ ਦੀ ਸ਼ਾਂਤੀ ਪਰਾਪਤ ਨਹੀਂ ਹੁੰਦੀ।','Chupai Chup N Hovee Jae Laae Rehaa Liv Thaar ||','ਜੇ ਮੈਂ (ਸਰੀਰ ਦੀ) ਇਕ-ਤਾਰ ਸਮਾਧੀ ਲਾਈ ਰੱਖਾਂ; (ਤਾਂ ਭੀ ਇਸ ਤਰ੍ਹਾਂ) ਚੁੱਪ ਕਰ ਰਹਿਣ ਨਾਲ ਮਨ ਦੀ ਸ਼ਾਂਤੀ ਨਹੀਂ ਹੋ ਸਕਦੀ।','ਬਾਣੀ ਕੇ ਚੁੱਪ ਰਹਿਣੇ ਸੇ ਸੰਕਲਪ ਵਿਕਲਪੋਂ ਸੇ ਮਨ ਕੀ ਸਾਂਤੀ ਰੂਪ ਚੁੱਪ ਨਹੀਂ ਹੋਤੀ। ਜੇ ਹੋ ਜਾਵੇ ਤੌ (ਲਿਵ) ਬ੍ਰਿਤੀ ਕੋ ਤੇਲ ਧਾਰਾਵਤ ਲਗਾਇ ਰੱਖੀਏ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
7,1,'G',1,5,1,1,'14','1','066,066,110,097,106,098,112,066,','066 066 110 097 106 098 112 066 ','BuiKAw BuK n auqrI jy bMnw purIAw Bwr ]','The hunger of the hungry is not appeased, even by piling up loads of worldly goods.','The hunger of the hungry departs not, even though they may pile up loads of the world''s valuables.','ਖੁਧਿਆਵੰਤਾਂ ਦੀ ਖੁਧਿਆ ਦੂਰ ਨਹੀਂ ਹੁੰਦੀ, ਭਾਵੇਂ ਉਹ ਜਹਾਨਾ ਦੇ ਪਦਾਰਥਾਂ ਦੀਆਂ ਪੰਡਾ ਦੇ ਢੇਰ ਹੀ ਕਿਉਂ ਨਾਂ ਲਾ ਲੈਣ।','Bhukhiaa Bhukh N Outharee Jae Bannaa Pureeaa Bhaar ||','ਜੇ ਮੈਂ ਸਾਰੇ ਭਵਣਾਂ ਦੇ ਪਦਾਰਥਾਂ ਦੇ ਢੇਰ (ਭੀ) ਸਾਂਭ ਲਵਾਂ, ਤਾਂ ਭੀ ਤ੍ਰਿਸ਼ਨਾ ਦੇ ਅਧੀਨ ਰਿਹਾਂ ਤ੍ਰਿਸ਼ਨਾ ਦੂਰ ਨਹੀਂ ਹੋ ਸਕਦੀ।','ਭੁਖੇ ਰਹਿਨੇ ਸੇ ਅਰਥਾਤ ਕ੍ਰਿਸ ਚੰਦ੍ਰਾਇਣਾਦਿ ਬ੍ਰਤ ਕਰਨੇ ਸੇ, ਵਾ (ਭੁਖਿਆ) ਤ੍ਰਿਸ਼ਨਾ ਵਾਨੋ ਕੀ ਮਾਯਾ ਕੀ ਭੂਖ ਨਹੀਂ ਜਾਤੀ ਅਰਥਾਤ ਤ੍ਰਿਸਨਾਂ ਨਿਵਿਰਤ ਨਹੀਂ ਹੋਤੀ। ਜੋ ਇੰਦ੍ਰਾਦਿ ਸਭ ਪੁਰੀਯੋਂ ਕੇ ਪਦਾਰਥੋਂ ਕੇ ਭਾਰ ਬਾਧ ਕਰ ਦੇ ਦੀਜੀਏ, ਭਾਵ ਏਹੋ ਸਬ ਪਦਾਰਥ ਪਾਉਨੇ ਕਰ ਭੀ ਤ੍ਰਿਸ਼ਨਾ ਬਢਤੀ ਹੀ ਜਾਤੀ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
8,1,'G',1,6,1,1,'16','','115,115,108,104,113,101,110,099,110,','115 115 108 104 113 101 110 099 110 ','shs isAwxpw lK hoih q iek n clY nwil ]','Hundreds of thousands of clever tricks, but not even one of them will go along with you in the end.','Man may possess thousands and lacs of wits, but not even one (goes with him) avails him in the Lord''s court.','ਇਨਸਾਨ ਦੇ ਕੋਲ ਹਜ਼ਾਰਾਂ ਤੇ ਲੱਖਾਂ ਅਕਲ-ਮੰਦੀਆਂ ਹੋਣ, ਪਰ ਇਕ ਭੀ (ਸਾਈਂ ਦੇ ਦਰਬਾਰ ਅੰਦਰ ਉਸ ਨੂੰ ਲਾਭ ਨਹੀਂ ਪੁਚਾਉਂਦੀ) ਉਸ ਦੇ ਨਾਲ ਨਹੀਂ ਜਾਂਦੀ।','Sehas Siaanapaa Lakh Hohi Th Eik N Chalai Naal ||','ਜੇ (ਮੇਰੇ ਵਿਚ) ਹਜ਼ਾਰਾਂ ਤੇ ਲੱਖਾਂ ਚਤੁਰਾਈਆਂ ਹੋਵਣ, (ਤਾਂ ਭੀ ਉਹਨਾਂ ਵਿਚੋਂ) ਇਕ ਭੀ ਚਤੁਰਾਈ ਸਾਥ ਨਹੀਂ ਦੇਂਦੀ।','ਜੇਕਰ ਪੁਰਖ ਕੇ ਪਾਸ (ਸਹਸ) ਹਜਾਰੋਂ ਲਾਖੋਂ ਸੰਸਾਰਕ ਸ੍ਯਾਨਪਾਂ ਹੋਵੇਂ, ਤਾਂ ਵੀ ਪਰਮੇਸ੍ਵਰ ਕੀ ਪ੍ਰਾਪਤੀ ਮੈ ਚਤਰਾਈ੍ਯੋਂ ਕਾ ਏਕ ਜੋਰੁ ਭੀ (ਨਾਲਿ) ਸਾਥ ਨਹੀਂ ਚੱਲਦਾ ਹੈ, ਭਾਵ ਸਹਾਇਕ ਨਹੀਂ ਹੋਤਾ॥ ਪ੍ਰਸ਼ਨ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
9,1,'G',1,6,1,1,'13','1,20','107,115,104,107,107,113,112,','107 115 104 107 107 113 112 ','ikv sicAwrw hoeIAY ikv kUVY qutY pwil ]','So how can you become truthful? And how can the veil of illusion be torn away?','How can we be true and how can the screen of untruth be rent?','ਅਸੀਂ ਕਿਸ ਤਰ੍ਹਾਂ ਸੱਚੇ ਹੋ ਸਕਦੇ ਹਾਂ ਅਤੇ ਕਿਸ ਤਰ੍ਹਾਂ ਝੂਠ ਦਾ ਪੜਦਾ ਪਾੜਿਆ ਜਾ ਸਕਦਾ ਹੈ?','Kiv Sachiaaraa Hoeeai Kiv Koorrai Thuttai Paal ||','(ਤਾਂ ਫਿਰ) ਅਕਾਲ ਪੁਰਖ ਦਾ ਪਰਕਾਸ਼ ਹੋਣ ਲਈ ਯੋਗ ਕਿਵੇਂ ਬਣ ਸਕੀਦਾ ਹੈ (ਅਤੇ ਸਾਡੇ ਅੰਦਰ ਦਾ) ਕੂੜ ਦਾ ਪਰਦਾ ਕਿਵੇਂ ਟੁੱਟ ਸਕਦਾ ਹੈ?','ਫੇਰ ਕਿਸ ਪ੍ਰਕਾਰ ਪ੍ਰਮੇਸ੍ਵਰ ਸਾਥ ਸਚੇ ਹੋਵੀਏ, ਅਰੁ ਝੂਠ ਕਾ (ਪਾਲਿ) ਪੜਦਾ ਕੈਸੇ (ਤੁਟੈ) ਭਾਵ ਨਾਸ ਹੋਵੈ? ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
10,1,'G',1,7,1,1,'13','18','104,114,099,110,108,110,','104 114 099 110 108 110 ','hukim rjweI clxw nwnk iliKAw nwil ]1]','O Nanak, it is written that you shall obey the Hukam of His Command, and walk in the Way of His Will. ||1||','O Nanak! By obeying, the pre-ordained order of the Lord''s will.','ਹੇ ਨਾਨਕ! ਮਰਜ਼ੀ ਦੇ ਮਾਲਕ ਦੇ ਧੁਰ ਦੇ ਲਿਖੇ ਹੋਏ ਫੁਰਮਾਨ ਦੇ ਮੰਨਣ ਦੁਆਰਾ।','Hukam Rajaaee Chalanaa Naanak Likhiaa Naal ||1||','ਰਜ਼ਾ ਦੇ ਮਾਲਕ ਅਕਾਲ ਪੁਰਖ ਦੇ ਹੁਕਮ ਵਿਚ ਤੁਰਨਾ-(ਇਹੀ ਇਕ ਵਿਧੀ ਹੈ)। ਹੇ ਨਾਨਕ! (ਇਹ ਵਿਧੀ) ਧੁਰ ਤੋਂ ਹੀ ਜਦ ਤੋਂ ਜਗਤ ਬਣਿਆ ਹੈ, ਲਿਖੀ ਚਲੀ ਆ ਰਹੀ ਹੈ ॥੧॥','ਪੁਰਸੁ (ਰਜਾਈ) ਅਕਾਲ ਪੁਰਖ ਕੇ ਹੁਕਮ ਮੇ ਚਲੇ ਅਰਥਾਤ ਦੁਖੁ ਸੁਖੁ ਮੈਂ ਭਾਣਾ ਮਾਨ ਕਰ ਪ੍ਰਸਿੰਨ ਰਹੇ, ਇਉਂ ਕੂੜ ਕੀ ਪਾਲ ਤੁਟ ਜਾਤੀ ਹੈ ਔਰ (ਸਚਿਆਰਾ) ਸਚੇ ਹੋਈਤਾ ਹੈ ਵਾ ਹੁਕਮਿ ਵਿਖੇ (ਰਜਾਈ) ਰਾਜੀ, ਭਾਵ ਪ੍ਰਸਿੰਨ ਹੋ ਕਰ ਚਲਣਾ, ਇਸ ਕਰ ਪ੍ਰਮੇਸ੍ਵਰ ਨਾਲ ਸਚੇ ਰਹੀਤਾ ਹੈ। ਗੁਰੂ ਨਾਨਕ ਜੀ ਕਹਤੇ ਹੈਂ: ਜੋ ਪ੍ਰਾਰਬਧ ਕ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
11,2,'G',1,7,1,1,'13','','104,104,065,104,110,107,106,','104 104 065 104 110 107 106 ','hukmI hovin Awkwr hukmu n kihAw jweI ]','By His Command, bodies are created; His Command cannot be described.','By the Lord''s order bodies are produced. His order cannot be narrated.','ਸਾਈਂ ਦੇ ਅਮਰ ਦੁਆਰਾ ਸਰੀਰ ਬਣਦੇ ਹਨ। ਉਸ ਦਾ ਅਮਰ ਵਰਨਣ ਕੀਤਾ ਨਹੀਂ ਜਾ ਸਕਦਾ।','Hukamee Hovan Aakaar Hukam N Kehiaa Jaaee ||','ਅਕਾਲ ਪੁਰਖ ਦੇ ਹੁਕਮ ਅਨੁਸਾਰ ਸਾਰੇ ਸਰੀਰ ਬਣਦੇ ਹਨ, (ਪਰ ਇਹ) ਹੁਕਮ ਦੱਸਿਆ ਨਹੀਂ ਜਾ ਸਕਦਾ ਕਿ ਕਿਹੋ ਜਿਹਾ ਹੈ।','ਪ੍ਰਥਮ ਤੋ ਉਸ ਕਾ ਹੁਕਮੁ ਸਮਗ੍ਰ ਕਹਾ ਨਹੀਂ ਜਾਤਾ, ਕ੍ਯੋਂਕਿ ਬਿਅੰਤ ਹੈ। ਪਰ ਤਾਂ ਵੀ ਕੁਛ ਸੁਨਾਵਤੇ ਹੈਂ। ਏਹ ਜਿਤਨੇ ਅਕਾਰ ਸਥੂਲ ਸਰੀਰ ਹੈਂ, ਸੋ ਸੰਪੂਰਣ ਹੁਕਮੀ ਪਰਮੇਸ੍ਵਰ ਕੇ ਹੁਕਮ ਸੇ ਹੋਤੇ ਹੈਂ। ਅਰ ਹੁਕਮ ਸੇ ਹੀ ਜੀਵ ਆਵਰ ਭਾਵ ਕੋ ਪ੍ਰਾਪਤਿ ਹੋਤੇ ਹੈਂ। ਵਾ ਅਕਾਰ ਉਪਲਖਤ ''ਅਕਾਰ'', ''ਉਕਾਰ'', ''ਮਕਾਰ'', ''ਬ੍ਰਹਮਾ''');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
12,2,'G',1,8,1,1,'13','','104,104,106,104,109,118,','104 104 106 104 109 118 ','hukmI hovin jIA hukim imlY vifAweI ]','By His Command, souls come into being; by His Command, glory and greatness are obtained.','With His fiat the souls come into being and with His fiat greatness is obtained.','ਉਸ ਦੇ ਫੁਰਮਾਨ ਨਾਲ ਰੂਹਾਂ ਹੋਂਦ ਵਿੱਚ ਆਉਂਦੀਆਂ ਹਨ ਅਤੇ ਉਸ ਦੇ ਫੁਰਮਾਨ ਨਾਲ ਹੀ ਮਾਨ ਪਰਾਪਤ ਹੁੰਦਾ ਹੈ।','Hukamee Hovan Jeea Hukam Milai Vaddiaaee ||','ਰੱਬ ਦੇ ਹੁਕਮ ਅਨੁਸਾਰ ਹੀ ਸਾਰੇ ਜੀਵ ਜੰਮ ਪੈਂਦੇ ਹਨ ਅਤੇ ਹੁਕਮ ਅਨੁਸਾਰ ਹੀ (ਰੱਬ ਦੇ ਦਰ ''ਤੇ) ਸ਼ੋਭਾ ਮਿਲਦੀ ਹੈ।','ਪੁਨਾ ਤਿਨਾ ਦ੍ਵਾਰੇ ਔਰ ਜੀਵੋਂ ਕੇ ਅਕਾਰ, ਸਥਾਵਰ ਜੰਗਮ ਰੂਪ ਸਭ ਹੁਕਮੀ ਕੇ ਹੁਕਮ ਕਰ ਕੇ ਹੋਤੇ ਹੈਂ। ਹੁਕਮ ਹੀ ਕਰ ਕੇ ਇਨ ਜੀਵੋਂ ਕੋ ਵਡਿਆਈ ਛੁਟਿਆਈ ਮਿਲਤੀ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
13,2,'G',1,8,1,1,'13','1,24','104,097,110,104,108,100,115,112,','104 097 110 104 108 100 115 112 ','hukmI auqmu nIcu hukim iliK duK suK pweIAih ]','By His Command, some are high and some are low; by His Written Command, pain and pleasure are obtained.','By His command the mortals are make high and low and by His written command they obtain woe and weal.','ਉਸ ਦੇ ਫੁਰਮਾਨ ਦੁਆਰਾ ਪ੍ਰਾਨੀ ਚੰਗੇ ਤੇ ਮੰਦੇ ਹੁੰਦੇ ਹਨ ਅਤੇ ਉਸ ਦੇ ਲਿਖੇ ਫੁਰਮਾਨ ਦੁਆਰਾ ਹੀ ਉਹ ਗ਼ਮੀ ਤੇ ਖ਼ੁਸ਼ੀ ਪਾਉਂਦੇ ਹਨ।','Hukamee Outham Neech Hukam Likh Dhukh Sukh Paaeeahi ||','ਰੱਬ ਦੇ ਹੁਕਮ ਵਿਚ ਕੋਈ ਮਨੁੱਖ ਚੰਗਾ (ਬਣ ਜਾਂਦਾ) ਹੈ, ਕੋਈ ਭੈੜਾ। ਉਸ ਦੇ ਹੁਕਮ ਵਿਚ ਹੀ (ਆਪਣੇ ਕੀਤੇ ਹੋਏ ਕਰਮਾਂ ਦੇ) ਲਿਖੇ ਅਨੁਸਾਰ ਦੁੱਖ ਤੇ ਸੁਖ ਭੋਗੀਦੇ ਹਨ।','ਹੁਕਮੀ ਕੇ ਹੁਕਮ ਹੀ ਕਰ ਕੇ ਉਤਮ ਅਰੁ ਨੀਚ ਹੂਏ ਹੈਂ, ਵਾ ਨੀਚ ਤੇ ਉਤਮ, ਉਤਮ ਤੇ ਨੀਚ ਹੋਤੇ ਹੈਂ। ਜਥਾ ਅੰਗ ਰਾਜਾ ਕਾ ਬੇਟਾ ਬੇਨੁ ਨੀਚ ਹੂਆ, ਅਰੁ ਬਾਲਮੀਕ ਨੀਚੁ ਥਾ, ਸੋ ਪਰਮਾਤਮਾ ਕੇ ਹੁਕਮ ਸੇ ਰਾਮ ਜਪ ਕਰ ਉਤਮੁ ਭਇਆ⁽¹⁾। ਔਰ ਲਿਖਾ ਹੂਆ ਜੋ ਦੁਖੁ ਸੁਖੁ ਕਾ ਲੇਖੁ ਹੈ, ਸੋ (ਹੁਕਮੀ) ਪ੍ਰਮੇਸ੍ਵਰ ਕੇ ਹੁਕਮ ਸੇ ''ਪਾਈਅਹ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
14,2,'G',1,9,1,1,'13','','101,104,098,101,104,115,066,','101 104 098 101 104 115 066 ','ieknw hukmI bKsIs ieik hukmI sdw BvweIAih ]','Some, by His Command, are blessed and forgiven; others, by His Command, wander aimlessly forever.','Some obtain gifts through His order and some through His order are ever made to wander in transmigration.','ਕਈਆਂ ਨੂੰ ਉਸ ਦੀ ਆਗਿਆ ਰਾਹੀਂ ਦਾਤਾਂ ਮਿਲਦੀਆਂ ਹਨ ਅਤੇ ਕਈ ਉਸ ਦੀ ਆਗਿਆ ਰਾਹੀਂ ਆਵਾਗਉਣ ਅੰਦਰ ਸਦੀਵ ਹੀ ਭੁਆਈਂਦੇ ਹਨ।','Eikanaa Hukamee Bakhasees Eik Hukamee Sadhaa Bhavaaeeahi ||','ਹੁਕਮ ਵਿਚ ਹੀ ਕਦੀ ਮਨੁੱਖਾਂ ਉੱਤੇ (ਅਕਾਲ ਪੁਰਖ ਦੇ ਦਰ ਤੋਂ) ਬਖ਼ਸ਼ਸ਼ ਹੁੰਦੀ ਹੈ, ਅਤੇ ਉਸ ਦੇ ਹੁਕਮ ਵਿਚ ਹੀ ਕਈ ਮਨੁੱਖ ਨਿੱਤ ਜਨਮ ਮਰਨ ਦੇ ਗੇੜ ਵਿਚ ਭਵਾਈਦੇ ਹਨ।','ਇਕਨੋਂ ਕੋ ਹੁਕਮੀ ਕੇ ਹੁਕਮ ਕਰ ਕੇ ਹੀ ਆਤਮ ਪਦ ਕੀ ਪ੍ਰਾਪਤੀ ਰੂਪੁ ਬਖਸੀਸ ਮਿਲਤੀ ਹੈ। ਏਕ ਪਰਮਾਤਮਾ ਕੇ ਹੁਕਮ ਕਰ ਕੇ ਜਨਮ ਮਰਨ ਰੂਪ ਚੌਰਾਸੀ ਮੈ ਸਦਾ ਭ੍ਰਮਾਈਤੇ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
15,2,'G',1,9,1,1,'17','','104,065,115,107,098,104,110,107,','104 065 115 107 098 104 110 107 ','hukmY AMdir sBu ko bwhir hukm n koie ]','Everyone is subject to His Command; no one is beyond His Command.','All are subject to His fiat and none is exempt from His fiat.','ਸਾਰੇ ਉਸ ਦੇ ਅਮਰ ਵਿੱਚ ਹਨ ਅਤੇ ਉਸ ਦੇ ਅਮਰ ਤੋਂ ਬਾਹਰ ਕੋਈ ਨਹੀਂ।','Hukamai Andhar Sabh Ko Baahar Hukam N Koe ||','ਹਰੇਕ ਜੀਵ ਰੱਬ ਦੇ ਹੁਕਮ ਵਿਚ ਹੀ ਹੈ, ਕੋਈ ਜੀਵ ਹੁਕਮ ਤੋਂ ਬਾਹਰ (ਭਾਵ, ਹੁਕਮ ਤੋ ਆਕੀ) ਨਹੀਂ ਹੋ ਸਕਦਾ।','ਸੋ ਸਭ ਕੋਈ ਹੁਕਮ ਹੀ ਕੇ ਅੰਦਰ ਹੈ ਬ੍ਰਹਮਾ ਸੇ ਲੇ ਕਰ ਚੀਟੀ ਪ੍ਰਯੰਤ ਹੁਕਮ ਤੇ ਬਾਹਰ ਕੋਈ ਨਹੀਂ ਹੈ॥☬ਪ੍ਰਸ਼ਨ: ਜੇ ਕਰ ਹੁਕਮ ਮੈ ਹੀ ਹੈਂ, ਤਾਂ ਮੈ ਏਹੁ ਕਰਤਾ ਹਾਂ ਅਰੁ ਏਹੁ ਕਰਾਂਗਾ? ਸੋ ਜੀਉ ਐਸੇ ਕ੍ਯੋਂ ਕਹਿਤਾ ਹੈ ਅਰੁ ਸੋ ਅਹੰਤਾ ਮਮਤਾ ਕੈਸੇ ਛੁਟੈ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
16,2,'G',1,10,1,1,'15','1','110,104,106,098,113,104,107,110,107,','110 104 106 098 113 104 107 110 107 ','nwnk hukmY jy buJY q haumY khY n koie ]2]','O Nanak, one who understands His Command, does not speak in ego. ||2||','O Nanak! if man were to understand Lord''s fiat, then no one would take pride (speak in ego).','ਹੇ ਨਾਨਕ! ਜੇਕਰ ਇਨਸਾਨ ਪ੍ਰਭੂ ਦੇ ਫੁਰਮਾਨ ਨੂੰ ਸਮਝ ਲਵੇ, ਤਦ ਕੋਈ ਭੀ ਹੰਕਾਰ ਨਾਂ ਕਰੇ।','Naanak Hukamai Jae Bujhai Th Houmai Kehai N Koe ||2||','ਹੇ ਨਾਨਕ! ਜੇ ਕੋਈ ਮਨੁੱਖ ਅਕਾਲ ਪੁਰਖ ਦੇ ਹੁਕਮ ਨੂੰ ਸਮਝ ਲਏ ਤਾਂ ਫਿਰ ਉਹ ਸੁਆਰਥ ਦੀਆਂ ਗੱਲਾਂ ਨਹੀਂ ਕਰਦਾ (ਭਾਵ, ਫਿਰ ਉਹ ਸੁਆਰਥੀ ਜੀਵਨ ਛੱਡ ਦੇਂਦਾ ਹੈ) ॥੨॥','ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹੇ ਸਿਧੋ! ਜੇ ਕਰ ਹੁਕਮ ਕੋ ਬੂਝੇ ਤਾਂ ਕੋਈ ਪ੍ਰਕਾਰ ਸੇ (ਹਉਮੈ) ਹੰਕਾਰ ਕੇ ਬਚਨ ਨਹੀਂ ਕਹਤਾ ਕਿ ਮੈ ਨੇ ਏਹਿ ਕੀਆ ਅਰੁ ਏਹਿ ਕਰਾਂਗਾ। ਸਭ ਅਕਾਲ ਪੁਰਖ ਕੀ ਆਗ੍ਯਾ ਹੀ ਮਾਨੇਗੇ॥☬ਪ੍ਰਸ਼ਨ: ਜਿਸ ਕਾ ਐਸਾ ਹੁਕਮ ਹੈ, ਉਸ ਕਾ ਬਲੁ ਕਿਤਨਾਕੁ ਹੈ? ਕ੍ਯੋਂਕਿ ਹੁਕਮੁ ਜੋਰ ਸੇ ਚਲਤਾ ਹੈ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
17,3,'G',1,10,1,1,'9','','103,107,113,104,107,113,','103 107 113 104 107 113 ','gwvY ko qwxu hovY iksY qwxu ]','Some sing of His Power-who has that Power?','Who can sing His might? Who has power to sing it?','ਉਸਦੀ ਸ਼ਕਤੀ ਨੂੰ ਕੌਣ ਗਾਇਨ ਕਰ ਸਕਦਾ ਹੈ? ਇਸ ਨੂੰ ਗਾਇਨ ਕਰਨ ਦਾ ਕੀਹਦੇ ਕੋਲ ਬਲ ਹੈ?','Gaavai Ko Thaan Hovai Kisai Thaan ||','ਜਿਸ ਕਿਸੇ ਮਨੁੱਖ ਨੂੰ ਸਮਰਥਾ ਹੁੰਦੀ ਹੈ, ਉਹ ਰੱਬ ਦੇ ਤਾਣ ਨੂੰ ਗਾਉਂਦਾ ਹੈ, (ਭਾਵ, ਉਸ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਕਰਦਾ ਹੈ ਤੇ ਉਸ ਦੇ ਉਹ ਕੰਮ ਕਥਨ ਕਰਦਾ ਹੈ, ਜਿਨ੍ਹਾਂ ਤੋਂ ਉਸ ਦੀ ਵੱਡੀ ਤਾਕਤ ਪਰਗਟ ਹੋਵੇ)।','ਉਸ ਅਕਾਲ ਪੁਰਖ ਕੇ ਸਮੱਗ੍ਰ (ਤਾਣੁ) ਬਲੁ ਕੋ (ਕੋ ਗਾਵੈ) ਕੌਣ ਗਾਇ ਸਕਤਾ ਹੈ? ਜਬ ਕਿਸੀ ਮੈ ਐਸਾ ਬਲੁ ਹੋਵੈ, ਤੌ ਗਾਇ ਸਕਤਾ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
18,3,'G',1,11,1,1,'9','','103,107,100,106,110,','103 107 100 106 110 ','gwvY ko dwiq jwxY nIswxu ]','Some sing of His Gifts, and know His Sign and Insignia.','Who can sing His bounties and know His resplendent effulgence?','ਕੌਣ ਉਸ ਦੀਆਂ ਬਖ਼ਸ਼ੀਸ਼ਾਂ ਨੂੰ ਅਲਾਪ ਅਤੇ ਉਸ ਦੇ ਨੂਰਾਨੀ ਪਰਤਾਪ ਨੂੰ ਸਮਝ ਸਕਦਾ ਹੈ?','Gaavai Ko Dhaath Jaanai Neesaan ||','ਕੋਈ ਮਨੁੱਖ ਉਸ ਦੀਆਂ ਦਾਤਾਂ ਨੂੰ ਹੀ ਗਾਉਂਦਾ ਹੈ, (ਕਿਉਂਕਿ ਇਹਨਾਂ ਦਾਤਾਂ ਨੂੰ ਉਹ ਰੱਬ ਦੀ ਰਹਿਮਤ ਦਾ) ਨਿਸ਼ਾਨ ਸਮਝਦਾ ਹੈ।','(ਨੀਸਾਣੁ) ਪ੍ਰਗਟ ਅਰਥਾਤ ਇਦੰ ਕਰ ਕੇ ਉਸ ਕੀ ਦਾਤ ਕੋ ਕੌਨ ਜਾਨ ਸਕਦਾ ਹੈ? ਤਾਂ ਤੇ ਉਸ ਕੇ ਬਲ ਕੋ ਕੌਣ ਜਾਣੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
19,3,'G',1,11,1,1,'6','','103,107,103,118,099,','103 107 103 118 099 ','gwvY ko gux vifAweIAw cwr ]','Some sing of His Glorious Virtues, Greatness and Beauty.','Some chant the Lord''s beautiful excellences and magnificences.','ਕਈ ਸੁਆਮੀ ਦੀਆਂ ਸੁੰਦਰ ਵਡਿਆਈਆਂ ਅਤੇ ਬਜ਼ੁਰਗੀਆਂ ਗਾਇਨ ਕਰਦੇ ਹਨ।','Gaavai Ko Gun Vaddiaaeeaa Chaar ||','ਕੋਈ ਮਨੁੱਖ ਰੱਬ ਦੇ ਸੋਹਣੇ ਗੁਣ ਤੇ ਸੋਹਣੀਆਂ ਵਡਿਆਈਆਂ ਵਰਣਨ ਕਰਦਾ ਹੈ।','ਉਸ ਕੇ ਗੁਣਾ ਕੋ ਪੁਨਾ ਵਡਿਆਈਆ ਕੌ (ਚਾਰ) ਚਾਰੇ ਵੇਦ ਕਥਨ ਕਰਤੇ ਹੈਂ, ਪਰੁ ਅੰਤੁ ਨਹੀ ਪਾਵਤੇ ਹੈਂ। ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੌਣੁ ਗਾਇ ਸਕਤਾ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
20,3,'G',1,11,1,1,'6','','103,107,118,118,118,','103 107 118 118 118 ','gwvY ko ividAw ivKmu vIcwru ]','Some sing of knowledge obtained of Him, through difficult philosophical studies.','Who can chant God''s Knowledge, whose study is arduous?','ਵਾਹਿਗੁਰੂ ਦੇ ਇਲਮ ਨੂੰ ਜਿਸ ਦੀ ਸੋਚ ਵਿਚਾਰ ਕਠਨ ਹੈ, ਕੌਣ ਗਾ ਸਕਦਾ ਹੈ?','Gaavai Ko Vidhiaa Vikham Veechaar ||','ਕੋਈ ਮਨੁੱਖ ਵਿੱਦਿਆ ਦੇ ਬਲ ਨਾਲ ਅਕਾਲ ਪੁਰਖ ਦੇ ਕਠਨ ਗਿਆਨ ਨੂੰ ਗਾਉਂਦਾ ਹੈ (ਭਾਵ, ਸ਼ਾਸਤਰ ਆਦਿਕ ਦੁਆਰਾ ਆਤਮਕ ਫ਼ਿਲਾਸਫ਼ੀ ਦੇ ਔਖੇ ਵਿਸ਼ਿਆਂ ''ਤੇ ਵਿਚਾਰ ਕਰਦਾ ਹੈ)।','ਜਿਸ ਕੀ ਵੇਦਾਂਤਾ ਦੀ ਵਿੱਦ੍ਯਾ ਕਾ ਵਿਚਾਰੁ ਵੱਡਾ (ਵਿਖਮੁ) ਕਠਨੁ ਹੈ, ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੌਨੁ ਗਾਇ ਸਕਤਾ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
21,3,'G',1,12,1,1,'6','','103,107,115,107,113,075,','103 107 115 107 113 075 ','gwvY ko swij kry qnu Kyh ]','Some sing that He fashions the body, and then again reduces it to dust.','Some sing that He fashions the body and then reduces it to dust.','ਕਈ ਇਕ ਗਾਇਨ ਕਰਦੇ ਹਨ ਕਿ ਉਹ ਦੇਹ ਨੂੰ ਰਚਦਾ ਹੈ ਤੇ ਫੇਰ ਇਸ ਨੂੰ ਮਿੱਟੀ ਕਰ ਦਿੰਦਾ ਹੈ।','Gaavai Ko Saaj Karae Than Khaeh ||','ਕੋਈ ਮਨੁੱਖ ਇਉਂ ਗਾਉਂਦਾ ਹੈ, ''ਅਕਾਲ ਪੁਰਖ ਸਰੀਰ ਨੂੰ ਬਣਾ ਕੇ (ਫਿਰ) ਸੁਆਹ ਕਰ ਦੇਂਦਾ ਹੈ''।','ਜਿਸ ਪ੍ਰਕਾਰ ਇਨ ਜੀਵੋਂ ਕੇ (ਤਨ) ਸਰੀਰ (ਸਾਜ) ਬਨਾਇ ਕਰਕੇ, ਫਿਰ (ਖੇਹ) ਨਾਸ ਕਰ ਦੇਤਾ ਹੈ। ਵਾ ਜੈਸੇ (ਖੇਹ) ਪ੍ਰਿਥਵੀ ਆਦਿ ਤਤੋਂ ਸੇ ਇਨ ਸਰੀਰੋਂ ਕੋ ਸਾਜਣਾ ਕਰਤਾ ਹੈ, ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੌਨੁ ਗਾਇ ਸਕਤਾ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
22,3,'G',1,12,1,1,'6','','103,107,106,108,080,100,','103 107 106 108 080 100 ','gwvY ko jIA lY iPir dyh ]','Some sing that He takes life away, and then again restores it.','Some sing that God takes away life and again restores it.','ਕਈ ਇਕ ਗਾਇਨ ਕਰਦੇ ਹਨ ਕਿ ਵਾਹਿਗੁਰੂ ਪ੍ਰਾਣ ਲੈ ਲੈਂਦਾ ਹੈ ਤੇ ਮੁੜ ਵਾਪਸ ਦੇ ਦਿੰਦਾ ਹੈ।','Gaavai Ko Jeea Lai Fir Dhaeh ||','ਕੋਈ ਇਉਂ ਗਾਉਂਦਾ ਹੈ, ''ਹਰੀ (ਸਰੀਰਾਂ ਵਿਚੋਂ) ਜਿੰਦਾਂ ਕੱਢ ਕੇ ਫਿਰ (ਦੂਜੇ ਸਰੀਰਾਂ ਵਿਚ) ਪਾ ਦੇਂਦਾ ਹੈ''।','ਸੂਖਮ ਰੂਪੁ ਜੀਵੁ ਜਿਸ ਕੀ ਸੱਤਾ ਕੋ ਪਾਇਕੇ ਇਸ ਸਥੂਲ ਸਰੀਰ ਕੋ ਲਈ ਫਿਰਤਾ ਹੈ, ਵਾ ਇਸ ਸਰੀਰ ਮੈ ਸੇ ਜੀਵ ਨਿਕਾਲ ਲੇਤਾ ਹੈ ਔਰੁ ਜੋ ਸਰੀਰ ਮੇ ਜੀਵ ਪਾਇ ਦੇਤਾ ਹੈ, ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੌਨ ਗਾਇ ਸਕਤਾ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
23,3,'G',1,12,1,1,'6','','103,107,106,100,100,','103 107 106 100 100 ','gwvY ko jwpY idsY dUir ]','Some sing that He seems so very far away.','Some sing that God seems and appears to be far off.','ਕਈ ਗਾਇਨ ਕਰਦੇ ਹਨ ਕਿ ਹਰੀ ਦੁਰੇਡੇ ਮਲੂਮ ਹੁੰਦਾ ਅਤੇ ਸੁੱਝਦਾ ਹੈ।','Gaavai Ko Jaapai Dhisai Dhoor ||','ਕੋਈ ਮਨੁੱਖ ਆਖਦਾ ਹੈ, ''ਅਕਾਲ ਪੁਰਖ ਦੂਰ ਜਾਪਦਾ ਹੈ, ਦੂਰ ਦਿੱਸਦਾ ਹੈ'';','ਜੋ ਜਾਨਨੇ ਸੇ ਔਰ ਦੇਖਨੇ ਸੇ ਦੂਰ ਹੈ। ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੌਨੁ ਗਾਇ ਸਕਤਾ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
24,3,'G',2,1,1,1,'6','','103,107,118,104,104,','103 107 118 104 104 ','gwvY ko vyKY hwdrw hdUir ]','Some sing that He watches over us, face to face, ever-present.','Some sing that He is beholding us just face to face.','ਕਈ ਗਾਇਨ ਕਰਦੇ ਹਨ ਕਿ ਉਹ ਸਾਨੂੰ ਐਨ ਪਰਤੱਖ ਹੀ ਦੇਖ ਰਿਹਾ ਹੈ।','Gaavai Ko Vaekhai Haadharaa Hadhoor ||','ਪਰ ਕੋਈ ਆਖਦਾ ਹੈ, ''(ਨਹੀਂ, ਨੇੜੇ ਹੈ), ਸਭ ਥਾਈਂ ਹਾਜ਼ਰ ਹੈ, ਸਭ ਨੂੰ ਵੇਖ ਰਿਹਾ ਹੈ''।','ਜੇ ਕਰ (ਹਾਦਰਾ ਹਦੂਰਿ) ਹਾਜਰ ਹਜੂਰ, ਭਾਵ ਪ੍ਰਗਟ ਦੇਬੇ ਤੋ ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੋਈ ਗਾਇ ਸਕਤਾ ਹੈ॥☬ਅਬ ਦੂਸਰਾ ਅਰਥ ਕਹਤੇ ਹੈਂ: (ਕੋ) ਕੋਈਕ ਪੁਰਾਣੋ ਵਾਲੇ ਅਕਾਲ ਪੁਰਖ ਕੇ ਬਲ ਕੋ ਜਿਸ ਹਕੁ ਉਨ ਕੋ ਬੁਧਿ ਕਾ ਬਲੁ ਹੋ, ਮਧੁ ਕੋਟਭਾਦਿ ਬਧ ਪ੍ਰਸੰਗ ਲਿਖ ਕਰ ਕੇ ਗਾਵਤੇ ਹੈਂ। ਕੋਈ ਪੰਚ ਰਾਤ੍ਰਿ ਮਤਵਾਲੇ ਨਾਰਦਾਦਿ ਹਾਥ ਪਾਉਂ ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
25,3,'G',2,1,1,1,'6','','107,107,110,065,113,','107 107 110 065 113 ','kQnw kQI n AwvY qoit ]','There is no shortage of those who preach and teach.','There is no dearth of persons who dwell upon the Lord''s discourses.','ਗੋਬਿੰਦ ਦੀਆਂ ਗਿਆਨ ਗੋਸ਼ਟਾਂ ਵਿਚਾਰਨ ਵਾਲਿਆਂ ਪੁਰਸ਼ਾਂ ਦੀ ਕੋਈ ਕਮੀ ਨਹੀਂ।','Kathhanaa Kathhee N Aavai Thott ||','ਹੁਕਮ ਦੇ ਵਰਣਨ ਕਰਨ ਦੀ ਤੋਟ ਨਹੀਂ ਆ ਸਕੀ (ਭਾਵ, ਵਰਣਨ ਕਰ ਕਰ ਕੇ ਹੁਕਮ ਦਾ ਅੰਤ ਨਹੀਂ ਪੈ ਸਕਿਆ, ਹੁਕਮ ਦਾ ਸਹੀ ਸਰੂਪ ਨਹੀਂ ਲੱਭ ਸਕਿਆ);','ਜਿਤਨੇ ਸਿੰਮ੍ਰਿਤੀ, ਪੁਰਾਣ, ਸਾਸਤ੍ਰ ਕੇ ਵੇਤਾ ਹੈਂ ਤਿਨੋ ਨੇ ਪ੍ਰਮੇਸਰ ਕੇ ਸਤ੍ਯ ਸੰਕਲਪ ਆਦਿ ਬਲ ਕੀ ਕਥਾ ਨੂੰ ਕਥਨ ਕੀਆ ਹੈ। ਪਰੰਤੂ (ਤੋਟਿ) ਅੰਤੁ ਕਿਸੀ ਕੋ ਨਹੀਂ ਆਵਤਾ ਹੈ॥☬ਪ੍ਰਸ਼ਨ: ਜੇਕਰ ਬਹੁਤੇ ਮਿਲ ਕਰ ਕਹੇਂ ਤੌ ਅੰਤੁ ਮਿਲ ਜਾਵੇ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
26,3,'G',2,1,1,1,'9','','107,107,107,107,107,107,','107 107 107 107 107 107 ','kiQ kiQ kQI kotI koit koit ]','Millions upon millions offer millions of sermons and stories.','Millions give millions upon millions of descriptions and sermons regarding God.','ਕਰੋੜਾਂ ਹੀ ਬੰਦੇ ਹਰੀ ਬਾਰੇ ਕਰੋੜਾਂ ਉਤੇ ਕਰੋੜਾਂ ਬਿਆਨ ਅਤੇ ਧਰਮ-ਭਾਸ਼ਨ ਦਿੰਦੇ ਹਨ।','Kathh Kathh Kathhee Kottee Kott Kott ||','ਭਾਵੇਂ ਕ੍ਰੋੜਾਂ ਹੀ ਜੀਵਾਂ ਨੇ ਬੇਅੰਤ ਵਾਰੀ (ਅਕਾਲ ਪੁਰਖ ਦੇ ਹੁਕਮ ਦਾ) ਵਰਣਨ ਕੀਤਾ ਹੈ।','ਕ੍ਰੋੜੋਂ ਨੇ ਪੀਛੇ ਕਥਨ ਕਰੀ ਹੈ, ਕ੍ਰੋੜੋਂ ਹੀ ਅਬ ਕਥਨ ਕਰਤੇ ਹੈਂ, ਕ੍ਰੋੜੋਂ ਆਗੇ ਕਥਨ ਕਰੇਂਗੇ, ਪਰੰਤੂ ਅੰਤੁ ਨ ਮਿਲਾ, ਨਾ ਮਿਲਤਾ ਹੈ, ਨਾ ਮਿਲੇਗਾ॥☬ਪ੍ਰਸ਼ਨ: ਐਸੀ ਬਿ੍ਯੰਤ ਕਥਾ ਵਾਲਾ ਦਾਤਾ ਕੈਸਾ ਹੈ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
27,3,'G',2,2,1,1,'6','','100,100,108,081,112,','100 100 108 081 112 ','dydw dy lYdy Qik pwih ]','The Great Giver keeps on giving, while those who receive grow weary of receiving.','The Giver continues giving but the recipients grow weary of receiving.','ਦੇਣ ਵਾਲਾ ਦੇਈ ਜਾਂਦਾ ਹੈ ਪਰੰਤੂ ਲੈਣ ਵਾਲੇ ਲੈ ਕੇ ਹਾਰ ਹੁਟ ਜਾਂਦੇ ਹਨ।','Dhaedhaa Dhae Laidhae Thhak Paahi ||','ਦਾਤਾਰ ਅਕਾਲ ਪੁਰਖ (ਸਭ ਜੀਆਂ ਨੂੰ ਰਿਜ਼ਕ) ਦੇ ਰਿਹਾ ਹੈ, ਪਰ ਜੀਵ ਲੈ ਲੈ ਕੇ ਥੱਕ ਪੈਂਦੇ ਹਨ।','ਵਹੁਦਾਤਾ (ਦੇਦਾ) ਦੇਣੇ ਵਾਲਾ ਜੋ ਹੈ, ਸੋ ਦਾਨੁ ਦੇਤਾ ਹੀ ਰਹਿਤਾ ਹੈ, (ਲੈਦੇ) ਲੈਣੇ ਵਾਲੇ ਥਕ ਜਾਤੇ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
28,3,'G',2,2,1,1,'6','','106,106,075,075,','106 106 075 075 ','jugw jugMqir KwhI Kwih ]','Throughout the ages, consumers consume.','All the ages through the partakers partake of His provision.','ਸਮੂਹ ਜੁਗਾਂ ਅੰਦਰ ਖਾਣ ਵਾਲੇ ਉਸ ਦੇ ਪਦਾਰਥਾਂ ਨੂੰ ਖਾਂਦੇ ਹਨ।','Jugaa Juganthar Khaahee Khaahi ||','(ਸਭ ਜੀਵ) ਸਦਾ ਤੋਂ ਹੀ (ਰੱਬ ਦੇ ਦਿੱਤੇ ਪਦਾਰਥ) ਖਾਂਦੇ ਚਲੇ ਆ ਰਹੇ ਹਨ। ***','ਔਰ ਜੁਗੋਂ ਜੁਗੋਂ ਮੈ ਤਿਸਕੇ ਦੀਏ (ਥਾਹੀ) ਪਦਾਰਥੋਂ ਕੋ ਖਾਤੇ ਹੈਂ॥ ਵਾ ਪੁਨਃ ਪੁਨਃ ਖਾਤੇ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
29,3,'G',2,2,1,1,'7','','104,104,099,114,','104 104 099 114 ','hukmI hukmu clwey rwhu ]','The Commander, by His Command, leads us to walk on the Path.','The Commander, by His command, makes man walk on His path.','ਹਾਕਮ, ਆਪਣੇ ਅਮਰ ਦੁਆਰਾ ਆਦਮੀ ਨੂੰ ਆਪਣੇ ਰਸਤੇ ਉਤੇ ਟੋਰਦਾ ਹੈ।','Hukamee Hukam Chalaaeae Raahu ||','ਹੁਕਮ ਵਾਲੇ ਰੱਬ ਦਾ ਹੁਕਮ ਹੀ (ਸੰਸਾਰ ਦੀ ਕਾਰ ਵਾਲਾ) ਰਸਤਾ ਚਲਾ ਰਿਹਾ ਹੈ।','ਐਸਾ (ਹੁਕਮੀ) ਅਕਾਲ ਪੁਰਖੁ ਅਪਨੇ ਹੁਕਮ ਕੇ ਅੰਦਰ ਅਨੇਕ ਰਸਤੇ ਚਲਾਵਤਾ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
30,3,'G',2,3,1,1,'','1','110,118,118,','110 118 118 ','nwnk ivgsY vyprvwhu ]3]','O Nanak, He blossoms forth, Carefree and Untroubled. ||3||','O Nanak! the carefree Master makes merry.','ਹੇ ਨਾਨਕ! ਬੇ-ਮੁਹਤਾਜ ਮਾਲਕ ਮੌਜ਼ਾ ਮਾਣਦਾ ਹੈ।','Naanak Vigasai Vaeparavaahu ||3||','ਹੇ ਨਾਨਕ! ਉਹ ਨਿਰੰਕਾਰ ਸਦਾ ਵੇਪਰਵਾਹ ਹੈ ਤੇ ਪਰਸੰਨ ਹੈ ॥੩॥','ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹੇ ਸਿਧੋ! ਵਹੁ (ਵੇਪਰਵਾਹ) ਇੱਛਾ ਸੇ ਰਹਿਤ ਹੈ, ਸੋ (ਵਿਗਸੈ) ਪ੍ਰਸਿੰਨ ਹੋਤਾ ਹੈ, ਭਾਵ ਏਹ ਕਿ ਆਪਨੇ ਹੁਕਮ ਮੇਂ ਅਕਾਲ ਪੁਰਖੁ ਸਭ ਕੋ ਚਲਾਉਤਾ ਹੈ, ਔਰ ਜੀਵ ਕਹਤੇ ਹੈਂ "ਮੈਨੇ ਐਸਾ ਕਰਮੁ ਕੀਆ, ਮੈਨੇ ਏਹ ਦੀਆ।" ਇਨ ਅੱਗ੍ਯਾਤਤਾ ਕੇ ਬਚਨੋ ਕੋ ਸੁਨ ਕਰ ਪ੍ਰਸਿੰਨ ਹੋਤਾ ਹੈ, ਕ੍ਰੋਪੁ ਨਹੀਂ ਕਰ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
31,4,'G',2,3,1,1,'18','6','115,115,115,110,066,066,065,','115 115 115 110 066 066 065 ','swcw swihbu swcu nwie BwiKAw Bwau Apwru ]','True is the Master, True is His Name-speak it with infinite love.','True is the Lord, true His Name and the true have repeated His Name with infinite love.','ਸੱਚਾ ਹੈ ਸੁਆਮੀ, ਸੱਚਾ ਹੈ ਉਸਦਾ ਨਾਮ ਅਤੇ ਸਚਿਆਰਾ ਨੇ ਉਸ ਦੇ ਨਾਮ ਨੂੰ ਬੇਅੰਤ ਪਿਆਰ ਨਾਲ ਉਚਾਰਨ ਕੀਤਾ ਹੈ।','Saachaa Saahib Saach Naae Bhaakhiaa Bhaao Apaar ||','ਅਕਾਲ ਪੁਰਖ ਸਦਾ-ਥਿਰ ਰਹਿਣ ਵਾਲਾ ਹੀ ਹੈ, ਉਸ ਦਾ ਨਿਯਮ ਭੀ ਸਦਾ ਅਟੱਲ ਹੈ। ਉਸ ਦੀ ਬੋਲੀ ਪ੍ਰੇਮ ਹੈ ਅਤੇ ਉਹ ਆਪ ਅਕਾਲ ਪੁਰਖ ਬੇਅੰਤ ਹੈ।','ਹੇ ਸਿੱਧੋ! ਵਹੁ ਸਾਹਿਬੁ ਭੀ ਸਚਾ ਹੈ ਔਰ ਉਸ ਕਾ ਨਾਮੁ ਭੀ ਸਚਾ ਹੈ। ਸੋ ਨਾਮੁ ਤਿਨੋ ਨੇ (ਭਾਖਿਆ) ਕਹਿਆ ਹੈ, ਜਿਨ ਕੋ ਅਪਾਰ ਹੀ ਪ੍ਰੇਮ ਹੂਆ ਹੈ। ਵਾ ਜਿਨੋ ਨੇ ਭਾਖ੍ਯਾ ਹੈ, ਤਿਨ ਕੋ ਅਪਾਰ ਪਰਮਾਤਮਾ ਕਾ (ਭਾਉ) ਗ੍ਯਾਨੁ ਹੂਆ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
32,4,'G',2,3,1,1,'18','7','065,109,100,100,100,107,100,','065 109 100 100 100 107 100 ','AwKih mMgih dyih dyih dwiq kry dwqwru ]','People beg and pray, "Give to us, give to us", and the Great Giver gives His Gifts.','People pray and beg: "give us alms, give us alms", and the bestower bestows His gifts.','ਲੋਕੀਂ ਪ੍ਰਾਰਥਨਾ ਤੇ ਯਾਚਨਾ ਕਰਦੇ ਹਨ: "ਸਾਨੂੰ ਖੈਰ ਪਾ, ਸਾਨੂੰ ਖੈਰ ਪਾ", ਤੇ ਦਾਤਾ ਬਖ਼ਸ਼ਿਸ਼ਾਂ ਕਰਦਾ ਹੈ।','Aakhehi Mangehi Dhaehi Dhaehi Dhaath Karae Dhaathaar ||','ਅਸੀਂ ਜੀਵ ਉਸ ਪਾਸੋਂ ਦਾਤਾਂ ਮੰਗਦੇ ਹਾਂ ਤੇ ਆਖਦੇ ਹਾਂ,''(ਹੇ ਹਰੀ! ਸਾਨੂੰ ਦਾਤਾਂ) ਦੇਹ''। ਉਹ ਦਾਤਾਰ ਬਖ਼ਸ਼ਸ਼ਾਂ ਕਰਦਾ ਹੈ।','ਤਿਸ ਦਾਤਾਰ ਅਕਾਲ ਪੁਰਖ ਸੇ (ਆਖਹਿ) ਮੁਖੋਂ ਸੇ ਦੇਹ ਦੇਹ ਕਹਿ ਕਰ ਸਭੀ ਮਾਗਤੇ ਹੈਂ, ਔਰ ਸੋ ਕਰਮਾ ਅਨੁਸਾਰ ਯਥੋਚਿਤ ਦਾਤ ਦੇਤਾ ਹੈ॥ ਪ੍ਰਸ਼ਨ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
33,4,'G',2,4,1,1,'13','1','080,107,065,114,106,100,100,','080 107 065 114 106 100 100 ','Pyir ik AgY rKIAY ijqu idsY drbwru ]','So what offering can we place before Him, by which we might see the Darbaar of His Court?','Then, what should be placed before His where-by His court may be seen?','ਤਾਂ, ਉਸ ਦੇ ਅਗੇ ਕੀ ਧਰਿਆ ਜਾਵੇ ਜਿਸ ਦੁਆਰਾ ਉਸ ਦੀ ਦਰਗਾਹ ਦਾ ਦਰਸ਼ਨ ਹੋ ਜਾਵੇ?','Faer K Agai Rakheeai Jith Dhisai Dharabaar ||','(ਜੇ ਸਾਰੀਆਂ ਦਾਤਾਂ ਉਹ ਆਪ ਹੀ ਬਖਸ਼ ਰਿਹਾ ਹੈ ਤਾਂ) ਫਿਰ ਅਸੀਂ ਕਿਹੜੀ ਭੇਟਾ ਉਸ ਅਕਾਲ ਪੁਰਖ ਦੇ ਅੱਗੇ ਰੱਖੀਏ, ਜਿਸ ਦੇ ਸਦਕੇ ਸਾਨੂੰ ਉਸ ਦਾ ਦਰਬਾਰ ਦਿੱਸ ਪਏ?','ਤਿਸ ਅਕਾਲ ਪੁਰਖ ਕੇ ਆਗੇ (ਫੇਰਿ) ਭੇਟਾ ਕ੍ਯਾ ਰਖੀਏ ਵਾ ਮੁੜਕੇ ਕ੍ਯਾ ਰੱਖੀਏ⁽¹⁾? ਜਿਸ ਸੇ ਤਿਸ ਸੱਚੇ (ਦਰਬਾਰੁ) ਦੀਵਾਨ, ਭਾਵ ਸਰੂਪ ਕਾ ਦਰਸਨੁ ਹੋ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
34,4,'G',2,4,1,1,'15','1','109,107,098,098,106,115,068,112,','109 107 098 098 106 115 068 112 ','muhO ik bolxu bolIAY ijqu suix Dry ipAwru ]','What words can we speak to evoke His Love?','Which words should we utter with our mouths by hearing which, He may begin to bear us love?','ਅਸੀਂ ਆਪਣੇ ਮੁੱਖਾਂ ਤੇ ਕੇਹੜੇ ਬਚਨ ਉਚਾਰਨ ਕਰੀਏ ਜਿੰਨ੍ਹਾਂ ਨੂੰ ਸਰਵਣ ਕਰਕੇ, ਉਹ ਸਾਡੇ ਨਾਲ ਮੁਹੱਬਤ ਕਰਨ ਲੱਗ ਜਾਵੇ?','Muha K Bolan Boleeai Jith Sun Dhharae Piaar ||','ਅਸੀਂ ਮੂੰਹੋਂ ਕਿਹੜਾ ਬਚਨ ਬੋਲੀਏ (ਭਾਵ, ਕਿਹੋ ਜਿਹੀ ਅਰਦਾਸ ਕਰੀਏ) ਜਿਸ ਨੂੰ ਸੁਣ ਕੇ ਉਹ ਹਰੀ (ਸਾਨੂੰ) ਪਿਆਰ ਕਰੇ।','ਔਰ ਮੁਹ ਸੇ ਕ੍ਯਾ (ਬੋਲਣੁ) ਬਚਨੁ ਕਹੀਏ, ਜਿਸ ਕੋ ਸੁਨ ਕਰ ਅਕਾਲ ਪੁਰਖੁ ਪ੍ਯਾਰੁ ਧਾਰਨ ਕਰੇ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
35,4,'G',2,5,1,1,'17','','065,118,115,110,118,118,','065 118 115 110 118 118 ','AMimRq vylw scu nwau vifAweI vIcwru ]','In the Amrit Vaylaa, the ambrosial hours before dawn, chant the True Name, and contemplate His Glorious Greatness.','Early in the morning utter the True Name and reflect upon God''s greatness.','ਸੁਬ੍ਹਾ ਸਵੇਰੇ ਸਤਿਨਾਮ ਦਾ ਉਚਾਰਨ ਕਰ ਅਤੇ ਵਾਹਿਗੁਰੂ ਦੀਆਂ ਬਜ਼ੁਰਗੀਆਂ ਦਾ ਧਿਆਨ ਧਰ।','Anmrith Vaelaa Sach Naao Vaddiaaee Veechaar ||','ਪੂਰਨ ਖਿੜਾਉ ਦਾ ਸਮਾਂ ਹੋਵੇ (ਭਾਵ, ਪ੍ਰਭਾਤ ਵੇਲਾ ਹੋਵੇ), ਨਾਮ (ਸਿਮਰੀਏ) ਤੇ ਉਸ ਦੀਆਂ ਵਡਿਆਈਆਂ ਦੀ ਵਿਚਾਰ ਕਰੀਏ।','ਹੇ ਸਿਧੋ! ਅੰਮ੍ਰਿਤ ਵੇਲੇ ਸਚ ਨਾਮ ਕਾ ਜਾਪੁ ਕਰਨਾ, ਏਹੀ ਭੇਟਾ ਰਖੀਏ। ਇਸੀ ਤੇ ਤਿਸ ਕਾ ਦ੍ਰਬਾਰੁ ਦ੍ਰਿਸਟਿ ਆਵਤਾ ਹੈ। ਜੈਸੇ ਭਗਤੋਂ ਕੀ ਰੱਖ੍ਯਾ ਕਰੀ ਹੈ, ਇੱਤ੍ਯਾਦਿਕ ਵਡਿਆਈ ਕਾ ਵੀਚਾਰੁ ਕਰ ਕੇ ਕੀਰਤਨ ਕਰਨਾ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
36,4,'G',2,5,1,1,'11','','107,065,107,110,109,100,','107 065 107 110 109 100 ','krmI AwvY kpVw ndrI moKu duAwru ]','By the karma of past actions, the robe of this physical body is obtained. By His Grace, the Gate of Liberation is found.','By Good actions the physical robe is obtained and by the Lord''s benediction the gate of salvation.','ਚੰਗੇ ਅਮਲਾਂ ਦੁਆਰਾ ਦੇਹ ਪੁਸ਼ਾਕ ਪਰਾਪਤ ਹੁੰਦੀ ਹੈ ਅਤੇ ਸੁਆਮੀ ਦੀ ਦਯਾ ਦੁਆਰਾ ਮੁਕਤੀ ਦਾ ਦਰਵਾਜਾ।','Karamee Aavai Kaparraa Nadharee Mokh Dhuaar ||','(ਇਸ ਤਰ੍ਹਾਂ) ਪ੍ਰਭੂ ਦੀ ਮਿਹਰ ਨਾਲ ''ਸਿਫਤਿ'' ਰੂਪ ਪਟੋਲਾ ਮਿਲਦਾ ਹੈ, ਉਸ ਦੀ ਕ੍ਰਿਪਾ-ਦ੍ਰਿਸ਼ਟੀ ਨਾਲ ''ਕੂੜ ਦੀ ਪਾਲਿ'' ਤੋਂ ਖ਼ਲਾਸੀ ਹੁੰਦੀ ਹੈ ਤੇ ਰੱਬ ਦਾ ਦਰ ਪ੍ਰਾਪਤ ਹੋ ਜਾਂਦਾ ਹੈ।','ਤਿਸ ਕੋ ਸੁਨ ਕੇ ਸਚਾ ਸਾਹਿਬੁ ਪ੍ਯਾਰੁ ਧਾਰਤਾ ਹੈ। ਔਰ ਐਸੇ ਉਪਾਸਨਾ ਰੂਪੁ ਕਰਮ ਕੇ ਕਰਨ ਹਾਰਾ ਜਬ ਜੀਉ ਕਰਮੀ ਹੋਤਾ ਹੈ, ਤਬ (ਨਦਰੀ) ਹਰੀ ਕੀ ਕ੍ਰਿਪਾ ਦ੍ਰਿਸਟੀ ਸੇ (ਕਪੜਾ) ਭਗਤੀ ਰੂਪੁ ਸਿਰੋਪਾਉ ਮਿਲਤਾ ਹੈ। ਔਰੁ ਤਿਸੁ ਸੇ ਮੋਖ ਕਾ ਦ੍ਵਾਰਾ ਗ੍ਯਾਨੁ ਪ੍ਰਾਪਤਿ ਹੋਤਾ ਹੈ⁽¹⁾॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
37,4,'G',2,6,1,1,'11','1','110,101,106,115,065,115,','110 101 106 115 065 115 ','nwnk eyvY jwxIAY sBu Awpy sicAwru ]4]','O Nanak, know this well: the True One Himself is All. ||4||','Know thus, O Nanak! that the True One is all by Himself.','ਇਸ ਤਰ੍ਹਾਂ ਸਮਝ ਲੈ, ਹੇ ਨਾਨਕ! ਕਿ ਸਤਿਪੁਰਖ ਸਾਰਾ ਕੁਛ ਆਪਣੇ ਆਪ ਤੋਂ ਹੀ ਹੈ।','Naanak Eaevai Jaaneeai Sabh Aapae Sachiaar ||4||','ਹੇ ਨਾਨਕ! ਇਸ ਤਰ੍ਹਾਂ ਇਹ ਸਮਝ ਆ ਜਾਂਦੀ ਹੈ ਕਿ ਉਹ ਹੋਂਦ ਦਾ ਮਾਲਕ ਅਕਾਲ ਪੁਰਖ ਸਭ ਥਾਈਂ ਭਰਪੂਰ ਹੈ ॥੪॥','ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹੇ ਸਿੱਧੋ! (ਏਵੈ) ਇਸ ਪ੍ਰਕਾਰ ਜਾਨੀਏ ਜੋ (ਸਚਿਆਰੁ) ਸਚਾ ਅਕਾਲ ਪੁਰਖੁ ਸਰਬ ਠੌਰ ਆਪ ਹੀ ਹੈ। ਯਥਾ ਸੁਖਮਨੀ-☬"ਬਨ ਤ੍ਰਿਣ ਪਰਬਤ ਹੈ ਪਾਰਬ੍ਰਹਮੁ॥" ॥੪॥☬ਪ੍ਰਸ਼ਨ: ਵਹੁ ਕਿਸੀ ਕਾ ਕੀਆ ਹੂਆ ਹੈ, ਭਾਵ ਨਾਦੀ ਹੈ ਵਾ ਬਿੰਦੀ ਹੈ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
38,5,'G',2,6,1,1,'10','','081,110,106,107,110,104,','081 110 106 107 110 104 ','QwipAw n jwie kIqw n hoie ]','He cannot be established, He cannot be created.','He is neither established nor created by any one.','ਉਹ ਕਿਸੇ ਦਾ ਨਾਂ ਅਸਥਾਪਨ ਕੀਤਾ ਅਤੇ ਨਾਂ ਹੀ ਬਣਾਇਆ ਹੋਇਆ ਹੈ।','Thhaapiaa N Jaae Keethaa N Hoe ||','ਨਾ ਉਹ ਪੈਦਾ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ ਅਤੇ ਨਾ ਹੀ ਸਾਡਾ ਬਣਾਇਆ ਬਣਦਾ ਹੈ।','ਹੇ ਸਿੱਧੋ! ਸੋ ਅਕਾਲ ਪੁਰਖੁ ਕਿਸੀ ਕਾ ਸਥਾਪਿਤ ਨਹੀਂ ਕੀਆ ਹੂਆ, ਭਾਵ ਨਾਦੀ ਭੀ ਨਹੀਂ ਔਰੁ ਨ ਕਿਸੀ ਕਾ ਬਿੰਦੀ ਉਤਪਤਿ ਕੀਆ ਹੂਆ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
39,5,'G',2,7,1,1,'6','','065,065,110,115,','065 065 110 115 ','Awpy Awip inrMjnu soie ]','He Himself is Immaculate and Pure.','That Pure One is all in all Himself.','ਉਹ ਪਵਿਤਰ ਪੁਰਖ ਸਾਰਾ ਕੁਛ ਆਪ ਹੀ ਹੈ।','Aapae Aap Niranjan Soe ||','ਉਹ ਨਿਰੋਲ ਆਪ ਹੀ ਆਪ ਹੈ। ਉਹ ਅਕਾਲ ਪੁਰਖ ਮਾਇਆ ਦੇ ਪਰਭਾਵ ਤੋਂ ਪਰੇ ਹੈ।','ਵਹੁ ਨਿਰੰਜਨੁ ਮਾਯਾ ਮਲ ਸੇ ਰਹਿਤ ਆਪੇ ਹੀ ਆਪ ਸੁਤੇ ਸਿੱਧ ਹੈ, ਭਾਵ ਅਨਾਦਿ, ਅਨੰਤ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
40,5,'G',2,7,1,1,'6','','106,115,113,112,109,','106 115 113 112 109 ','ijin syivAw iqin pwieAw mwnu ]','Those who serve Him are honored.','They who serve Him, obtain honour.','ਜਿਨ੍ਹਾਂ ਨੇ ਉਸ ਦੀ ਟਹਿਲ ਸੇਵਾ ਕਮਾਈ, ਉਨ੍ਹਾਂ ਨੂੰ ਇਜ਼ਤ ਪਰਾਪਤ ਹੋਈ।','Jin Saeviaa Thin Paaeiaa Maan ||','ਜਿਸ ਮਨੁੱਖ ਨੇ ਉਸ ਅਕਾਲ ਪੁਰਖ ਨੂੰ ਸਿਮਰਿਆ ਹੈ, ਉਸ ਨੇ ਹੀ ਵਡਿਆਈ ਪਾ ਲਈ ਹੈ।','ਜਿਨਿ ਗੁਰਮੁਖੋਂ ਨੇ ਸੇਵਨ ਕੀਆ ਹੈ, ਤਿਨੋ ਨੇ ਮਾਨੁ ਪਾਯਾ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
41,5,'G',2,7,1,1,'6','','110,103,103,110,','110 103 103 110 ','nwnk gwvIAY guxI inDwnu ]','O Nanak, sing of the Lord, the Treasure of Excellence.','O Nanak! sing praises of the Lord who is the treasure of excellences.','ਹੇ ਨਾਨਕ! ਉਸ ਦੀ ਸਿਫ਼ਤ ਸ਼ਲਾਘਾ ਗਾਇਨ ਕਰ ਜੋ ਉਤਕ੍ਰਿਸ਼ਟਰਾਈਆਂ ਦਾ ਖ਼ਜ਼ਾਨਾ ਹੈ।','Naanak Gaaveeai Gunee Nidhhaan ||','ਹੇ ਨਾਨਕ! (ਆਓ) ਅਸੀਂ ਭੀ ਉਸ ਗੁਣਾਂ ਦੇ ਖ਼ਜ਼ਾਨੇ ਹਰੀ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਕਰੀਏ।','ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਐਸਾ ਨਿਸਚਾ ਕਰ ਕੇ (ਗੁਣੀ ਨਿਧਾਨੁ) ਗੁਣਾਂ ਕਾ ਖਜਾਨਾ, ਭਾਵ ਅਕਾਲ ਪੁਰਖ ਕੇ ਗੁਣੋਂ ਕੋ ਗਾਉਣਾ ਚਾਹੀਏ॥☬ਪ੍ਰਸ਼ਨ: ਗਾਨਾ ਤਬ ਹੋਤਾ ਹੈ, ਜਬ ਕੋਈ ਸ੍ਰੋਤਾ ਹੋ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
42,5,'G',2,8,1,1,'8','','103,115,109,114,066,','103 115 109 114 066 ','gwvIAY suxIAY min rKIAY Bwau ]','Sing, and listen, and let your mind be filled with love.','With the Lord''s love reposed in thy heart sing and hear His praises.','ਪ੍ਰਭੂ ਦੀ ਪ੍ਰੀਤ ਨੂੰ ਆਪਣੇ ਦਿਲ ਅੰਦਰ ਟਿਕਾ ਕੇ ਉਸ ਦੀ ਕੀਰਤੀ ਗਾਇਨ ਤੇ ਸਰਵਣ ਕਰ।','Gaaveeai Suneeai Man Rakheeai Bhaao ||','(ਆਓ, ਅਕਾਲ ਪੁਰਖ ਦੇ ਗੁਣ) ਗਾਵੀਏ ਤੇ ਸੁਣੀਏ ਅਤੇ ਆਪਣੇ ਮਨ ਵਿਚ ਉਸਦਾ ਪ੍ਰੇਮ ਟਿਕਾਈਏ।','ਅਪਨੇ ਸੇ ਨ੍ਯੂਨ ਪਾਸ (ਗਾਵੀਐ) ਕਥਨ ਕਰੀਏ ਅਰੁ ਅਪਨੇ ਤੇ ਅਧਿਕ ਸੇ ਸੁਣੀਏ। ਜਬ ਦੋਨੋ ਕਾ ਸੰਜੋਗ ਨਾ ਹੋ, ਤਬ ਮਨ ਮੇਂ (ਭਾਉ) ਪ੍ਰੇਮੁ ਰਖੀਏ ਵਾ (ਗਾਵੀਐ) ਜੋ ਗਾਵਨ ਵਾਲੇ ਵਕਤਾ ਸ੍ਰੀ ਸਤਿਗੁਰੂ ਜੀ ਹੈਂ, ਤਿਨ ਸੇ (ਸੁਣੀਏ) ਸ੍ਰਵਣ ਕਰੀਏ, ਪੁਨਾ (ਮਨ) ਮਨਨ ਕਰੀਏ, ਪੁਨਾ (ਰਖੀਏ) ਨਿਦਿਧ੍ਯਾਸਨੁ ਕਰੀਏ ਤਬ (ਭਾਉ) ਪ੍ਰਤੱਖ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
43,5,'G',2,8,1,1,'6','','100,112,115,071,108,106,','100 112 115 071 108 106 ','duKu prhir suKu Gir lY jwie ]','Your pain shall be sent far away, and peace shall come to your home.','Thus shalt thou shed pain and shalt take happiness to thy home.','ਇਸ ਤਰ੍ਹਾਂ ਤੇਰੀ ਤਕਲੀਫ ਦੂਰ ਹੋ ਜਾਵੇਗੀ ਅਤੇ ਤੂੰ ਖੁਸ਼ੀ ਆਪਣੇ ਗ੍ਰਹਿ ਨੂੰ ਲੈ ਜਾਵੇਂਗਾ।','Dhukh Parehar Sukh Ghar Lai Jaae ||','(ਜੋ ਮਨੁੱਖ ਇਹ ਆਹਰ ਕਰਦਾ ਹੈ, ਉਹ) ਆਪਣਾ ਦੁੱਖ ਦੂਰ ਕਰਕੇ ਸੁੱਖ ਨੂੰ ਹਿਰਦੇ ਵਿਚ ਵਸਾ ਲੈਂਦਾ ਹੈ।','ਤਿਸ ਕਾ ਫਲੁ ਦੁਖੋਂ ਕੋ (ਪਰ) ਭਲੀ ਪ੍ਰਕਾਰ (ਹਰਿ) ਨਾਸੁ ਕਰ ਕੇ ਸਰਬ ਸੁਖੋਂ ਕੇ ਘਰਿ ਆਤਮ ਸੁਖੁ, ਭਾਵ ਜਿਸ ਸੁਖ ਕੇ ਲੇਸ ਤੇ ਚੌਦਾਂ ਭਵਨ ਮੇ ਜੀਵਯ ਅਨੰਦੀ ਹੋ ਰਹੇ ਹੈਂ, ਉਸ ਮੇ (ਲੈ ਜਾਇ) ਅਭਿੰਨ ਹੋ ਜਾਤਾ ਹੈ॥☬ਪ੍ਰਸ਼ਨ: ਤਿਸ ਅਭਿੰਨਤਾ ਮੈ ਉਦਾਹਰਣੁ ਕਹੀਏ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
44,5,'G',2,8,1,1,'22','9','103,110,103,118,103,114,115,','103 110 103 118 103 114 115 ','gurmuiK nwdM gurmuiK vydM gurmuiK rihAw smweI ]','The Guru''s Word is the Sound-current of the Naad; the Guru''s Word is the Wisdom of the Vedas; the Guru''s Word is all-pervading.','Gurbani is the Divine Word, Gurbani the Lord''s Knowledge and through Gurbani the Lord is realised to be all pervading.','ਗੁਰਬਾਣੀ ਰੱਬੀ ਕਲਾਮ ਹੈ, ਗੁਰਬਾਨੀ ਸਾਹਿਬ ਦਾ ਗਿਆਨ ਅਤੇ ਗੁਰਬਾਣੀ ਰਾਹੀਂ ਹੀ ਸੁਆਮੀ ਨੂੰ ਸਾਰੇ ਵਿਆਪਕ ਅਨੁਭਵ ਕੀਤਾ ਜਾਂਦਾ ਹੈ।','Guramukh Naadhan Guramukh Vaedhan Guramukh Rehiaa Samaaee ||','(ਪਰ ਉਸ ਰੱਬ ਦਾ) ਨਾਮ ਤੇ ਗਿਆਨ ਗੁਰੂ ਦੀ ਰਾਹੀਂ (ਪ੍ਰਾਪਤ ਹੁੰਦਾ ਹੈ)। ਗੁਰੂ ਦੀ ਰਾਹੀਂ ਹੀ (ਇਹ ਪਰਤੀਤ ਆਉਂਦੀ ਹੈ ਕਿ) ਉਹ ਹਰੀ ਸਭ ਥਾਈਂ ਵਿਆਪਕ ਹੈ।','ਗੁਰੂ ਜੋ ਮੁਖ ਹੈਂ ਤਿਨਾ ਦਾ ਜੋ (ਨਾਦੰ) ਸਬਦੁ ਹੈ, ਜਬ ਗੁਰਮੁਖਿ ਜਗ੍ਯਾਸੂ ਨੇ ਸੁਣ ਕੇ ਤਿਸ ਕੇ ਸਿਧਾਂਤ ਕੋ (ਵੇਦੰ) ਜਾਣਿਆਂ, ਤਬ ਗੁਰੂ ਜੋ ਹੈ ਪੂਜ੍ਯ ਮੁਖੁ ਪਰਮਾਤਮਾ ਤਿਸ ਮੈ (ਰਹਿਆ ਸਮਾਈ) ਅਭਿੰਨ ਹੋ ਰਹਿਤਾ ਹੈ॥☬ਪ੍ਰਸ਼ਨ: ਐਸੇ ਗੁਰੋਂ ਕੀ ਮਹਿਮਾ ਸੁਨਾਓ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
45,5,'G',2,9,1,1,'28','6,17','103,101,103,103,098,103,112,109,','103 101 103 103 098 103 112 109 ','guru eIsru guru gorKu brmw guru pwrbqI mweI ]','The Guru is Shiva, the Guru is Vishnu and Brahma; the Guru is Paarvati and Lakhshmi.','The Guru is Shiva, the Guru Vishnu and Brahma, the Guru is Shiva''s consort Parbati, Vishnu''s consort Lakhshmi and Brahma''s consort Saraswati.','ਗੁਰੂ ਸ਼ਿਵ ਹੈ, ਗੁਰੂ ਹੀ ਵਿਸ਼ਨੂੰ ਤੇ ਬ੍ਰਹਮਾਂ, ਗੁਰੂ ਹੀ ਸ਼ਿਵ ਦੀ ਪਤਨੀ-ਪਾਰਬਤੀ, ਵਿਸ਼ਨੂੰ ਦੀ ਪਤਨੀ ਲਖਸ਼ਮੀ ਅਤੇ ਬ੍ਰਹਮਾ ਦੀ ਪਤਨੀ-ਸੁਰਸਵਤੀ ਹੈ।','Gur Eesar Gur Gorakh Baramaa Gur Paarabathee Maaee ||','ਗੁਰੂ ਹੀ (ਸਾਡੇ ਲਈ) ਸ਼ਿਵ ਹੈ, ਗੁਰੂ ਹੀ (ਸਾਡੇ ਲਈ) ਗੋਰਖ ਤੇ ਬ੍ਰਹਮਾ ਹੈ ਅਤੇ ਗੁਰੂ ਹੀ (ਸਾਡੇ ਲਈ) ਮਾਈ ਪਾਰਬਤੀ ਹੈ।','ਗੁਰੂ ਧਾਰਨ ਕਰ ਕੇ ਹੀ (ਈਸਰੁ) ਸਿਵ ਜੀ ਹੂਏ ਹੈਂ, ਗੁਰੂ ਹੀ ਧਾਰਨ ਕਰ ਕੇ (ਗੋਰਖੁ) ਬਿਸਨ ਜੀ ਹੂਏ ਹੈਂ, ਗੁਰੂ ਹੀ ਧਾਰਨ ਕਰ ਕੇ (ਬਰਮਾ) ਬ੍ਰਹਮਾ ਜੀ ਹੂਏ ਹੈਂ, ਗੁਰੂ ਹੀ ਧਾਰਨ ਕਰ ਕੇ ਪਾਰਬਤੀ ਜੀ (ਮਾ) ਲੱਛਮੀ ਜੀ, (ਈ) ਸੁਰਸਤੀ ਜੀ ਹੂਈ ਹੈ। ਵਾ ਗੁਰੂ ਹੀ ਸਰਬ ਦੇਵ ਰੂਪ ਹੈਂ। ਈਸਰ ਕਾ ਗੁਨੁ ਧਾਰ ਕਰ ਸਿੱਖੋਂ ਕਾ ਅ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
46,5,'G',2,9,1,1,'18','8','106,104,106,065,110,107,107,110,106,','106 104 106 065 110 107 107 110 106 ','jy hau jwxw AwKw nwhI khxw kQnu n jweI ]','Even knowing God, I cannot describe Him; He cannot be described in words.','Even though I Know God, I cannot narrate Him, He cannot be described by words.','ਭਾਵੇਂ ਮੈਂ ਵਾਹਿਗੁਰੂ ਨੂੰ ਜਾਣਦਾ ਹਾਂ, ਮੈਂ ਉਸ ਨੂੰ ਵਰਣਨ ਨਹੀਂ ਕਰ ਸਕਦਾ। ਬਚਨਾ ਦੁਆਰਾ ਉਹ ਬਿਆਨ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ।','Jae Ho Jaanaa Aakhaa Naahee Kehanaa Kathhan N Jaaee ||','ਉਂਝ (ਇਸ ਅਕਾਲ ਪੁਰਖ ਦੇ ਹੁਕਮ ਨੂੰ) ਜੇ ਮੈਂ ਸਮਝ, (ਭੀ) ਲਵਾਂ, (ਤਾਂ ਭੀ) ਉਸ ਦਾ ਵਰਣਨ ਨਹੀਂ ਕਰ ਸਕਦਾ। (ਅਕਾਲ ਪੁਰਖ ਦੇ ਹੁਕਮ ਦਾ) ਕਥਨ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ।','ਹੇ ਸਿੱਧੋ! ਐਸੇ ਸਤਿਗੁਰੋਂ ਕੀ ਮਹਿਮਾ ਜੇਕਰ ਮੈ ਇਦੰਤਾ ਕਰ ਜਾਨੋ ਤੋ ਕ੍ਯਾ ਨਾ ਕਹੂੰ, ਭਾਵ ਬ੍ਯੰਤ ਹੈ। ਜੇਕਰ ਮੈ ਕਹਿਣਾ ਭੀ ਚਾਹੂੰ ਤੌ ਮਨ ਬਾਣੀ ਕਾ ਅਵਿਸੇ ਹੋਨੇ ਕਰ ਕੇ ਕਥਨੁ ਨਹੀਂ ਕਰੀ ਜਾਤੀ॥☬ਪ੍ਰਸ਼ਨ: ਕੁਛ ਤੇ ਕਹੀਏ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
47,5,'G',2,10,1,1,'1','','103,101,100,098,','103 101 100 098 ','gurw iek dyih buJweI ]','The Guru has given me this one understanding:','The Guru has explained one thing to me.','ਗੁਰੂ ਨੇ ਮੈਨੂੰ ਇਕ ਚੀਜ਼ ਸਮਝਾ ਦਿਤੀ ਹੈ।','Guraa Eik Dhaehi Bujhaaee ||','(ਮੇਰੀ ਤਾਂ) ਹੇ ਸਤਿਗੁਰੂ! (ਤੇਰੇ ਅੱਗੇ ਅਰਦਾਸ ਹੈ ਕਿ) ਮੈਨੂੰ ਇਕ ਸਮਝ ਦੇਹ,','ਗੁਰੋਂ ਨੇ ਮੁਝ ਕੋ ਏਕ ਬੂਝ ਦਿਤੀ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
48,5,'G',2,10,1,1,'19','27','115,106,107,101,100,115,109,118,110,106,','115 106 107 101 100 115 109 118 110 106 ','sBnw jIAw kw ieku dwqw so mY ivsir n jweI ]5]','There is only the One, the Giver of all souls. May I never forget Him! ||5||','There is but one Bestower for all the beings May, I never forget Him.','ਸਮੂਹ ਜੀਵਾਂ ਦਾ ਕੇਵਲ ਇਕ ਦਾਤਾਰ ਹੈ। ਉਹ ਮੈਨੂੰ ਕਦੇ ਭੀ ਨਾਂ ਭੁਲੇ।','Sabhanaa Jeeaa Kaa Eik Dhaathaa So Mai Visar N Jaaee ||5||','ਕਿ ਜਿਹੜਾ ਸਭਨਾਂ ਜੀਵਾਂ ਨੂੰ ਦਾਤਾਂ ਦੇਣ ਵਾਲਾ ਇਕ ਰੱਬ ਹੈ, ਮੈਂ ਉਸ ਨੂੰ ਭੁਲਾ ਨਾ ਦਿਆਂ ॥੫॥','ਸਭ ਜੀਵੋਂ ਕਾ ਦਾਤਾ ਏਕੁ ਅਕਾਲ ਪੁਰਖ ਹੈ। ਹੇ ਸਿਧੋ! ਸੋ ਮੁਝ ਕੋ ਵਿਸਰਤਾ ਨਹੀਂ ਹੈ॥☬ਉੱਤਰ ਮੈ ਗੁਰੁ ਜੀ ਕੀ ਚਤੁਰਾਈ ਸਮਝ ਕੇ ਸਿਧੋਂ ਕੇ ਮਨ ਮੈ ਲੋਭੁ ਹੂਆ, ਕਿ ਨਾਨਕ ਨਿਰੰਕਾਰੀ ਹਮਾਰੇ ਮਤ ਮੈ ਆ ਜਾਵੇ ਤੋ ਹਮਾਰਾ ਪ੍ਰਤਾਪੁ ਵੱਡਾ ਹੋ ਜਾਵੇ। ਏਹ ਜਾਨ ਕਰ ਕਹਤੇ ਭਏ ਕਿ ਹੇ ਬਾਲੇ! ਤੈਨੂੰ ਤੀਰਥ ਕਰਾਈਏ ਅਰੁ ਰਤਨਾ ਕੀ ਖ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
49,6,'G',2,11,1,1,'20','7,30','113,110,106,113,066,118,066,107,110,107,','113 110 106 113 066 118 066 107 110 107 ','qIriQ nwvw jy iqsu Bwvw ivxu Bwxy ik nwie krI ]','If I am pleasing to Him, then that is my pilgrimage and cleansing bath. Without pleasing Him, what good are ritual cleansings?','If I become pleasing to Him that is my pilgrimage bath. Without pleasing Him of what avail is the ablution?','ਜੇਕਰ ਮੈਂ ਉਸਨੂੰ ਚੰਗਾ ਲੱਗ ਜਾਵਾਂ ਤਾਂ ਇਹੀ ਮੇਰਾ ਧਰਮ ਅਸਥਾਨ ਤੇ ਨ੍ਹਾਉਣਾ ਹੈ। ਉਸਨੂੰ ਚੰਗਾ ਲੱਗਣ ਦੇ ਬਿਨਾ ਇਸ਼ਨਾਨ ਦਾ ਕੀ ਲਾਭ ਹੈ?','Theerathh Naavaa Jae This Bhaavaa Vin Bhaanae K Naae Karee ||','ਮੈਂ ਤੀਰਥ ਉੱਤੇ ਜਾ ਕੇ ਤਦ ਇਸ਼ਨਾਨ ਕਰਾਂ ਜੇ ਇਉਂ ਕਰਨ ਨਾਲ ਉਸ ਪਰਮਾਤਮਾ ਨੂੰ ਖ਼ੁਸ਼ ਕਰ ਸਕਾਂ, ਪਰ ਜੇ ਇਸ ਤਰ੍ਹਾਂ ਪਰਮਾਤਮਾ ਖ਼ੁਸ਼ ਨਹੀਂ ਹੁੰਦਾ, ਤਾਂ ਮੈਂ (ਤੀਰਥ ਉੱਤੇ) ਇਸ਼ਨਾਨ ਕਰਕੇ ਕੀਹ ਖੱਟਾਂਗਾ?','ਹੇ ਸਿਧੋ! ਜੌ ਪ੍ਰਮੇਸ੍ਵਰ ਕੋ ਭਾਵੀਏ ਤੌ ਹੀ ਤੀਰਥ ਨਾਤਾ ਜਾਇ ਅਰੁ ਤੀਰਥ ਨਾਤੇ ਕੀ ਸਫਲਤਾ ਭੀ ਹੋ ਜਾਵੇ। ਜੇਕਰ ਉਸ ਕੇ ਭਾਏ ਬਿਨਾ ਨਾਇ ਭੀ ਲੀਆ ਤੌ ਕਿਆ ਕਰੇਂਗੇ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
50,6,'G',2,11,1,1,'19','29','106,115,097,118,118,107,107,109,108,','106 115 097 118 118 107 107 109 108 ','jyqI isriT aupweI vyKw ivxu krmw ik imlY leI ]','I gaze upon all the created beings: without the karma of good actions, what are they given to receive?','All the created beings, that I behold, without good acts what are they given and what do they obtain?','ਸਮੂਹ ਸਾਜੇ ਹੋਏ ਜੀਵਾਂ ਨੂੰ ਜਿਹੜੇ ਮੈਂ ਤਕਦਾ ਹਾਂ, ਸ਼ੁਭ ਅਮਲਾਂ ਬਾਝੋਂ ਉਨ੍ਹਾਂ ਨੂੰ ਕੀ ਮਿਲਦਾ ਹੈ, ਅਤੇ ਉਹ ਕੀ ਲੈਂਦੇ ਹਨ?','Jaethee Sirath Oupaaee Vaekhaa Vin Karamaa K Milai Lee ||','ਅਕਾਲ ਪੁਰਖ ਦੀ ਪੈਦਾ ਕੀਤੀ ਹੋਈ ਜਿਤਨੀ ਭੀ ਦੁਨੀਆ ਮੈਂ ਵੇਖਦਾ ਹਾਂ, (ਇਸ ਵਿੱਚ) ਪਰਮਾਤਮਾ ਦੀ ਕਿਰਪਾ ਤੋਂ ਬਿਨਾ ਕਿਸੇ ਨੂੰ ਕੁਝ ਨਹੀਂ ਮਿਲਦਾ, ਕੋਈ ਕੁਝ ਨਹੀਂ ਲੈ ਸਕਦਾ।','ਜਿਤਨੀ ਸ੍ਰਿਸਟੀ ਉਤਪਤਿ ਕਰੀ ਹੋਈ ਕੀ ਦੇਖਤਾ ਹੂੰ, ਬਿਨਾ ਕਰਮਾ ਕਿਸੀ ਕੋ ਕ੍ਯਾ ਮਿਲਤਾ ਹੈ ਅਰੁ ਕ੍ਯਾ ਅਪਨੇ ਬਲ ਸੇ ਏਹ ਜੀਵ ਲੈ ਸਕਤਾ ਹੈ। ਭਾਵ ਜੇਕਰ ਹਮਾਰੇ ਕਰਮੋਂ ਮੇਂ ਹੋਗਾ ਅਰੁ ਈਸ੍ਵਰ ਕੋ ਭਾਇਆ, ਤਬ ਆਪ ਹੀ ਤੀਰਥ ਕਰ ਲੈਵੇਂਗੇ। ਤੁਮ ਸੋਂ ਕ੍ਯਾ ਪ੍ਰਯੋਜਨੁ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
51,6,'G',2,12,1,1,'20','29','109,118,114,106,109,106,101,103,107,115,115,','109 118 114 106 109 106 101 103 107 115 115 ','miq ivic rqn jvwhr mwixk jy iek gur kI isK suxI ]','Within the mind are gems, jewels and rubies, if you listen to the Guru''s Teachings, even once.','In the mind are gems, jewels and rubies, provided thou you act upon (hearken to) even one instruction of the Guru.','ਮਨ ਅੰਦਰ ਹੀਰੇ ਜਵਾਹਰ ਤੇ ਲਾਲ ਹਨ, ਜੇਕਰ ਤੂੰ ਗੁਰਾਂ ਦੀ ਇਕ ਭੀ ਸਿਖਿਆ ਸਰਵਣ ਕਰਕੇ ਅਮਲ ਕਰ ਲਵੇਂ।','Math Vich Rathan Javaahar Maanik Jae Eik Gur Kee Sikh Sunee ||','ਜੇ ਸਤਿਗੁਰੂ ਦੀ ਇਕ ਸਿੱਖਿਆ ਸੁਣ ਲਈ ਜਾਏ, ਤਾਂ ਮਨੁੱਖ ਦੀ ਬੁੱਧ ਦੇ ਅੰਦਰ ਰਤਨ, ਜਵਾਹਰ ਤੇ ਮੌਤੀ (ਉਪਜ ਪੈਂਦੇ ਹਨ, ਭਾਵ, ਪਰਮਾਤਮਾ ਦੇ ਗੁਣ ਪੈਦਾ ਹੋ ਜਾਂਦੇ ਹਨ)।','ਹੇ ਸਿਧੋ! (ਜੇ) ਜਬ (ਗੁਰ ਕੀ) ਗੁਰੂਓਂ ਕੀ (ਇਕ) ਏਕਤਾ ਕੀ ਸਿਖ੍ਯਾ ਸੁਣੀਤੀ ਹੈ, ਭਾਵ ਜਬ ਗੁਰੋਂ ਸੇ ਏਕ ਪਰਮਾਤਮਾ ਕਾ ਉਪਦੇਸੁ ਸੁਨੀਏ, ਤਬ ਅਪਨੀ (ਮਤਿ) ਬੁਧੀ ਮੈ ਹੀ ਰਤਨ, ਜਵਾਹਰ, ਮਾਣਿਕ ਮਿਲ ਜਾਤੇ ਹੈਂ⁽¹⁾॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
52,6,'G',2,12,1,1,'1','','103,101,100,098,','103 101 100 098 ','gurw iek dyih buJweI ]','The Guru has given me this one understanding:','The Guru has explained one thing to me.','ਗੁਰੂ ਨੇ ਮੈਨੂੰ ਇਕ ਗਲ ਸਮਝਾ ਦਿਤੀ ਹੈ।','Guraa Eik Dhaehi Bujhaaee ||','(ਤਾਂ ਤੇ) ਹੇ ਸਤਿਗੁਰੂ! (ਮੇਰੀ ਤੇਰੇ ਅੱਗੇ ਇਹ ਅਰਦਾਸ ਹੈ ਕਿ) ਮੈਨੂੰ ਇਕ ਇਹ ਸਮਝ ਦੇਹ,','ਗੁਰੋਂ ਨੇ ਮੁਝ ਕੋ ਏਕ ਬੂਝ ਦਿਤੀ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
53,6,'G',2,13,1,1,'19','27','115,106,107,101,100,115,109,118,110,106,','115 106 107 101 100 115 109 118 110 106 ','sBnw jIAw kw ieku dwqw so mY ivsir n jweI ]6]','There is only the One, the Giver of all souls. May I never forget Him! ||6||','There is but one Bestower for all the beings. May, I never forget Him.','ਸਮੂਹ ਜੀਵਾਂ ਦਾ ਕੇਵਲ ਇਕ ਦਾਤਾਰ ਹੈ। ਉਹ ਮੈਨੂੰ ਕਦੇ ਭੀ ਨਾਂ ਭੁੱਲੇ।','Sabhanaa Jeeaa Kaa Eik Dhaathaa So Mai Visar N Jaaee ||6||','ਜਿਸ ਕਰਕੇ ਮੈਨੂੰ ਉਹ ਅਕਾਲ ਪੁਰਖ ਨਾ ਵਿਸਰ ਜਾਏ, ਜੋ ਸਾਰੇ ਜੀਵਾਂ ਨੂੰ ਦਾਤਾਂ ਦੇਣ ਵਾਲਾ ਹੈ ॥੬॥','ਸਭ ਜੀਵੋਂ ਕਾ ਦਾਤਾ ਏਕੁ ਅਕਾਲ ਪੁਰਖ ਹੈ। ਹੇ ਸਿਧੋ! ਸੋ ਮੁਝ ਕੋ ਵਿਸਰਤਾ ਨਹੀਂ ਹੈ॥ ੬॥☬ਪੁਨਾ ਸਿਧ ਗੁਰੂ ਜੀ ਸੇ ਕਹਤੇ ਭਏ ਕਿ ਜੇ ਕਰ ਆਪ ਹਮਾਰੇ ਮਤ ਮੈ ਆਓ ਅਰਥਾਤ ਜੋਗ ਭੇਸੁ ਲੇ ਲਵੋ, ਤਬ ਜੋਗ ਕੇ ਬਲ ਸੇ ਆਪ ਕੀ ਅਵਸਥਾ ਵੱਡੀ ਹੋ ਜਾਵੇਗੀ। ਸਿਧੋਂ ਕੇ ਪ੍ਰਬੋਧਨੇ ਪਰ ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਉੱਤਰ ਕਹਤੇ ਭਏ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
54,7,'G',2,13,1,1,'13','','106,106,099,065,104,100,104,','106 106 099 065 104 100 104 ','jy jug cwry Awrjw hor dsUxI hoie ]','Even if you could live throughout the four ages, or even ten times more,','Though a man''s age be equal to four ages and grow even ten times more,','ਭਾਵੇਂ ਇਨਸਾਨ ਦੀ ਉਮਰ ਚਾਰ ਜੁਗਾਂ ਦੀ ਹੋਵੇ ਅਤੇ ਦਸ ਗੁਣਾ ਵਧੇਰੇ ਭੀ ਹੋ ਜਾਏ।','Jae Jug Chaarae Aarajaa Hor Dhasoonee Hoe ||','ਜੇ ਕਿਸੇ ਮਨੁੱਖ ਦੀ ਉਮਰ ਚਾਰ ਜੁਗਾਂ ਜਿਤਨੀ ਹੋ ਜਾਏ, (ਨਿਰੀ ਇਤਨੀ ਹੀ ਨਹੀਂ, ਸਗੋਂ ਜੇ) ਇਸ ਤੋਂ ਭੀ ਦਸ ਗੁਣੀ ਹੋਰ (ਉਮਰ) ਹੋ ਜਾਏ,','ਹੇ ਸਿਧੋ! ਜੇ ਕਰ ਚਾਰ ਜੁਗ ਪ੍ਰਯੰਤ ਆਰਬਲਾ ਹੋਵੇ ਅਰ ਦਸ ਗੁਣੀ ਔਰ ਭੀ ਹੋਵੇ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
55,7,'G',2,14,1,1,'15','','110,075,118,106,110,099,115,107,','110 075 118 106 110 099 115 107 ','nvw KMfw ivic jwxIAY nwil clY sBu koie ]','And even if you were known throughout the nine continents and followed by all,','Even though he be known in the nine continents and all were to walk with him (or follow in his train),','ਭਾਵੇਂ ਉਹ ਨਵਾਂ ਹੀ ਮਹਾਦੀਪਾਂ ਅੰਦਰਿ ਪ੍ਰਸਿਧ ਹੋਵੇ ਅਤੇ ਸਾਰੇ ਉਸ ਦੇ (ਮਗਰ ਲੱਗਦੇ ਜਾਂ ਨਾਲ ਟੁਰਦੇ) ਹੋਣ,','Navaa Khanddaa Vich Jaaneeai Naal Chalai Sabh Koe ||','ਜੇ ਉਹ ਸਾਰੇ ਸੰਸਾਰ ਵਿਚ ਭੀ ਪਰਗਟ ਹੋ ਜਾਏ ਅਤੇ ਹਰੇਕ ਮਨੁੱਖ ਉਸ ਦੇ ਪਿੱਛੇ ਲੱਗ ਕੇ ਤੁਰੇ।','ਨਵਾਂ ਖੰਡਾਂ⁽¹⁾ ਵਿਚ ਪੁਰਸ਼ ਜਾਣਿਆਂ ਭੀ ਜਾਵੇ ਅਰਥਾਤ ਪ੍ਰਸਿੱਧ ਹੋ ਜਾਵੇ। ਔਰ ਸਭ ਕੋਈ ਸਾਥ ਚਲੈ, ਭਾਵ ਸਾਰੀ ਸ੍ਰਿਸ਼ਟੀ ਹੁਕਮ ਮੇ ਚਲੇ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
56,7,'G',2,14,1,1,'17','','099,110,114,107,106,107,106,108,','099 110 114 107 106 107 106 108 ','cMgw nwau rKwie kY jsu kIriq jig lyie ]','With a good name and reputation, with praise and fame throughout the world-','and he were to assume good name and obtain praise and renown in the world.','ਤੇ ਭਾਵੇਂ ਉਹ ਸਰੇਸ਼ਟ ਨਾਮ ਰਖਵਾ ਲਵੇ ਅਤੇ ਸੰਸਾਰ ਅੰਦਰ ਉਪਮਾ ਤੇ ਸ਼ੋਭਾ ਪਰਾਪਤ ਕਰ ਲਵੇ।','Changaa Naao Rakhaae Kai Jas Keerath Jag Laee ||','ਜੇ ਉਹ ਚੰਗੀ ਨਾਮਵਰੀ ਖੱਟ ਕੇ ਸਾਰੇ ਸੰਸਾਰ ਵਿਚ ਸ਼ੋਭਾ ਭੀ ਪ੍ਰਾਪਤ ਕਰ ਲਏ,','ਨਾਮੁ ਭੀ ਜਗਤ ਮੈ ਅਛਾ ਰਖਾਵੇ, ਜਸੁ ਦੇਸ ਮੈ, ਕੀਰਤਿ ਦੇਸਾਂਤਰ ਮੈ ਵਾ ਜਸੁ ਮੁਖ ਪਰ, ਕੀਰਤੀ ਪਿਠ ਪਿਛੇ ਸਭ ਕੋਈ ਕਰੇ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
57,7,'G',2,15,1,1,'16','','106,113,110,110,065,113,118,110,112,107,','106 113 110 110 065 113 118 110 112 107 ','jy iqsu ndir n AwveI q vwq n puCY ky ]','Still, if the Lord does not bless you with His Glance of Grace, then who cares? What is the use?','If God''s gracious glance falls not one him, them, no one would care for him,','ਜੇਕਰ ਉਹ ਉਸ ਦੀ ਦਯਾ ਦ੍ਰਿਸ਼ਟੀ ਦਾ ਪਾਤਰ ਨਹੀਂ, ਤਦ, ਉਸ ਦੀ ਕੋਈ ਪਰਵਾਹ ਨਹੀਂ ਕਰੇਗਾ,','Jae This Nadhar N Aavee Th Vaath N Pushhai Kae ||','(ਪਰ) ਜੇਕਰ ਅਕਾਲ ਪੁਰਖ ਦੀ ਮਿਹਰ ਦੀ ਨਜ਼ਰ ਵਿਚ ਨਹੀਂ ਆ ਸਕਦਾ, ਤਾਂ ਉਹ ਉਸ ਬੰਦੇ ਵਰਗਾ ਹੈ ਜਿਸ ਦੀ ਕੋਈ ਖ਼ਬਰ ਭੀ ਨਹੀਂ ਪੁੱਛਦਾ (ਭਾਵ, ਇਤਨੀ ਮਾਣ ਵਡਿਆਈ ਵਾਲਾ ਹੁੰਦਿਆਂ ਭੀ ਅਸਲ ਵਿਚ ਨਿਆਸਰਾ ਹੀ ਹੈ)।','ਹੇ ਸਿਧੋ! ਜੇਕਰ ਹਰੀ ਕੀ ਕ੍ਰਿਪਾ (ਨਦਰਿ) ਦ੍ਰਿਸ਼ਟੀ ਮੇ ਪੁਰਸ਼ੁ ਨਹੀਂ ਆਵੇ ਤਬ ਤਿਸ ਕੀ ਕੋਈ ਸੰਸਾਰ ਮੇ ਬਾਤ ਨਹੀਂ ਪੂਛਤਾ। ਵਾ (ਕੇ) ਕੋਈ ਮਹਾਤਮਾ ਜਨ ਜੋ ਪਰਮੇਸ੍ਵਰ ਕੇ ਪ੍ਯਾਰੇ ਹੈਂ, ਸੋ ਬਾਤ ਨਹੀਂ ਪੂਛਤੇ, ਭਾਵ ਤਿਸ ਕੋ ਤੁਛ ਜਾਨਤੇ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
58,7,'G',2,15,1,1,'17','','107,065,107,107,100,100,068,','107 065 107 107 100 100 068 ','kItw AMdir kItu kir dosI dosu Dry ]','Among worms, you would be considered a lowly worm, and even contemptible sinners would hold you in contempt.','he is accounted a vermin amongst worms and even the sinners impute accusations to him.','ਉਹ ਕੀੜਿਆਂ ਵਿੱਚ ਨੀਚ ਮਕੌੜਾ ਗਿਣਿਆ ਜਾਂਦਾ ਹੈ ਅਤੇ ਪਾਂਬਰ ਭੀ ਉਸ ਉਤੇ ਦੁਸ਼ਨ ਲਾਉਂਦੇ ਹਨ।','Keettaa Andhar Keett Kar Dhosee Dhos Dhharae ||','(ਸਗੋਂ ਅਜਿਹਾ ਮਨੁੱਖ ਅਕਾਲ ਪੁਰਖ ਦੇ ਸਾਹਮਣੇ) ਇਕ ਮਮੂਲੀ ਜਿਹਾ ਕੀੜਾ ਹੈ ("ਖਸਮੈ ਨਦਰੀ ਕੀੜਾ ਆਵੈ" ਆਸਾ ਮ: ੧) ਅਕਾਲ ਪੁਰਖ ਉਸ ਨੂੰ ਦੋਸੀ ਥਾਪ ਕੇ (ਉਸ ਉੱਤੇ ਨਾਮ ਨੂੰ ਭੁੱਲਣ ਦਾ) ਦੋਸ਼ ਲਾਉਂਦਾ ਹੈ।','ਕੀਟ ਜੋ ਹੈਂ ਤਿਨ ਕੇ ਅੰਦਰਿ ਵਹੁ ਭੀ ਇਕੁ ਕੀਟ ਹੋਤਾ ਹੈ, ਜਿਸ ਕੋ (ਦੋਸੀ) ਕੁਸਟੀ ਵਾ ਪਾਪੀ ਭੀ ਦੋਸੁ ਰਖਤੇ ਹੈਂ, ਵਾ ਉਸ ਕੇ ਦੋਸੀ ਹੋਣੇ ਤੇ ਪ੍ਰਲੋਕ ਮੈ ਉਸ ਪਰ ਦੋਸ ਧਰੇ ਜਾਤੇ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
59,7,'G',2,15,1,1,'19','1','110,110,103,107,103,103,100,','110 110 103 107 103 103 100 ','nwnk inrguix guxu kry guxvMiqAw guxu dy ]','O Nanak, God blesses the unworthy with virtue, and bestows virtue on the virtuous.','O Nanak! God grants virtue to the non-virtuous and bestows piety on the pious.','ਹੇ ਨਾਨਕ! ਵਾਹਿਗੁਰੂ ਨੇਕੀ-ਬਿਹੁਨਾ ਨੂੰ ਨੇਕੀ ਬਖਸ਼ਦਾ ਹੈ ਅਤੇ ਪਵਿੱਤਰ ਆਤਮਾਵਾਂ ਨੂੰ ਪਵਿਤ੍ਰਤਾਈ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।','Naanak Niragun Gun Karae Gunavanthiaa Gun Dhae ||','ਹੇ ਨਾਨਕ! ਉਹ ਅਕਾਲ ਪੁਰਖ ਗੁਣ-ਹੀਨ ਮਨੁੱਖ ਵਿੱਚ ਗੁਣ ਪੈਦਾ ਕਰ ਦੇਂਦਾ ਹੈ ਤੇ ਗੁਣੀ ਮਨੁੱਖਾਂ ਨੂੰ ਭੀ ਗੁਣ ਉਹੀ ਬਖ਼ਸ਼ਦਾ ਹੈ।','ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹੇ ਸਿਧੋ! ਪਰਮੇਸ੍ਵਰੁ ਨਿਰਗੁਣੋ ਕੋ ਭੀ ਗੁਣੁ ਦੇਤਾ ਹੈ, ਅਰ ਗੁਣਵਾਨੋ ਕੋ ਅਧਿਕ ਗੁਣੁ ਪ੍ਰਾਪਤਿ ਕਰ ਦੇਤਾ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
60,7,'G',2,16,1,1,'13','','113,107,110,115,106,113,103,107,107,','113 107 110 115 106 113 103 107 107 ','qyhw koie n suJeI ij iqsu guxu koie kry ]7]','No one can even imagine anyone who can bestow virtue upon Him. ||7||','I can think of no such one who can show any goodness unto Him.','ਮੈਂ ਕਿਸੇ ਇਹੋ ਜੇਹੇ ਦਾ ਖਿਆਲ ਨਹੀਂ ਕਰ ਸਕਦਾ ਜਿਹੜਾ ਉਸ ਉਤੇ ਕੋਈ ਮਿਹਰਬਾਨੀ ਕਰ ਸਕਦਾ ਹੋਵੇ।','Thaehaa Koe N Sujhee J This Gun Koe Karae ||7||','ਇਹੋ ਜਿਹਾ ਕੋਈ ਹੋਰ ਨਹੀਂ ਦਿੱਸਦਾ, ਜੋ ਨਿਰਗੁਣ ਜੀਵ ਨੂੰ ਕੋਈ ਗੁਣ ਦੇ ਸਕਦਾ ਹੋਵੇ। (ਭਾਵ ਪ੍ਰਭੂ ਦੀ ਮਿਹਰ ਦੀ ਨਜ਼ਰ ਹੀ ਉਸ ਨੂੰ ਉੱਚਾ ਕਰ ਸਕਦੀ ਹੈ, ਲੰਮੀ ਉਮਰ ਤੇ ਜਗਤ ਦੀ ਸ਼ੋਭਾ ਸਹਾਇਤਾ ਨਹੀਂ ਕਰਦੀ) ॥੭॥','ਤੈਸਾ ਕੋਈ ਦਿਖਾਈ ਨਹੀਂ ਦੇਤਾ, ਜੋ ਤਿਸ ਪ੍ਰਮੇਸ੍ਵਰ ਕੋ ਗੁਣ ਦੇਵੈ, ਭਾਵ ਉਪਕਾਰੋ ਕਾ ਪ੍ਰਤੀ ਬਦਲਾ ਦੇਵੇ॥੭॥☬ਅਬ ਚਾਰ ਪੌੜੀਆਂ ਮੈਂ ਗੁਰੂ ਜੀ ਨਾਮ ਦੇ ਸੁਣਨੇ ਦਾ ਮਹਾਤਮੁ ਕਥਨ ਕਰਤੇ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
61,8,'G',2,16,1,1,'1','','115,115,112,115,110,','115 115 112 115 110 ','suixAY isD pIr suir nwQ ]','Listening-the Siddhas, the spiritual teachers, the heroic warriors, the yogic masters.','By hearing God''s Name the mortal becomes a perfect person, religious guide, spiritual hero and a great yogi.','ਵਾਹਿਗੁਰੂ ਦੇ ਨਾਮ ਨੂੰ ਸਰਵਣ ਕਰਨ ਦੁਆਰਾ ਪ੍ਰਾਨੀ ਪੂਰਨ ਪੁਰਸ਼ ਧਾਰਮਕ ਆਗੂ, ਰੂਹਾਨੀ ਯੋਧਾ ਅਤੇ ਵੱਡਾ ਯੋਗੀ ਹੋ ਜਾਂਦਾ ਹੈ।','Suniai Sidhh Peer Sur Naathh ||','ਇਹ ਨਾਮ ਹਿਰਦੇ ਵਿਚ ਟਿਕਣ ਦੀ ਹੀ ਬਰਕਤਿ ਹੈ ਕਿ ਵਾਹਿਗੁਰੂ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਸੁਣਨ ਨਾਲ (ਸਾਧਾਰਨ ਮਨੁੱਖ) ਸਿੱਧਾਂ, ਪੀਰਾਂ, ਦੇਵਤਿਆਂ ਤੇ ਨਾਥਾਂ ਦੀ ਪਦਵੀ ਪਾ ਲੈਂਦੇ ਹਨ','ਗੋਰਖ ਆਦੀ ਸਿਖ ਔਰ ਮੁਸਲਮਾਨ ਮਤ ਕੇ ਪੀਰ ਔਰ ਦੇਵਤਾ, ਪੁਨਾ ੯ ਨਾਥ ਵਾ (ਸੁਰਿਨਾਥ) ਇੰਦ੍ਰ, ਇਨ ਸਭ ਕੋ ਪਦਵੀ ਗੁਰ ਉਪਦੇਸੁ ਸਰਵਣ ਸੇ ਹੀ ਪਰਾਪਤਿ ਭਈ ਹੈ॥ ਆਗੇ ਪਦਵੀ ਦੋ ਪ੍ਰਕਾਰ ਕੀ ਹੈ: ਸਕਾਮੀਆਂ ਕੋ ਸਿੱਧੀ ਸ੍ਵਰਗਾਦਿਕ ਪਦਵੀ, ਨਿਸਕਾਮੀਆਂ ਕੋ ਸ੍ਵੈ ਸਰੂਪ ਕੀ ਪ੍ਰਾਪਤੀ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
62,8,'G',2,17,1,1,'1','','115,068,068,065,','115 068 068 065 ','suixAY Driq Dvl Awkws ]','Listening-the earth, its support and the Akaashic ethers.','By hearing God''s Name the reality of the earth, it''s supposed supporting bull and the heaven is revealed unto the mortal.','ਵਾਹਿਗੁਰੂ ਦੇ ਨਾਮ ਨੂੰ ਸਰਵਣ ਕਰਨ ਦੁਆਰਾ ਪ੍ਰਾਨੀ ਨੂੰ ਧਰਤੀ, ਇਸ ਦੇ ਚੁੱਕਣ ਵਾਲੇ ਕਲਪਤ ਬਲਦ ਅਤੇ ਅਸਮਾਨ ਦੀ ਅਸਲੀਅਤ ਦਾ ਪਤਾ ਲੱਗ ਜਾਂਦਾ ਹੈ।','Suniai Dhharath Dhhaval Aakaas ||','ਤੇ ਵਾਹਿਗੁਰੂ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਸੁਣਨ ਨਾਲ ਉਹਨਾਂ ਨੂੰ ਇਹ ਸੋਝੀ ਹੋ ਜਾਂਦੀ ਹੈ ਕਿ ਧਰਤੀ ਆਕਾਸ਼ ਦਾ ਆਸਰਾ ਉਹ ਪ੍ਰਭੂ ਹੈ,','(ਧਰਤੀ) ਪ੍ਰਿਥਵੀ ਔਰੁ (ਧਵਲ) ਧਰਮ ਰੂਪੁ ਔਰੁ ਅਕਾਸੁ ਏਹ ਸਭ ਨਾਮ ਕੋ ਸੁਣ ਕੇ ਹੂਏ ਹੈਂ। ਭਾਵ ਇਨ ਕੇ ਅਭਿਮਾਨੀ ਦੇਵਤਾ ਨਾਮ ਕੋ ਸੁਣ ਕੇ ਅਧਿਕ ਪ੍ਰਭਤਾ ਕੋ ਪ੍ਰਾਪਤਿ ਹੂਏ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
63,8,'G',2,17,1,1,'1','','115,100,108,112,','115 100 108 112 ','suixAY dIp loA pwqwl ]','Listening-the oceans, the lands of the world and the nether regions of the underworld.','By hearkening to the Lord''s Name man comes to have the knowledge of the continents, the worlds and the nether regions.','ਸਾਈਂ ਦੇ ਨਾਮ ਨੂੰ ਸਰਵਣ ਕਰਣ ਦੁਆਰਾ ਆਦਮੀ ਨੂੰ ਮਹਾ-ਦੀਪਾਂ, ਪੁਰੀਆਂ ਅਤੇ ਹੇਠਲਿਆਂ ਲੋਆਂ ਦੀ ਗਿਆਤ ਹੋ ਜਾਂਦੀ ਹੈ।','Suniai Dheep Loa Paathaal ||','ਵਾਹਿਗੁਰੂ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਸੁਣਨ ਨਾਲ ਸੋਝੀ ਪੈਂਦੀ ਹੈ ਕਿ ਵਾਹਿਗੁਰੂ ਜੋ ਸਾਰੇ ਦੀਪਾਂ, ਲੋਕਾਂ, ਪਾਤਾਲਾਂ ਵਿਚ ਵਿਆਪਕ ਹੈ','ਸਾਤ ਹੀ ਦੀਪ ਅਰ ਸਾਤ ਹੀ (ਲੋਅ) ਲੋਕ ਅਰ ਸਾਤ ਹੀ ਪਾਤਾਲੋਂ ਕੇ ਅਭਿਮਾਨੀ ਦੇਵਤਾ ਨਾਮ ਕੌ ਸ੍ਰਵਣ ਕਰ ਕੇ ਅਧਿਕਤਾ ਕੋ ਪ੍ਰਾਪਤਿ ਹੂਏ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
64,8,'G',2,17,1,1,'1','','115,112,110,115,107,','115 112 110 115 107 ','suixAY poih n skY kwlu ]','Listening-Death cannot even touch you.','By hearing the Lord''s Name death cannot torment (touch) the mortal.','ਰੱਬ ਦੇ ਨਾਮ ਨੂੰ ਸਰਵਣ ਕਰਨ ਦੁਆਰਾ ਮੌਤ ਪ੍ਰਾਨੀ ਲਾਗੇ ਨਹੀਂ ਲੱਗ ਲਗਦੀ (ਅਜ਼ਾਬ ਨਹੀਂ ਦੇ ਸਕਦੀ)।','Suniai Pohi N Sakai Kaal ||','(ਵਾਹਿਗੁਰੂ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਸੁਣਨ ਵਾਲੇ ਮਨੁੱਖ ਕਾਲ ਵੀ ਨਹੀਂ ਪੋਂਹਦਾ ਭਾਵ ਉਨ੍ਹਾਂ ਨੂੰ ਮੌਤ ਨਹੀਂ ਡਰਾ ਸਕਦੀ)','ਸੁਣਨੇ ਕਰ ਕੇ ਕਾਲੁ (ਪੋਹਿ) ਸਪਰਸ ਨਹੀਂ ਕਰ ਸਕਤਾ, ਭਾਵ ਮਾਰਕੰਡੇ ਆਦਿਕ ਚਿਰੰਜੀਵੀ ਪਦ ਕੋ ਨਾਮੁ ਸੁਣ ਕੇ ਹੀ ਪ੍ਰਾਪਤਿ ਹੂਏ ਹੈਂ॥⁽¹⁾');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
65,8,'G',2,18,1,1,'1','','110,066,115,118,','110 066 115 118 ','nwnk Bgqw sdw ivgwsu ]','O Nanak, the devotees are forever in bliss.','O Nanak! the devotees ever enjoy happiness.','ਹੇ ਨਾਨਕ! ਅਨੁਰਾਗੀ ਹਮੇਸ਼ਾਂ ਅਨੰਦ ਮਾਣਦੇ ਹਨ।','Naanak Bhagathaa Sadhaa Vigaas ||','ਹੇ ਨਾਨਕ! (ਅਕਾਲ ਪੁਰਖ ਦੇ ਨਾਮ ਵਿਚ ਸੁਰਤ ਜੋੜਨ ਵਾਲੇ) ਭਗਤ ਜਨਾਂ ਦੇ ਹਿਰਦੇ ਵਿਚ ਸਦਾ ਖਿੜਾਉ ਬਣਿਆ ਰਹਿੰਦਾ ਹੈ,','ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹੇ ਸਿਧੋ! ਜਿਸ ਨਾਮ ਸ੍ਰਵਣ ਕਾ ਐਸਾ ਮਹਾਤਮੁ ਹੈ, ਜਿਸ ਸੇ ਸਦਾ (ਵਿਗਾਸੁ) ਅਨੰਦੁ ਅਰਥਾਤ ਨਿਤ੍ਯਾਨੰਦੁ ਪ੍ਰਾਪਤਿ ਹੂਆ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
66,8,'G',2,18,1,1,'1','','115,100,112,107,110,','115 100 112 107 110 ','suixAY dUK pwp kw nwsu ]8]','Listening-pain and sin are erased. ||8||','By hearing to the Master''s Name sorrow and sin meet with destruction.','ਮਾਲਕ ਦੇ ਨਾਮ ਨੂੰ ਸਰਵਣ ਕਰਣ ਦੁਆਰਾ ਕਸ਼ਟ ਤੇ ਕਸਮਲ ਤਬਾਹ ਥੀ ਵੰਞਦੇ (ਤਬਾਹ ਹੋ ਜਾਂਦੇ) ਹਨ।','Suniai Dhookh Paap Kaa Naas ||8||','(ਕਿੳਂਕਿ) ਉਸ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਸੁਣਨ ਕਰ ਕੇ (ਮਨੁੱਖ ਦੇ) ਦੁੱਖਾਂ ਤੇ ਪਾਪਾਂ ਦਾ ਨਾਸ ਹੋ ਜਾਂਦਾ ਹੈ ॥੮॥','ਜਿਸ ਨਾਮ ਸ੍ਰਵਣ ਕਾ ਐਸਾ ਮਹਾਤਮੁ ਹੈ, ਤਿਸ ਨਾਮ ਕੋ ਜਿਨ ਭਗਤੋਂ ਨੇ ਪ੍ਰੇਮ ਸੇ ਸ਼੍ਰਵਣ ਕੀਆ ਹੈ, ਤਿਨ ਕੇ ਸਭ ਪ੍ਰਕਾਰ ਕੇ ਦੁਖ ਔਰੁ ਪਾਪੋਂ ਕਾ ਨਾਸੁ ਹੋ ਕਰ ਸਦਾ (ਵਿਗਾਸੁ) ਅਨੰਦੁ ਅਰਥਾਤ ਨਿਤ੍ਯਾਨੰਦੁ ਪ੍ਰਾਪਤਿ ਹੂਆ ਹੈ⁽¹⁾॥੮॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
67,9,'G',2,18,1,1,'1','','115,101,098,101,','115 101 098 101 ','suixAY eIsru brmw ieMdu ]','Listening-Shiva, Brahma and Indra.','By hearing the Lord''s Name the status of god of death, god of creation and god of rain is obtained.','ਸਾਹਿਬ ਦੇ ਨਾਮ ਨੂੰ ਸੁਣਨ ਦੁਆਰਾ ਮੌਤ ਦੇ ਦੇਵਤੇ, ਉਤਪੁਤੀ ਦੇ ਦੇਵਤੇ ਅਤੇ ਮੀਂਹ ਦੇ ਦੇਵਤੇ ਦੀ ਪਦਵੀ ਪਰਾਪਤ ਹੋ ਜਾਂਦੀ ਹੈ।','Suniai Eesar Baramaa Eindh ||','ਅਕਾਲ ਪੁਰਖ ਦੇ ਨਾਮ ਵਿਚ ਸੁਰਤ ਜੋੜਨ ਦਾ ਸਦਕਾ ਸਾਧਾਰਨ ਮਨੁੱਖ ਸ਼ਿਵ, ਬ੍ਰਹਮਾ ਤੇ ਇੰਦਰ ਦੀ ਪਦਵੀ ''ਤੇ ਅੱਪੜ ਜਾਂਦਾ ਹੈ,','(ਈਸਰੁ) ਸਿਵ, (ਬਰਮਾ) ਬ੍ਰਹਮਾ, (ਇੰਦੁ) ਇੰਦ੍ਰ ਵਾ ਚੰਦ੍ਰ ਇਤਿਆਦਿਕੋਂ ਕੋ ਪਦਵੀ ਨਾਮ ਕੇ ਸ੍ਰਵਣ ਸੇ ਹੀ ਪ੍ਰਾਪਤਿ ਭਈ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
68,9,'G',2,19,1,1,'1','','115,109,115,109,','115 109 115 109 ','suixAY muiK swlwhx mMdu ]','Listening-even foul-mouthed people praise Him.','By hearing God''s Name even the evil come to sing Lord''s praises with their mouth.','ਰਬ ਦਾ ਨਾਮ ਸੁਣਨ ਦੁਆਰਾ ਬਦਕਾਰ ਭੀ ਆਪਣੇ ਮੂੰਹ ਨਾਲ ਸਾਈਂ ਦੀ ਸਿਫ਼ਤ ਗਾਇਨ ਕਰਨ ਲੱਗ ਜਾਂਦੇ ਹਨ।','Suniai Mukh Saalaahan Mandh ||','ਮੰਦਾ ਮਨੁੱਖ ਭੀ ਮੂੰਹੋਂ ਰੱਬ ਦੀਆਂ ਸਿਫ਼ਤਾਂ ਕਰਨ ਲੱਗ ਪੈਂਦਾ ਹੈ,','ਜੋ ਮੰਦ ਜਾਤੀ ਮੰਦ ਕਰਮੀ ਬਾਲਮੀਕਾਦਿ ਵਾਟਮਾਰ ਥੇ, ਸੋ ਮੁੱਖ (ਸਾਲਾਹਣ) ਉਸਤਿਤੀ ਕੇ ਜੋਗਯ ਆਦਿਕਵਿ ਐਸੀ ਪਦਵੀ ਕੋ ਸ੍ਰਵਣ ਸੇ ਹੀ ਪ੍ਰਾਪਤਿ ਭਏ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
69,9,'G',2,19,1,1,'1','','115,106,106,113,066,','115 106 106 113 066 ','suixAY jog jugiq qin Byd ]','Listening-the technology of Yoga and the secrets of the body.','By hearing God''s Name the mortal understands the ways of uniting with the Lord and the body''s secrets.','ਹਰੀ ਦਾ ਨਾਮ ਸੁਣਨ ਦੁਆਰਾ ਜੀਵ ਸਾਹਿਬ ਨਾਲ ਜੁੜਨ ਦੇ ਰਸਤੇ ਅਤੇ ਸਰੀਰ ਦੇ ਭੇਤਾਂ ਨੂੰ ਜਾਣ ਲੈਂਦਾ ਹੈ।','Suniai Jog Jugath Than Bhaedh ||','(ਸਾਧਾਰਨ ਬੁੱਧ ਵਾਲੇ ਨੂੰ ਭੀ) ਸਰੀਰ ਵਿਚ ਦੀਆਂ ਗੁੱਝੀਆਂ ਗੱਲਾਂ, (ਭਾਵ, ਅੱਖਾਂ, ਕੰਨ, ਜੀਭ ਆਦਿਕ ਇੰਦਰੀਆਂ ਦੇ ਚਾਲਿਆਂ ਤੇ ਵਿਕਾਰ ਆਦਿਕਾਂ ਵੱਲ ਦੌੜ-ਭੱਜ) ਦੇ ਭੇਦ ਦਾ ਪਤਾ ਲੱਗ ਜਾਂਦਾ ਹੈ,','ਅਸਟਾਂਗ ਜੋਗ ਕੀ ਜੁਗਤਿ ਸੇ ਸਰੀਰ ਮੇਂ ਜੋ ਖਟ ਚੱਕ੍ਰ ਹੈਂ, ਤਿਨ ਕਾ ਜਾਨ ਲੇਨਾ, ਯੇਹੁ ਤਨ ਕਾ ਭੇਦੁ, ਸਭੁ ਸ੍ਰਵਣ ਸੇ ਹੀ ਹੁਆ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
70,9,'G',2,19,1,1,'1','','115,115,115,118,','115 115 115 118 ','suixAY swsq isimRiq vyd ]','Listening-the Shaastras, the Simritees and the Vedas.','By hearing the Lord''s Name the Knowledge of the four religious books, six school of philosophy and twenty seven ceremonial treatise is acquired.','ਮਾਲਕ ਦੇ ਨਾਮ ਨੂੰ ਸੁਣਨ ਦੁਆਰਾ ਚੌਹਾਂ ਹੀ ਧਾਰਮਿਕ ਗ੍ਰੰਥਾਂ, ਛੇ ਫਲਸਫੇ ਦਿਆਂ ਗ੍ਰੰਥਾਂ ਅਤੇ ਸਤਾਈ ਕਰਮਕਾਂਡੀ ਪੁਸਤਕਾਂ ਦੀ ਗਿਆਤ ਪਰਾਪਤ ਹੋ ਜਾਂਦੀ ਹੈ।','Suniai Saasath Simrith Vaedh ||','ਪ੍ਰਭੂ-ਮੇਲ ਦੀ ਜੁਗਤੀ ਦੀ ਸਮਝ ਪੈ ਜਾਂਦੀ ਹੈ, ਸ਼ਾਸਤ੍ਰਾਂ ਸਿਮ੍ਰਿਤੀਆਂ ਤੇ ਵੇਦਾਂ ਦੀ ਸਮਝ ਪੈ ਜਾਂਦੀ ਹੈ (ਭਾਵ, ਧਾਰਮਿਕ ਪੁਸਤਕਾਂ ਦਾ ਅਸਲ ਉੱਚਾ ਨਿਸ਼ਾਨਾ ਤਦੋਂ ਸਮਝ ਪੈਂਦਾ ਹੈ ਜਦੋਂ ਅਸੀਂ ਨਾਮ ਵਿਚ ਸੁਰਤ ਜੋੜਦੇ ਹਾਂ, ਨਹੀਂ ਤਾਂ ਨਿਰੇ ਲਫ਼ਜ਼ਾਂ ਨੂੰ ਹੀ ਪੜ੍ਹ ਛਡਦੇ ਹਾਂ, ਉਸ ਅਸਲੀ ਜਜ਼ਬੇ ਵਿਚ ਨਹੀਂ ਪਹੁੰਚਦੇ, ਜਿਸ','੬ ਸਾਸਤ੍ਰ, ੨੭ ਸਿੰਮਿਤ੍ਰੀ, ੪ ਵੇਦ, ਇਨ ਸਭਨੋ ਕਾ ਸਿਧਾਂਤੁ ਸ੍ਰਵਣ ਸੇ ਹੀ ਪ੍ਰਪਤਿ ਹੂਆ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
71,9,'G',3,19,1,1,'1','','110,066,115,118,','110 066 115 118 ','nwnk Bgqw sdw ivgwsu ]','O Nanak, the devotees are forever in bliss.','Ever blissful are the saints, O Nanak!','ਸਦੀਵ ਸੁਪ੍ਰਸੰਨ ਹਨ ਸਾਧੂ, ਹੇ ਨਾਨਕ!','Naanak Bhagathaa Sadhaa Vigaas ||','ਹੇ ਨਾਨਕ! (ਨਾਮ ਨਾਲ ਪ੍ਰੀਤ ਕਰਨ ਵਾਲੇ) ਭਗਤ ਜਨਾਂ ਦੇ ਹਿਰਦੇ ਵਿਚ ਸਦਾ ਖਿੜਾਉ ਬਣਿਆ ਰਹਿੰਦਾ ਹੈ;','ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹੇ ਸਿਧੋ! ਜਿਸ ਨਾਮ ਸ੍ਰਵਣ ਕਾ ਐਸਾ ਮਹਾਤਮੁ ਹੈ, ਜਿਸ ਸੇ ਸਦਾ (ਵਿਗਾਸੁ) ਅਨੰਦੁ ਅਰਥਾਤ ਨਿਤ੍ਯਾਨੰਦੁ ਪ੍ਰਾਪਤਿ ਹੂਆ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
72,9,'G',3,1,1,1,'1','','115,100,112,107,110,','115 100 112 107 110 ','suixAY dUK pwp kw nwsu ]9]','Listening-pain and sin are erased. ||9||','By hearing the Lord''s Name disease and wickedness are wiped off.','ਸੁਆਮੀ ਦੇ ਨਾਮ ਨੂੰ ਸਰਵਣ ਕਰਣ ਦੁਆਰਾ ਬੀਮਾਰੀ ਤੇ ਗੁਨਾਹ ਦੂਰ ਹੋ ਜਾਂਦੇ ਹਨ।','Suniai Dhookh Paap Kaa Naas ||9||','(ਕਿਉਂਕਿ) ਰੱਬ ਦੀ ਸਿਫ਼ਤਿ ਸਾਲਾਹ ਸੁਣਨ ਕਰਕੇ (ਮਨੁੱਖ ਦੇ) ਦੁਖਾਂ ਤੇ ਪਾਪਾਂ ਦਾ ਨਾਸ਼ ਹੋ ਜਾਂਦਾ ਹੈ ॥੯॥','ਜਿਸ ਨਾਮ ਸ੍ਰਵਣ ਕਾ ਐਸਾ ਮਹਾਤਮੁ ਹੈ, ਤਿਸ ਨਾਮ ਕੋ ਜਿਨ ਭਗਤੋਂ ਨੇ ਪ੍ਰੇਮ ਸੇ ਸ਼੍ਰਵਣ ਕੀਆ ਹੈ, ਤਿਨ ਕੇ ਸਭ ਪ੍ਰਕਾਰ ਕੇ ਦੁਖ ਔਰੁ ਪਾਪੋਂ ਕਾ ਨਾਸੁ ਹੋ ਕਰ ਸਦਾ (ਵਿਗਾਸੁ) ਅਨੰਦੁ ਅਰਥਾਤ ਨਿਤ੍ਯਾਨੰਦੁ ਪ੍ਰਾਪਤਿ ਹੂਆ ਹੈ॥੯॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
73,10,'G',3,1,1,1,'1','','115,115,115,103,','115 115 115 103 ','suixAY squ sMqoKu igAwnu ]','Listening-truth, contentment and spiritual wisdom.','By hearkening to the Lord''s Name truthfulness, contentment and Divine Knowledge are obtained.','ਸਾਹਿਬ ਦੇ ਨਾਮ ਨੂੰ ਸਰਵਣ ਕਰਣ ਦੁਆਰਾ ਸਚਾਈ ਸਬੂਰੀ ਅਤੇ ਬ੍ਰਹਮ ਵੀਚਾਰ ਪਰਾਪਤ ਹੋ ਜਾਂਦੇ ਹਨ।','Suniai Sath Santhokh Giaan ||','ਰੱਬ ਦੇ ਨਾਮ ਵਿਚ ਜੁੜਨ ਨਾਲ (ਹਿਰਦੇ ਵਿਚ) ਦਾਨ (ਦੇਣ ਦਾ ਸੁਭਾਉ), ਸੰਤੋਖ ਤੇ ਪ੍ਰਕਾਸ਼ ਪਰਗਟ ਹੋ ਜਾਂਦਾ ਹੈ,','ਸ੍ਰਵਣ ਸੇ ਹੀ ਸਤੁ, ਸੰਤੋਖੁ, ਗ੍ਯਾਨੁ ਪ੍ਰਾਪਤਿ ਹੋਤਾ ਹੈ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
74,10,'G',3,1,1,1,'1','','115,065,107,101,','115 065 107 101 ','suixAY ATsiT kw iesnwnu ]','Listening-take your cleansing bath at the sixty-eight places of pilgrimage.','By hearing the Lord''s Name the fruit of the ablution at sixty-eight holies is attained.','ਪ੍ਰਭੂ ਦੇ ਨਾਮ ਨੂੰ ਸਰਵਣ ਕਰਨ ਦੁਆਰਾ ਅਠਾਹਠ ਤੀਰਥਾਂ ਉਤੇ ਨ੍ਹਾਉਣ ਦਾ ਫਲ ਪਰਾਪਤ ਹੋ ਜਾਂਦਾ ਹੈ।','Suniai Athasath Kaa Eisanaan ||','ਮਾਨੋ, ਅਠਾਹਠ ਤੀਰਥਾਂ ਦਾ ਇਸ਼ਨਾਨ (ਹੀ) ਹੋ ਜਾਂਦਾ ਹੈ (ਭਾਵ, ਅਠਾਰਠ ਤੀਰਥਾਂ ਦੇ ਇਸ਼ਨਾਨ ਨਾਮ ਜਪਣ ਦੇ ਵਿਚ ਹੀ ਆ ਜਾਂਦੇ ਹਨ)।','ਅਠਸਠ ਤੀਰਥੋਂ ਕੇ ਸਨਾਨ ਕਾ ਫਲੁ ਵਾ ਅਠਾਸਠ ਤੀਰਥੋਂ ਮੇਂ ਪਵਿਤ੍ਰਤਾ ਸ਼ਕਤੀ ਨਾਮ ਸ੍ਰਵਣ ਸੇ ਹੀ ਹੂਈ ਹੈ। ਸੋ ਅਠਸਠ ਤੀਰਥ ਐਸੇ ਜਾਨਨੇ, ਜੈਸੇ ਕੁਰਖ੍ਯੇਤ੍ਰ ਮੇਂ ਬਹੁਤ ਤੀਰਥ ਹੈਂ ਪਰੰਤੂ ਗਿਣਤੀ ਮੇਂ ਏਕ ਹੈ। ਇਸੀ ਭਾਂਤ ਮੁੱਖ ਤੀਰਥੋਂ ਕੀ ਗਿਣਤੀ ਕਰਨੇ ਸੇ ੬੮ ਹੋਤੇ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
75,10,'G',3,2,1,1,'1','','115,112,112,112,109,','115 112 112 112 109 ','suixAY piV piV pwvih mwnu ]','Listening-reading and reciting, honor is obtained.','By hearing and constantly reading God''s Name man gains honour.','ਹਰੀ ਦੇ ਨਾਮ ਨੂੰ ਸੁਣਨ ਅਤੇ ਇਕ ਰਸ ਵਾਚਣ ਦੁਆਰਾ ਆਦਮੀ ਇੱਜ਼ਤ ਪਾਉਂਦਾ ਹੈ।','Suniai Parr Parr Paavehi Maan ||','ਜੋ ਸਤਕਾਰ (ਮਨੁੱਖ ਵਿੱਦਿਆ) ਪੜ੍ਹ ਕੇ ਪਾਂਦੇ ਹਨ, ਉਹ ਭਗਤ ਜਨਾਂ ਨੂੰ ਅਕਾਲ ਪੁਰਖ ਦੇ ਨਾਮ ਵਿਚ ਜੁੜ ਕੇ ਹੀ ਮਿਲ ਜਾਂਦਾ ਹੈ।','ਸਾਸਤ੍ਰ ਵੇਦੋਂ ਕੇ ਪਢ ਪਢ ਮਾਨ ਕਾ ਪਾਵਨਾ, ਸੋ ਭੀ ਸ੍ਰਵਣ ਸੇ ਹੀ ਪ੍ਰਾਪਤਿ ਹੂਆ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
76,10,'G',3,2,1,1,'1','','115,108,115,068,','115 108 115 068 ','suixAY lwgY shij iDAwnu ]','Listening-intuitively grasp the essence of meditation.','By hearing the Name, man easily procures the Lord''s meditation.','ਸਾਹਿਬ ਦੇ ਨਾਮ ਨੂੰ ਸੁਣਨ ਦੁਆਰਾ ਆਦਮੀ ਨੂੰ ਸੁਖੈਨ ਹੀ ਸਾਹਿਬ ਦਾ ਸਿਮਰਨ ਪਰਾਪਤ ਹੋ ਜਾਂਦਾ ਹੈ।','Suniai Laagai Sehaj Dhhiaan ||','ਨਾਮ ਸੁਣਨ ਦਾ ਸਦਕਾ ਅਡੋਲਤਾ ਵਿਚ ਚਿੱਤ ਦੀ ਬ੍ਰਿਤੀ ਟਿਕ ਜਾਂਦੀ ਹੈ।','(ਸਹਜਿ) ਆਤਮਾ ਮੈਂ ਧ੍ਯਾਨੁ ਲਗਨਾ ਸੋ ਭੀ ਸਰਵਣ ਸੇ ਹੀ ਹੂਆ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
77,10,'G',3,2,1,1,'1','','110,066,115,118,','110 066 115 118 ','nwnk Bgqw sdw ivgwsu ]','O Nanak, the devotees are forever in bliss.','Ever blissful are the saints, O Nanak!','ਹੇ ਨਾਨਕ! ਅਨੁਰਾਗੀ ਹਮੇਸ਼ਾਂ ਅਨੰਦ ਮਾਣਦੇ ਹਨ।','Naanak Bhagathaa Sadhaa Vigaas ||','ਹੇ ਨਾਨਕ! (ਅਕਾਲ ਪੁਰਖ ਦੇ ਨਾਮ ਵਿਚ ਸੁਰਤ ਜੋੜਨ ਵਾਲੇ) ਭਗਤ ਜਨਾਂ ਦੇ ਹਿਰਦੇ ਵਿਚ ਸਦਾ ਖਿੜਾਉ ਬਣਿਆ ਰਹਿੰਦਾ ਹੈ,','ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹੇ ਸਿਧੋ! ਜਿਸ ਨਾਮ ਸ੍ਰਵਣ ਕਾ ਐਸਾ ਮਹਾਤਮੁ ਹੈ, ਜਿਸ ਸੇ ਸਦਾ (ਵਿਗਾਸੁ) ਅਨੰਦੁ ਅਰਥਾਤ ਨਿਤ੍ਯਾਨੰਦੁ ਪ੍ਰਾਪਤਿ ਹੂਆ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
78,10,'G',3,3,1,1,'1','','115,100,112,107,110,','115 100 112 107 110 ','suixAY dUK pwp kw nwsu ]10]','Listening-pain and sin are erased. ||10||','By hearing the Lord''s Name disease and wickedness are wiped off.','ਮਾਲਕ ਦੇ ਨਾਮ ਨੂੰ ਸਰਵਣ ਕਰਨ ਦੁਆਰਾ ਕਸ਼ਟ ਅਤੇ ਕਸਮਲ ਤਬਾਹ ਹੋ ਜਾਂਦੇ ਹਨ।','Suniai Dhookh Paap Kaa Naas ||10||','(ਕਿਉਂਕਿ) ਅਕਾਲ ਪੁਰਖ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਸੁਣਨ ਨਾਲ (ਮਨੁੱਖ ਦੇ) ਦੱਖਾਂ ਤੇ ਪਾਪਾਂ ਦਾ ਨਾਸ ਹੋ ਜਾਂਦਾ ਹੈ ॥੧੦॥','ਜਿਸ ਨਾਮ ਸ੍ਰਵਣ ਕਾ ਐਸਾ ਮਹਾਤਮੁ ਹੈ, ਤਿਸ ਨਾਮ ਕੋ ਜਿਨ ਭਗਤੋਂ ਨੇ ਪ੍ਰੇਮ ਸੇ ਸ਼੍ਰਵਣ ਕੀਆ ਹੈ, ਤਿਨ ਕੇ ਸਭ ਪ੍ਰਕਾਰ ਕੇ ਦੁਖ ਔਰੁ ਪਾਪੋਂ ਕਾ ਨਾਸੁ ਹੋ ਕਰ ਸਦਾ (ਵਿਗਾਸੁ) ਅਨੰਦੁ ਅਰਥਾਤ ਨਿਤ੍ਯਾਨੰਦੁ ਪ੍ਰਾਪਤਿ ਹੂਆ ਹੈ॥');
