CREATE TABLE IF NOT EXISTS shabad(
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    shabad_no TEXT, 
    source_id TEXT,
    ang_id TEXT, 
    line_id TEXT, 
    writer_id TEXT, 
    raag_id TEXT, 
    vishraam TEXT, 
    green_vishraam TEXT, 
    first_ltr_start TEXT,
    first_ltr_any TEXT  ,
    gurmukhi TEXT ,
    english_ssk TEXT  ,
    english_bms TEXT  ,
    punjabi_bms TEXT,
    transliteration TEXT ,
    sggs_darpan TEXT ,
    faridkot_teeka TEXT
);

INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
1,
1,
'G',
1,
1,
1,
1,
'30',
'17,43,55',
'115,107,112,110,110,065,109,065,115,103,',
'115 107 112 110 110 065 109 065 115 103 ',
'<> siqnwmu krqw purKu inrBau inrvYru Akwl mUriq AjUnI sYBM gurpRswid ]',
'One Universal Creator God, TheName Is Truth  Creative Being Personified No Fear No Hatred Image Of The Undying, Beyond Birth, Self-Existent. By Guru''s Grace~',
'There is but one God. True is His Name, creative His personality and immortal His form. He is without fear sans enmity, unborn and self-illumined. By the Guru''s grace He is obtained.',
'ਵਾਹਿਗੁਰੂ ਕੇਵਲ ਇਕ ਹੈ। ਸੱਚਾ ਹੈ ਉਸ ਦਾ ਨਾਮ, ਰਚਨਹਾਰ ਉਸ ਦੀ ਵਿਅਕਤੀ ਅਤੇ ਅਮਰ ਉਸ ਦਾ ਸਰੂਪ। ਉਹ ਨਿਡਰ, ਕੀਨਾ-ਰਹਿਤ, ਅਜਨਮਾ ਤੇ ਸਵੈ-ਪ੍ਰਕਾਸ਼ਵਾਨ ਹੈ। ਗੁਰਾਂ ਦੀ ਦਯਾ ਦੁਆਰਾ ਉਹ ਪਰਾਪਤ ਹੁੰਦਾ ਹੈ।',
'Ikoankaar Sathnaam Karathaa Purakh Nirabho Niravair Akaal Moorath Ajoonee Saibhan Gurprasaadh||',
'ਅਕਾਲ ਪੁਰਖ ਇੱਕ ਹੈ, ਜਿਸ ਦਾ ਨਾਮ ''ਹੋਂਦ ਵਾਲਾ'' ਹੈ ਜੋ ਸ੍ਰਿਸ਼ਟੀ ਦਾ ਰਚਨਹਾਰ ਹੈ, ਜੋ ਸਭ ਵਿਚ ਵਿਆਪਕ ਹੈ, ਭੈ ਤੋਂ ਰਹਿਤ ਹੈ, ਵੈਰ-ਰਹਿਤ ਹੈ, ਜਿਸ ਦਾ ਸਰੂਪ ਕਾਲ ਤੋਂ ਪਰੇ ਹੈ, (ਭਾਵ, ਜਿਸ ਦਾ ਸਰੀਰ ਨਾਸ-ਰਹਿਤ ਹੈ), ਜੋ ਜੂਨਾਂ ਵਿਚ ਨਹੀਂ ਆਉਂਦਾ, ਜਿਸ ਦਾ ਪ੍ਰਕਾਸ਼ ਆਪਣੇ ਆਪ ਤੋਂ ਹੋਇਆ ਹੈ ਅਤੇ ਜੋ ਸਤਿਗੁਰੂ ਦੀ ',
'ਬੇਦ ਸੂਪੁ ਉਪਦੇਸ ਮੇ ''ਓਂ'' ਕੇ ਆਦਿ ਮੇ ''ਏਕ'' ਅੰਗੁ ਨਹੀਂ ਕਹਾ, ਈਹਾਂ ਕਹਾ ਹੈ। ਤਿਸ ਕਾ ਏਹਿ ਤਾਤਪਰਯੁ ਹੈ, ਸੋ ਸਭ ਕੋ ਪ੍ਰਤੀਤ ਹੋ ਜਾਵੇ, ਜੋ ਸਿਧਾਂਤ ਵਸਤੂ ਅਦ੍ਵੈਤ ਹੈ, ਦ੍ਵੈਤ ਨਹੀਂ। ਯਾਂ ਤੇ ਜੀਵ ਈਸ ਏਕ ਰੂਪੁ ਹੈਂ, ਭੇਦ ਵਾਦੀਯੋਂ ਕੇ ਮਤ ਵਤ ਦੋ ਨਹੀਂ। ਕੇਈ ਕਿ ਏਕ ਅੰਗੁ ਆਦਿ ਮੇ ਕਹਿਨੇ ਕਾ ਏਹਿ ਹੇਤੂ ਕਹਤੇ ਹ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
2,1,'G',1,3,1,1,'','','106,','106 ','] jpu ]','Chant And Meditate:','Embrace His meditation.','ਉਸ ਦਾ ਸਿਮਰਨ ਕਰ।','|| Jap ||','(ਬਾਣੀ ਦਾ ਨਾਮ ਹੈ)','ਇਸ ਅਸਥਾਨ ਮੈ ਜਪ ਸਬਦ ਕੇ ਕਹਿਨੇ ਸੇ ਇਸ ਬਾਣੀ ਕਾ ਨਾਮੁ ਜਪੁ ਹੀ ਕਹਤੇ ਹੈਂ। ਜਿਸ ਪ੍ਰਮਾਤਮਾ ਕੇ ਨਾਮ ਕਾ ਜਪੁ ਵਿਧਾਨ ਕੀਆ ਹੈ ਸੋ ਪਰਮਾਤਮਾ ਕੈਸਾ ਹੈ ਤਿਸੁ ਪਰ ਕਹਤੇ ਹੈਂ (ਕਰਤਾ) ਨਿਖਲ ਸੰਸਾਰ ਕਾਕਾਰਣੁ ਹੈ ਭਾਵ ਯੇਹ ਹੈ ਕਿ ਯਾਵਤ ਕਾਲ ਕਿਸੀ ਬਸਤੂ ਕਾ ਲਛਨੁ ਨਹੀਂ ਕੀਆ ਜਾਤਾ ਹੈ ਤਾਵਤ ਕਾਲ ਪਰਯੰਤ ਵਸਤੂ ਕੀ ਸਿੱਧੀ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
3,1,'G',1,4,1,1,'6','','065,115,106,115,','065 115 106 115 ','Awid scu jugwid scu ]','True In The Primal Beginning. True Throughout The Ages.','True in the prime, True in the beginning of ages,','ਪਰਾਰੰਭ ਵਿੱਚ ਸੱਚਾ, ਯੁਗਾਂ ਦੇ ਸ਼ੁਰੂ ਵਿੱਚ ਸੱਚਾ,','Aadh Sach Jugaadh Sach ||','ਅਕਾਲ ਪੁਰਖ ਮੁੱਢ ਤੋਂ ਹੋਂਦ ਵਾਲਾ ਹੈ, ਜੁਗਾਂ ਦੇ ਮੁੱਢ ਤੋਂ ਮੌਜੂਦ ਹੈ।','ਆਦਿ ਕਹੀਏ ਸਰਬ ਕੀ ਉਤਪਤੀ ਸੇ ਪਹਿਲੇ ਭੀ ਵਹੁ ਪੁਰਖੁ ਸਚੁ ਹੀ ਥਾ। ਜਬ ਸੂਖਮੁ ਔਰ ਅਸਥੂਲੁ ਪਰਪੰਚੁ ਹੋ ਗ੍ਯਾ ਪਰੰਤੂ ਸਤਜੁਗ ਆਦਿਕੋਂ ਕੇ ਧਰਮ ਕਾ ਵਿਸਤਾਰੁ ਨਹੀਂ ਹੂਆ ਥਾ, ਉਸ ਕਾਲ ਕਾ ਨਾਮੁ ਜੁਗਾਦਿ ਹੈ, ਤਿਸ ਕਾਲ ਮੈ ਭੀ ਸੱਚੁ ਹੀ ਥਾ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
4,1,'G',1,4,1,1,'7','','104,066,115,110,104,066,115,','104 066 115 110 104 066 115 ','hY BI scu nwnk hosI BI scu ]1]','True Here And Now. O Nanak, Forever And Ever True. ||1||','True He is even now and True He verily, shall be, O Nanak!','ਅਤੇ ਸੱਚਾ ਉਹ ਹੁਣ ਭੀ ਹੈ, ਹੇ ਨਾਨਕ! ਨਿਸਚਿਤ ਹੀ, ਉਹ ਸੱਚਾ ਹੋਵੇਗਾ।','Hai Bhee Sach Naanak Hosee Bhee Sach ||1||','ਹੇ ਨਾਨਕ! ਇਸ ਵੇਲੇ ਭੀ ਮੌਜੂਦ ਹੈ ਤੇ ਅਗਾਂਹ ਨੂੰ ਭੀ ਹੋਂਦ ਵਾਲਾ ਰਹੇਗਾ ॥੧॥','''ਹੈ ਭੀ ਸਚੁ'' ਹੁਣ ਸਾਰੇ ਜਗਤ ਕੀ ਇਸਥਿਤੀ ਕਾਲ ਮੇ ਭੀ ਸੱਚੁ ਹੈ। ਸ੍ਰੀ ਗੁਰੂ ਨਾਨਕ ਜੀ ਕਹਤੇ ਹੈਂ: ''ਹੋਸੀ ਭੀ ਸਚੁ'' ਅੱਗੇ ਨੂੰ ਸਾਰੇ ਜਗਤ ਕੇ ਪ੍ਰਲਯ ਕਾਲ ਮੇ ਭੀ ਸੱਚੁ ਹੀ ਹੋਵੇਗਾ ॥੧॥☬ਪੁਨਾ ਜਗ੍ਯਾਸੂਓਂ ਕੇ ਸੁਖੇਨ ਬੋਧ ਨਮਿੱਤ ਸੰਕੋਚ ਕਰ ਇਸ ਮੰਤ੍ਰ ਕਾ ਅਰਥੁ ਕਹਤੇ ਹੈਂ:☬ਏਕ ਜੋ ''ਓਂ'' ਮੰਗਲ ਰੂਪੁ ਪਰਮਾਤਮਾ ਹੈ। ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
5,1,'G',1,5,1,1,'13','1','115,115,110,104,106,115,108,118,','115 115 110 104 106 115 108 118 ','socY soic n hoveI jy socI lK vwr ]','By thinking, He cannot be reduced to thought, even by thinking hundreds of thousands of times.','By pondering on God, man cannot have a conception of Him, even though he may ponder over lacs of times.','ਵਿਚਾਰ ਕਰਨ ਦੁਆਰਾ ਵਾਹਿਗੁਰੂ ਦੀ ਗਿਆਤ ਨਹੀਂ ਹੁੰਦੀ, ਭਾਵੇਂ ਆਦਮੀ ਲੱਖਾਂ ਵਾਰੀ ਵਿਚਾਰ ਪਿਆ ਕਰੇ।','Sochai Soch N Hovee Jae Sochee Lakh Vaar ||','ਜੇ ਮੈਂ ਲੱਖ ਵਾਰੀ (ਭੀ) (ਇਸ਼ਨਾਨ ਆਦਿਕ ਨਾਲ ਸਰੀਰ ਦੀ) ਸੁੱਚ ਰੱਖਾਂ, (ਤਾਂ ਭੀ ਇਸ ਤਰ੍ਹਾਂ) ਸੁੱਚ ਰੱਖਣ ਨਾਲ (ਮਨ ਦੀ) ਸੁੱਚ ਨਹੀਂ ਰਹਿ ਸਕਦੀ।','ਸੋਚ, ਪਵਿੱਤ੍ਰਤਾ ਕਰਨੇ ਸੇ ਅੰਤਹਕਰਣ ਰਾਗ ਦ੍ਵੈਖ ਸੇ ਰਹਿਤ ਸੁੱਧ ਨਹੀਂ ਹੋਤਾ, ਭਾਵੇਂ ਲਾਖੋਂ ਵਾਰ ਪਵਿੱਤ੍ਰਤਾ ਕਰੀਏ। ਵਾ ਆਤਮ ਵਿਚਾਰ ਜੋ ਹੈ, ਸੋ (ਸੋਚਿ) ਪਵਿੱਤ੍ਰਤਾ ਕਰਨੇ ਸੇ ਨਹੀਂ ਪ੍ਰਾਪਤਿ ਹੋਤਾ, ਜੇ ਕਰ ਲੱਖਾਂ ਵਾਰੀ ਪਵਿੱਤ੍ਰਤਾ ਕਰੀਏ। ਭਾਵ ਯੇਹ ਹੈ, ਬਾਹਿਰ ਕੀ ਪਵਿੱਤ੍ਰਤਾ ਸਰੀਰ ਕੀ ਸੁੱਧੀ ਕਾ ਕਾਰਣੁ ਹੈ। ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
6,1,'G',1,5,1,1,'13','1','099,099,110,104,106,108,114,108,113,','099 099 110 104 106 108 114 108 113 ','cupY cuip n hoveI jy lwie rhw ilv qwr ]','By remaining silent, inner silence is not obtained, even by remaining lovingly absorbed deep within.','Even though one be silent and remains absorbed in Lord''s constant love he obtains not mind''s silence.','ਭਾਵੇਂ ਬੰਦਾ ਚੁਪ ਕਰ ਰਹੇ ਅਤੇ ਲਗਾਤਾਰ ਧਿਆਨ ਅੰਦਰ ਲੀਨ ਰਹੇ, ਉਸ ਨੂੰ ਮਨ ਦੀ ਸ਼ਾਂਤੀ ਪਰਾਪਤ ਨਹੀਂ ਹੁੰਦੀ।','Chupai Chup N Hovee Jae Laae Rehaa Liv Thaar ||','ਜੇ ਮੈਂ (ਸਰੀਰ ਦੀ) ਇਕ-ਤਾਰ ਸਮਾਧੀ ਲਾਈ ਰੱਖਾਂ; (ਤਾਂ ਭੀ ਇਸ ਤਰ੍ਹਾਂ) ਚੁੱਪ ਕਰ ਰਹਿਣ ਨਾਲ ਮਨ ਦੀ ਸ਼ਾਂਤੀ ਨਹੀਂ ਹੋ ਸਕਦੀ।','ਬਾਣੀ ਕੇ ਚੁੱਪ ਰਹਿਣੇ ਸੇ ਸੰਕਲਪ ਵਿਕਲਪੋਂ ਸੇ ਮਨ ਕੀ ਸਾਂਤੀ ਰੂਪ ਚੁੱਪ ਨਹੀਂ ਹੋਤੀ। ਜੇ ਹੋ ਜਾਵੇ ਤੌ (ਲਿਵ) ਬ੍ਰਿਤੀ ਕੋ ਤੇਲ ਧਾਰਾਵਤ ਲਗਾਇ ਰੱਖੀਏ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
7,1,'G',1,5,1,1,'14','1','066,066,110,097,106,098,112,066,','066 066 110 097 106 098 112 066 ','BuiKAw BuK n auqrI jy bMnw purIAw Bwr ]','The hunger of the hungry is not appeased, even by piling up loads of worldly goods.','The hunger of the hungry departs not, even though they may pile up loads of the world''s valuables.','ਖੁਧਿਆਵੰਤਾਂ ਦੀ ਖੁਧਿਆ ਦੂਰ ਨਹੀਂ ਹੁੰਦੀ, ਭਾਵੇਂ ਉਹ ਜਹਾਨਾ ਦੇ ਪਦਾਰਥਾਂ ਦੀਆਂ ਪੰਡਾ ਦੇ ਢੇਰ ਹੀ ਕਿਉਂ ਨਾਂ ਲਾ ਲੈਣ।','Bhukhiaa Bhukh N Outharee Jae Bannaa Pureeaa Bhaar ||','ਜੇ ਮੈਂ ਸਾਰੇ ਭਵਣਾਂ ਦੇ ਪਦਾਰਥਾਂ ਦੇ ਢੇਰ (ਭੀ) ਸਾਂਭ ਲਵਾਂ, ਤਾਂ ਭੀ ਤ੍ਰਿਸ਼ਨਾ ਦੇ ਅਧੀਨ ਰਿਹਾਂ ਤ੍ਰਿਸ਼ਨਾ ਦੂਰ ਨਹੀਂ ਹੋ ਸਕਦੀ।','ਭੁਖੇ ਰਹਿਨੇ ਸੇ ਅਰਥਾਤ ਕ੍ਰਿਸ ਚੰਦ੍ਰਾਇਣਾਦਿ ਬ੍ਰਤ ਕਰਨੇ ਸੇ, ਵਾ (ਭੁਖਿਆ) ਤ੍ਰਿਸ਼ਨਾ ਵਾਨੋ ਕੀ ਮਾਯਾ ਕੀ ਭੂਖ ਨਹੀਂ ਜਾਤੀ ਅਰਥਾਤ ਤ੍ਰਿਸਨਾਂ ਨਿਵਿਰਤ ਨਹੀਂ ਹੋਤੀ। ਜੋ ਇੰਦ੍ਰਾਦਿ ਸਭ ਪੁਰੀਯੋਂ ਕੇ ਪਦਾਰਥੋਂ ਕੇ ਭਾਰ ਬਾਧ ਕਰ ਦੇ ਦੀਜੀਏ, ਭਾਵ ਏਹੋ ਸਬ ਪਦਾਰਥ ਪਾਉਨੇ ਕਰ ਭੀ ਤ੍ਰਿਸ਼ਨਾ ਬਢਤੀ ਹੀ ਜਾਤੀ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
8,1,'G',1,6,1,1,'16','','115,115,108,104,113,101,110,099,110,','115 115 108 104 113 101 110 099 110 ','shs isAwxpw lK hoih q iek n clY nwil ]','Hundreds of thousands of clever tricks, but not even one of them will go along with you in the end.','Man may possess thousands and lacs of wits, but not even one (goes with him) avails him in the Lord''s court.','ਇਨਸਾਨ ਦੇ ਕੋਲ ਹਜ਼ਾਰਾਂ ਤੇ ਲੱਖਾਂ ਅਕਲ-ਮੰਦੀਆਂ ਹੋਣ, ਪਰ ਇਕ ਭੀ (ਸਾਈਂ ਦੇ ਦਰਬਾਰ ਅੰਦਰ ਉਸ ਨੂੰ ਲਾਭ ਨਹੀਂ ਪੁਚਾਉਂਦੀ) ਉਸ ਦੇ ਨਾਲ ਨਹੀਂ ਜਾਂਦੀ।','Sehas Siaanapaa Lakh Hohi Th Eik N Chalai Naal ||','ਜੇ (ਮੇਰੇ ਵਿਚ) ਹਜ਼ਾਰਾਂ ਤੇ ਲੱਖਾਂ ਚਤੁਰਾਈਆਂ ਹੋਵਣ, (ਤਾਂ ਭੀ ਉਹਨਾਂ ਵਿਚੋਂ) ਇਕ ਭੀ ਚਤੁਰਾਈ ਸਾਥ ਨਹੀਂ ਦੇਂਦੀ।','ਜੇਕਰ ਪੁਰਖ ਕੇ ਪਾਸ (ਸਹਸ) ਹਜਾਰੋਂ ਲਾਖੋਂ ਸੰਸਾਰਕ ਸ੍ਯਾਨਪਾਂ ਹੋਵੇਂ, ਤਾਂ ਵੀ ਪਰਮੇਸ੍ਵਰ ਕੀ ਪ੍ਰਾਪਤੀ ਮੈ ਚਤਰਾਈ੍ਯੋਂ ਕਾ ਏਕ ਜੋਰੁ ਭੀ (ਨਾਲਿ) ਸਾਥ ਨਹੀਂ ਚੱਲਦਾ ਹੈ, ਭਾਵ ਸਹਾਇਕ ਨਹੀਂ ਹੋਤਾ॥ ਪ੍ਰਸ਼ਨ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
9,1,'G',1,6,1,1,'13','1,20','107,115,104,107,107,113,112,','107 115 104 107 107 113 112 ','ikv sicAwrw hoeIAY ikv kUVY qutY pwil ]','So how can you become truthful? And how can the veil of illusion be torn away?','How can we be true and how can the screen of untruth be rent?','ਅਸੀਂ ਕਿਸ ਤਰ੍ਹਾਂ ਸੱਚੇ ਹੋ ਸਕਦੇ ਹਾਂ ਅਤੇ ਕਿਸ ਤਰ੍ਹਾਂ ਝੂਠ ਦਾ ਪੜਦਾ ਪਾੜਿਆ ਜਾ ਸਕਦਾ ਹੈ?','Kiv Sachiaaraa Hoeeai Kiv Koorrai Thuttai Paal ||','(ਤਾਂ ਫਿਰ) ਅਕਾਲ ਪੁਰਖ ਦਾ ਪਰਕਾਸ਼ ਹੋਣ ਲਈ ਯੋਗ ਕਿਵੇਂ ਬਣ ਸਕੀਦਾ ਹੈ (ਅਤੇ ਸਾਡੇ ਅੰਦਰ ਦਾ) ਕੂੜ ਦਾ ਪਰਦਾ ਕਿਵੇਂ ਟੁੱਟ ਸਕਦਾ ਹੈ?','ਫੇਰ ਕਿਸ ਪ੍ਰਕਾਰ ਪ੍ਰਮੇਸ੍ਵਰ ਸਾਥ ਸਚੇ ਹੋਵੀਏ, ਅਰੁ ਝੂਠ ਕਾ (ਪਾਲਿ) ਪੜਦਾ ਕੈਸੇ (ਤੁਟੈ) ਭਾਵ ਨਾਸ ਹੋਵੈ? ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
10,1,'G',1,7,1,1,'13','18','104,114,099,110,108,110,','104 114 099 110 108 110 ','hukim rjweI clxw nwnk iliKAw nwil ]1]','O Nanak, it is written that you shall obey the Hukam of His Command, and walk in the Way of His Will. ||1||','O Nanak! By obeying, the pre-ordained order of the Lord''s will.','ਹੇ ਨਾਨਕ! ਮਰਜ਼ੀ ਦੇ ਮਾਲਕ ਦੇ ਧੁਰ ਦੇ ਲਿਖੇ ਹੋਏ ਫੁਰਮਾਨ ਦੇ ਮੰਨਣ ਦੁਆਰਾ।','Hukam Rajaaee Chalanaa Naanak Likhiaa Naal ||1||','ਰਜ਼ਾ ਦੇ ਮਾਲਕ ਅਕਾਲ ਪੁਰਖ ਦੇ ਹੁਕਮ ਵਿਚ ਤੁਰਨਾ-(ਇਹੀ ਇਕ ਵਿਧੀ ਹੈ)। ਹੇ ਨਾਨਕ! (ਇਹ ਵਿਧੀ) ਧੁਰ ਤੋਂ ਹੀ ਜਦ ਤੋਂ ਜਗਤ ਬਣਿਆ ਹੈ, ਲਿਖੀ ਚਲੀ ਆ ਰਹੀ ਹੈ ॥੧॥','ਪੁਰਸੁ (ਰਜਾਈ) ਅਕਾਲ ਪੁਰਖ ਕੇ ਹੁਕਮ ਮੇ ਚਲੇ ਅਰਥਾਤ ਦੁਖੁ ਸੁਖੁ ਮੈਂ ਭਾਣਾ ਮਾਨ ਕਰ ਪ੍ਰਸਿੰਨ ਰਹੇ, ਇਉਂ ਕੂੜ ਕੀ ਪਾਲ ਤੁਟ ਜਾਤੀ ਹੈ ਔਰ (ਸਚਿਆਰਾ) ਸਚੇ ਹੋਈਤਾ ਹੈ ਵਾ ਹੁਕਮਿ ਵਿਖੇ (ਰਜਾਈ) ਰਾਜੀ, ਭਾਵ ਪ੍ਰਸਿੰਨ ਹੋ ਕਰ ਚਲਣਾ, ਇਸ ਕਰ ਪ੍ਰਮੇਸ੍ਵਰ ਨਾਲ ਸਚੇ ਰਹੀਤਾ ਹੈ। ਗੁਰੂ ਨਾਨਕ ਜੀ ਕਹਤੇ ਹੈਂ: ਜੋ ਪ੍ਰਾਰਬਧ ਕ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
11,2,'G',1,7,1,1,'13','','104,104,065,104,110,107,106,','104 104 065 104 110 107 106 ','hukmI hovin Awkwr hukmu n kihAw jweI ]','By His Command, bodies are created; His Command cannot be described.','By the Lord''s order bodies are produced. His order cannot be narrated.','ਸਾਈਂ ਦੇ ਅਮਰ ਦੁਆਰਾ ਸਰੀਰ ਬਣਦੇ ਹਨ। ਉਸ ਦਾ ਅਮਰ ਵਰਨਣ ਕੀਤਾ ਨਹੀਂ ਜਾ ਸਕਦਾ।','Hukamee Hovan Aakaar Hukam N Kehiaa Jaaee ||','ਅਕਾਲ ਪੁਰਖ ਦੇ ਹੁਕਮ ਅਨੁਸਾਰ ਸਾਰੇ ਸਰੀਰ ਬਣਦੇ ਹਨ, (ਪਰ ਇਹ) ਹੁਕਮ ਦੱਸਿਆ ਨਹੀਂ ਜਾ ਸਕਦਾ ਕਿ ਕਿਹੋ ਜਿਹਾ ਹੈ।','ਪ੍ਰਥਮ ਤੋ ਉਸ ਕਾ ਹੁਕਮੁ ਸਮਗ੍ਰ ਕਹਾ ਨਹੀਂ ਜਾਤਾ, ਕ੍ਯੋਂਕਿ ਬਿਅੰਤ ਹੈ। ਪਰ ਤਾਂ ਵੀ ਕੁਛ ਸੁਨਾਵਤੇ ਹੈਂ। ਏਹ ਜਿਤਨੇ ਅਕਾਰ ਸਥੂਲ ਸਰੀਰ ਹੈਂ, ਸੋ ਸੰਪੂਰਣ ਹੁਕਮੀ ਪਰਮੇਸ੍ਵਰ ਕੇ ਹੁਕਮ ਸੇ ਹੋਤੇ ਹੈਂ। ਅਰ ਹੁਕਮ ਸੇ ਹੀ ਜੀਵ ਆਵਰ ਭਾਵ ਕੋ ਪ੍ਰਾਪਤਿ ਹੋਤੇ ਹੈਂ। ਵਾ ਅਕਾਰ ਉਪਲਖਤ ''ਅਕਾਰ'', ''ਉਕਾਰ'', ''ਮਕਾਰ'', ''ਬ੍ਰਹਮਾ''');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
12,2,'G',1,8,1,1,'13','','104,104,106,104,109,118,','104 104 106 104 109 118 ','hukmI hovin jIA hukim imlY vifAweI ]','By His Command, souls come into being; by His Command, glory and greatness are obtained.','With His fiat the souls come into being and with His fiat greatness is obtained.','ਉਸ ਦੇ ਫੁਰਮਾਨ ਨਾਲ ਰੂਹਾਂ ਹੋਂਦ ਵਿੱਚ ਆਉਂਦੀਆਂ ਹਨ ਅਤੇ ਉਸ ਦੇ ਫੁਰਮਾਨ ਨਾਲ ਹੀ ਮਾਨ ਪਰਾਪਤ ਹੁੰਦਾ ਹੈ।','Hukamee Hovan Jeea Hukam Milai Vaddiaaee ||','ਰੱਬ ਦੇ ਹੁਕਮ ਅਨੁਸਾਰ ਹੀ ਸਾਰੇ ਜੀਵ ਜੰਮ ਪੈਂਦੇ ਹਨ ਅਤੇ ਹੁਕਮ ਅਨੁਸਾਰ ਹੀ (ਰੱਬ ਦੇ ਦਰ ''ਤੇ) ਸ਼ੋਭਾ ਮਿਲਦੀ ਹੈ।','ਪੁਨਾ ਤਿਨਾ ਦ੍ਵਾਰੇ ਔਰ ਜੀਵੋਂ ਕੇ ਅਕਾਰ, ਸਥਾਵਰ ਜੰਗਮ ਰੂਪ ਸਭ ਹੁਕਮੀ ਕੇ ਹੁਕਮ ਕਰ ਕੇ ਹੋਤੇ ਹੈਂ। ਹੁਕਮ ਹੀ ਕਰ ਕੇ ਇਨ ਜੀਵੋਂ ਕੋ ਵਡਿਆਈ ਛੁਟਿਆਈ ਮਿਲਤੀ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
13,2,'G',1,8,1,1,'13','1,24','104,097,110,104,108,100,115,112,','104 097 110 104 108 100 115 112 ','hukmI auqmu nIcu hukim iliK duK suK pweIAih ]','By His Command, some are high and some are low; by His Written Command, pain and pleasure are obtained.','By His command the mortals are make high and low and by His written command they obtain woe and weal.','ਉਸ ਦੇ ਫੁਰਮਾਨ ਦੁਆਰਾ ਪ੍ਰਾਨੀ ਚੰਗੇ ਤੇ ਮੰਦੇ ਹੁੰਦੇ ਹਨ ਅਤੇ ਉਸ ਦੇ ਲਿਖੇ ਫੁਰਮਾਨ ਦੁਆਰਾ ਹੀ ਉਹ ਗ਼ਮੀ ਤੇ ਖ਼ੁਸ਼ੀ ਪਾਉਂਦੇ ਹਨ।','Hukamee Outham Neech Hukam Likh Dhukh Sukh Paaeeahi ||','ਰੱਬ ਦੇ ਹੁਕਮ ਵਿਚ ਕੋਈ ਮਨੁੱਖ ਚੰਗਾ (ਬਣ ਜਾਂਦਾ) ਹੈ, ਕੋਈ ਭੈੜਾ। ਉਸ ਦੇ ਹੁਕਮ ਵਿਚ ਹੀ (ਆਪਣੇ ਕੀਤੇ ਹੋਏ ਕਰਮਾਂ ਦੇ) ਲਿਖੇ ਅਨੁਸਾਰ ਦੁੱਖ ਤੇ ਸੁਖ ਭੋਗੀਦੇ ਹਨ।','ਹੁਕਮੀ ਕੇ ਹੁਕਮ ਹੀ ਕਰ ਕੇ ਉਤਮ ਅਰੁ ਨੀਚ ਹੂਏ ਹੈਂ, ਵਾ ਨੀਚ ਤੇ ਉਤਮ, ਉਤਮ ਤੇ ਨੀਚ ਹੋਤੇ ਹੈਂ। ਜਥਾ ਅੰਗ ਰਾਜਾ ਕਾ ਬੇਟਾ ਬੇਨੁ ਨੀਚ ਹੂਆ, ਅਰੁ ਬਾਲਮੀਕ ਨੀਚੁ ਥਾ, ਸੋ ਪਰਮਾਤਮਾ ਕੇ ਹੁਕਮ ਸੇ ਰਾਮ ਜਪ ਕਰ ਉਤਮੁ ਭਇਆ⁽¹⁾। ਔਰ ਲਿਖਾ ਹੂਆ ਜੋ ਦੁਖੁ ਸੁਖੁ ਕਾ ਲੇਖੁ ਹੈ, ਸੋ (ਹੁਕਮੀ) ਪ੍ਰਮੇਸ੍ਵਰ ਕੇ ਹੁਕਮ ਸੇ ''ਪਾਈਅਹ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
14,2,'G',1,9,1,1,'13','','101,104,098,101,104,115,066,','101 104 098 101 104 115 066 ','ieknw hukmI bKsIs ieik hukmI sdw BvweIAih ]','Some, by His Command, are blessed and forgiven; others, by His Command, wander aimlessly forever.','Some obtain gifts through His order and some through His order are ever made to wander in transmigration.','ਕਈਆਂ ਨੂੰ ਉਸ ਦੀ ਆਗਿਆ ਰਾਹੀਂ ਦਾਤਾਂ ਮਿਲਦੀਆਂ ਹਨ ਅਤੇ ਕਈ ਉਸ ਦੀ ਆਗਿਆ ਰਾਹੀਂ ਆਵਾਗਉਣ ਅੰਦਰ ਸਦੀਵ ਹੀ ਭੁਆਈਂਦੇ ਹਨ।','Eikanaa Hukamee Bakhasees Eik Hukamee Sadhaa Bhavaaeeahi ||','ਹੁਕਮ ਵਿਚ ਹੀ ਕਦੀ ਮਨੁੱਖਾਂ ਉੱਤੇ (ਅਕਾਲ ਪੁਰਖ ਦੇ ਦਰ ਤੋਂ) ਬਖ਼ਸ਼ਸ਼ ਹੁੰਦੀ ਹੈ, ਅਤੇ ਉਸ ਦੇ ਹੁਕਮ ਵਿਚ ਹੀ ਕਈ ਮਨੁੱਖ ਨਿੱਤ ਜਨਮ ਮਰਨ ਦੇ ਗੇੜ ਵਿਚ ਭਵਾਈਦੇ ਹਨ।','ਇਕਨੋਂ ਕੋ ਹੁਕਮੀ ਕੇ ਹੁਕਮ ਕਰ ਕੇ ਹੀ ਆਤਮ ਪਦ ਕੀ ਪ੍ਰਾਪਤੀ ਰੂਪੁ ਬਖਸੀਸ ਮਿਲਤੀ ਹੈ। ਏਕ ਪਰਮਾਤਮਾ ਕੇ ਹੁਕਮ ਕਰ ਕੇ ਜਨਮ ਮਰਨ ਰੂਪ ਚੌਰਾਸੀ ਮੈ ਸਦਾ ਭ੍ਰਮਾਈਤੇ ਹੈਂ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
15,2,'G',1,9,1,1,'17','','104,065,115,107,098,104,110,107,','104 065 115 107 098 104 110 107 ','hukmY AMdir sBu ko bwhir hukm n koie ]','Everyone is subject to His Command; no one is beyond His Command.','All are subject to His fiat and none is exempt from His fiat.','ਸਾਰੇ ਉਸ ਦੇ ਅਮਰ ਵਿੱਚ ਹਨ ਅਤੇ ਉਸ ਦੇ ਅਮਰ ਤੋਂ ਬਾਹਰ ਕੋਈ ਨਹੀਂ।','Hukamai Andhar Sabh Ko Baahar Hukam N Koe ||','ਹਰੇਕ ਜੀਵ ਰੱਬ ਦੇ ਹੁਕਮ ਵਿਚ ਹੀ ਹੈ, ਕੋਈ ਜੀਵ ਹੁਕਮ ਤੋਂ ਬਾਹਰ (ਭਾਵ, ਹੁਕਮ ਤੋ ਆਕੀ) ਨਹੀਂ ਹੋ ਸਕਦਾ।','ਸੋ ਸਭ ਕੋਈ ਹੁਕਮ ਹੀ ਕੇ ਅੰਦਰ ਹੈ ਬ੍ਰਹਮਾ ਸੇ ਲੇ ਕਰ ਚੀਟੀ ਪ੍ਰਯੰਤ ਹੁਕਮ ਤੇ ਬਾਹਰ ਕੋਈ ਨਹੀਂ ਹੈ॥☬ਪ੍ਰਸ਼ਨ: ਜੇ ਕਰ ਹੁਕਮ ਮੈ ਹੀ ਹੈਂ, ਤਾਂ ਮੈ ਏਹੁ ਕਰਤਾ ਹਾਂ ਅਰੁ ਏਹੁ ਕਰਾਂਗਾ? ਸੋ ਜੀਉ ਐਸੇ ਕ੍ਯੋਂ ਕਹਿਤਾ ਹੈ ਅਰੁ ਸੋ ਅਹੰਤਾ ਮਮਤਾ ਕੈਸੇ ਛੁਟੈ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
16,2,'G',1,10,1,1,'15','1','110,104,106,098,113,104,107,110,107,','110 104 106 098 113 104 107 110 107 ','nwnk hukmY jy buJY q haumY khY n koie ]2]','O Nanak, one who understands His Command, does not speak in ego. ||2||','O Nanak! if man were to understand Lord''s fiat, then no one would take pride (speak in ego).','ਹੇ ਨਾਨਕ! ਜੇਕਰ ਇਨਸਾਨ ਪ੍ਰਭੂ ਦੇ ਫੁਰਮਾਨ ਨੂੰ ਸਮਝ ਲਵੇ, ਤਦ ਕੋਈ ਭੀ ਹੰਕਾਰ ਨਾਂ ਕਰੇ।','Naanak Hukamai Jae Bujhai Th Houmai Kehai N Koe ||2||','ਹੇ ਨਾਨਕ! ਜੇ ਕੋਈ ਮਨੁੱਖ ਅਕਾਲ ਪੁਰਖ ਦੇ ਹੁਕਮ ਨੂੰ ਸਮਝ ਲਏ ਤਾਂ ਫਿਰ ਉਹ ਸੁਆਰਥ ਦੀਆਂ ਗੱਲਾਂ ਨਹੀਂ ਕਰਦਾ (ਭਾਵ, ਫਿਰ ਉਹ ਸੁਆਰਥੀ ਜੀਵਨ ਛੱਡ ਦੇਂਦਾ ਹੈ) ॥੨॥','ਸ੍ਰੀ ਗੁਰੂ ਜੀ ਕਹਤੇ ਹੈਂ: ਹੇ ਸਿਧੋ! ਜੇ ਕਰ ਹੁਕਮ ਕੋ ਬੂਝੇ ਤਾਂ ਕੋਈ ਪ੍ਰਕਾਰ ਸੇ (ਹਉਮੈ) ਹੰਕਾਰ ਕੇ ਬਚਨ ਨਹੀਂ ਕਹਤਾ ਕਿ ਮੈ ਨੇ ਏਹਿ ਕੀਆ ਅਰੁ ਏਹਿ ਕਰਾਂਗਾ। ਸਭ ਅਕਾਲ ਪੁਰਖ ਕੀ ਆਗ੍ਯਾ ਹੀ ਮਾਨੇਗੇ॥☬ਪ੍ਰਸ਼ਨ: ਜਿਸ ਕਾ ਐਸਾ ਹੁਕਮ ਹੈ, ਉਸ ਕਾ ਬਲੁ ਕਿਤਨਾਕੁ ਹੈ? ਕ੍ਯੋਂਕਿ ਹੁਕਮੁ ਜੋਰ ਸੇ ਚਲਤਾ ਹੈ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
17,3,'G',1,10,1,1,'9','','103,107,113,104,107,113,','103 107 113 104 107 113 ','gwvY ko qwxu hovY iksY qwxu ]','Some sing of His Power-who has that Power?','Who can sing His might? Who has power to sing it?','ਉਸਦੀ ਸ਼ਕਤੀ ਨੂੰ ਕੌਣ ਗਾਇਨ ਕਰ ਸਕਦਾ ਹੈ? ਇਸ ਨੂੰ ਗਾਇਨ ਕਰਨ ਦਾ ਕੀਹਦੇ ਕੋਲ ਬਲ ਹੈ?','Gaavai Ko Thaan Hovai Kisai Thaan ||','ਜਿਸ ਕਿਸੇ ਮਨੁੱਖ ਨੂੰ ਸਮਰਥਾ ਹੁੰਦੀ ਹੈ, ਉਹ ਰੱਬ ਦੇ ਤਾਣ ਨੂੰ ਗਾਉਂਦਾ ਹੈ, (ਭਾਵ, ਉਸ ਦੀ ਸਿਫ਼ਤ-ਸਾਲਾਹ ਕਰਦਾ ਹੈ ਤੇ ਉਸ ਦੇ ਉਹ ਕੰਮ ਕਥਨ ਕਰਦਾ ਹੈ, ਜਿਨ੍ਹਾਂ ਤੋਂ ਉਸ ਦੀ ਵੱਡੀ ਤਾਕਤ ਪਰਗਟ ਹੋਵੇ)।','ਉਸ ਅਕਾਲ ਪੁਰਖ ਕੇ ਸਮੱਗ੍ਰ (ਤਾਣੁ) ਬਲੁ ਕੋ (ਕੋ ਗਾਵੈ) ਕੌਣ ਗਾਇ ਸਕਤਾ ਹੈ? ਜਬ ਕਿਸੀ ਮੈ ਐਸਾ ਬਲੁ ਹੋਵੈ, ਤੌ ਗਾਇ ਸਕਤਾ ਹੈ॥');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
18,3,'G',1,11,1,1,'9','','103,107,100,106,110,','103 107 100 106 110 ','gwvY ko dwiq jwxY nIswxu ]','Some sing of His Gifts, and know His Sign and Insignia.','Who can sing His bounties and know His resplendent effulgence?','ਕੌਣ ਉਸ ਦੀਆਂ ਬਖ਼ਸ਼ੀਸ਼ਾਂ ਨੂੰ ਅਲਾਪ ਅਤੇ ਉਸ ਦੇ ਨੂਰਾਨੀ ਪਰਤਾਪ ਨੂੰ ਸਮਝ ਸਕਦਾ ਹੈ?','Gaavai Ko Dhaath Jaanai Neesaan ||','ਕੋਈ ਮਨੁੱਖ ਉਸ ਦੀਆਂ ਦਾਤਾਂ ਨੂੰ ਹੀ ਗਾਉਂਦਾ ਹੈ, (ਕਿਉਂਕਿ ਇਹਨਾਂ ਦਾਤਾਂ ਨੂੰ ਉਹ ਰੱਬ ਦੀ ਰਹਿਮਤ ਦਾ) ਨਿਸ਼ਾਨ ਸਮਝਦਾ ਹੈ।','(ਨੀਸਾਣੁ) ਪ੍ਰਗਟ ਅਰਥਾਤ ਇਦੰ ਕਰ ਕੇ ਉਸ ਕੀ ਦਾਤ ਕੋ ਕੌਨ ਜਾਨ ਸਕਦਾ ਹੈ? ਤਾਂ ਤੇ ਉਸ ਕੇ ਬਲ ਕੋ ਕੌਣ ਜਾਣੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
19,3,'G',1,11,1,1,'6','','103,107,103,118,099,','103 107 103 118 099 ','gwvY ko gux vifAweIAw cwr ]','Some sing of His Glorious Virtues, Greatness and Beauty.','Some chant the Lord''s beautiful excellences and magnificences.','ਕਈ ਸੁਆਮੀ ਦੀਆਂ ਸੁੰਦਰ ਵਡਿਆਈਆਂ ਅਤੇ ਬਜ਼ੁਰਗੀਆਂ ਗਾਇਨ ਕਰਦੇ ਹਨ।','Gaavai Ko Gun Vaddiaaeeaa Chaar ||','ਕੋਈ ਮਨੁੱਖ ਰੱਬ ਦੇ ਸੋਹਣੇ ਗੁਣ ਤੇ ਸੋਹਣੀਆਂ ਵਡਿਆਈਆਂ ਵਰਣਨ ਕਰਦਾ ਹੈ।','ਉਸ ਕੇ ਗੁਣਾ ਕੋ ਪੁਨਾ ਵਡਿਆਈਆ ਕੌ (ਚਾਰ) ਚਾਰੇ ਵੇਦ ਕਥਨ ਕਰਤੇ ਹੈਂ, ਪਰੁ ਅੰਤੁ ਨਹੀ ਪਾਵਤੇ ਹੈਂ। ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੌਣੁ ਗਾਇ ਸਕਤਾ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
20,3,'G',1,11,1,1,'6','','103,107,118,118,118,','103 107 118 118 118 ','gwvY ko ividAw ivKmu vIcwru ]','Some sing of knowledge obtained of Him, through difficult philosophical studies.','Who can chant God''s Knowledge, whose study is arduous?','ਵਾਹਿਗੁਰੂ ਦੇ ਇਲਮ ਨੂੰ ਜਿਸ ਦੀ ਸੋਚ ਵਿਚਾਰ ਕਠਨ ਹੈ, ਕੌਣ ਗਾ ਸਕਦਾ ਹੈ?','Gaavai Ko Vidhiaa Vikham Veechaar ||','ਕੋਈ ਮਨੁੱਖ ਵਿੱਦਿਆ ਦੇ ਬਲ ਨਾਲ ਅਕਾਲ ਪੁਰਖ ਦੇ ਕਠਨ ਗਿਆਨ ਨੂੰ ਗਾਉਂਦਾ ਹੈ (ਭਾਵ, ਸ਼ਾਸਤਰ ਆਦਿਕ ਦੁਆਰਾ ਆਤਮਕ ਫ਼ਿਲਾਸਫ਼ੀ ਦੇ ਔਖੇ ਵਿਸ਼ਿਆਂ ''ਤੇ ਵਿਚਾਰ ਕਰਦਾ ਹੈ)।','ਜਿਸ ਕੀ ਵੇਦਾਂਤਾ ਦੀ ਵਿੱਦ੍ਯਾ ਕਾ ਵਿਚਾਰੁ ਵੱਡਾ (ਵਿਖਮੁ) ਕਠਨੁ ਹੈ, ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੌਨੁ ਗਾਇ ਸਕਤਾ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
21,3,'G',1,12,1,1,'6','','103,107,115,107,113,075,','103 107 115 107 113 075 ','gwvY ko swij kry qnu Kyh ]','Some sing that He fashions the body, and then again reduces it to dust.','Some sing that He fashions the body and then reduces it to dust.','ਕਈ ਇਕ ਗਾਇਨ ਕਰਦੇ ਹਨ ਕਿ ਉਹ ਦੇਹ ਨੂੰ ਰਚਦਾ ਹੈ ਤੇ ਫੇਰ ਇਸ ਨੂੰ ਮਿੱਟੀ ਕਰ ਦਿੰਦਾ ਹੈ।','Gaavai Ko Saaj Karae Than Khaeh ||','ਕੋਈ ਮਨੁੱਖ ਇਉਂ ਗਾਉਂਦਾ ਹੈ, ''ਅਕਾਲ ਪੁਰਖ ਸਰੀਰ ਨੂੰ ਬਣਾ ਕੇ (ਫਿਰ) ਸੁਆਹ ਕਰ ਦੇਂਦਾ ਹੈ''।','ਜਿਸ ਪ੍ਰਕਾਰ ਇਨ ਜੀਵੋਂ ਕੇ (ਤਨ) ਸਰੀਰ (ਸਾਜ) ਬਨਾਇ ਕਰਕੇ, ਫਿਰ (ਖੇਹ) ਨਾਸ ਕਰ ਦੇਤਾ ਹੈ। ਵਾ ਜੈਸੇ (ਖੇਹ) ਪ੍ਰਿਥਵੀ ਆਦਿ ਤਤੋਂ ਸੇ ਇਨ ਸਰੀਰੋਂ ਕੋ ਸਾਜਣਾ ਕਰਤਾ ਹੈ, ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੌਨੁ ਗਾਇ ਸਕਤਾ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
22,3,'G',1,12,1,1,'6','','103,107,106,108,080,100,','103 107 106 108 080 100 ','gwvY ko jIA lY iPir dyh ]','Some sing that He takes life away, and then again restores it.','Some sing that God takes away life and again restores it.','ਕਈ ਇਕ ਗਾਇਨ ਕਰਦੇ ਹਨ ਕਿ ਵਾਹਿਗੁਰੂ ਪ੍ਰਾਣ ਲੈ ਲੈਂਦਾ ਹੈ ਤੇ ਮੁੜ ਵਾਪਸ ਦੇ ਦਿੰਦਾ ਹੈ।','Gaavai Ko Jeea Lai Fir Dhaeh ||','ਕੋਈ ਇਉਂ ਗਾਉਂਦਾ ਹੈ, ''ਹਰੀ (ਸਰੀਰਾਂ ਵਿਚੋਂ) ਜਿੰਦਾਂ ਕੱਢ ਕੇ ਫਿਰ (ਦੂਜੇ ਸਰੀਰਾਂ ਵਿਚ) ਪਾ ਦੇਂਦਾ ਹੈ''।','ਸੂਖਮ ਰੂਪੁ ਜੀਵੁ ਜਿਸ ਕੀ ਸੱਤਾ ਕੋ ਪਾਇਕੇ ਇਸ ਸਥੂਲ ਸਰੀਰ ਕੋ ਲਈ ਫਿਰਤਾ ਹੈ, ਵਾ ਇਸ ਸਰੀਰ ਮੈ ਸੇ ਜੀਵ ਨਿਕਾਲ ਲੇਤਾ ਹੈ ਔਰੁ ਜੋ ਸਰੀਰ ਮੇ ਜੀਵ ਪਾਇ ਦੇਤਾ ਹੈ, ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੌਨ ਗਾਇ ਸਕਤਾ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
23,3,'G',1,12,1,1,'6','','103,107,106,100,100,','103 107 106 100 100 ','gwvY ko jwpY idsY dUir ]','Some sing that He seems so very far away.','Some sing that God seems and appears to be far off.','ਕਈ ਗਾਇਨ ਕਰਦੇ ਹਨ ਕਿ ਹਰੀ ਦੁਰੇਡੇ ਮਲੂਮ ਹੁੰਦਾ ਅਤੇ ਸੁੱਝਦਾ ਹੈ।','Gaavai Ko Jaapai Dhisai Dhoor ||','ਕੋਈ ਮਨੁੱਖ ਆਖਦਾ ਹੈ, ''ਅਕਾਲ ਪੁਰਖ ਦੂਰ ਜਾਪਦਾ ਹੈ, ਦੂਰ ਦਿੱਸਦਾ ਹੈ'';','ਜੋ ਜਾਨਨੇ ਸੇ ਔਰ ਦੇਖਨੇ ਸੇ ਦੂਰ ਹੈ। ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੌਨੁ ਗਾਇ ਸਕਤਾ ਹੈ?');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
24,3,'G',2,1,1,1,'6','','103,107,118,104,104,','103 107 118 104 104 ','gwvY ko vyKY hwdrw hdUir ]','Some sing that He watches over us, face to face, ever-present.','Some sing that He is beholding us just face to face.','ਕਈ ਗਾਇਨ ਕਰਦੇ ਹਨ ਕਿ ਉਹ ਸਾਨੂੰ ਐਨ ਪਰਤੱਖ ਹੀ ਦੇਖ ਰਿਹਾ ਹੈ।','Gaavai Ko Vaekhai Haadharaa Hadhoor ||','ਪਰ ਕੋਈ ਆਖਦਾ ਹੈ, ''(ਨਹੀਂ, ਨੇੜੇ ਹੈ), ਸਭ ਥਾਈਂ ਹਾਜ਼ਰ ਹੈ, ਸਭ ਨੂੰ ਵੇਖ ਰਿਹਾ ਹੈ''।','ਜੇ ਕਰ (ਹਾਦਰਾ ਹਦੂਰਿ) ਹਾਜਰ ਹਜੂਰ, ਭਾਵ ਪ੍ਰਗਟ ਦੇਬੇ ਤੋ ਤਿਸ ਕੇ ਬਲ ਕੋ ਕੋਈ ਗਾਇ ਸਕਤਾ ਹੈ॥☬ਅਬ ਦੂਸਰਾ ਅਰਥ ਕਹਤੇ ਹੈਂ: (ਕੋ) ਕੋਈਕ ਪੁਰਾਣੋ ਵਾਲੇ ਅਕਾਲ ਪੁਰਖ ਕੇ ਬਲ ਕੋ ਜਿਸ ਹਕੁ ਉਨ ਕੋ ਬੁਧਿ ਕਾ ਬਲੁ ਹੋ, ਮਧੁ ਕੋਟਭਾਦਿ ਬਧ ਪ੍ਰਸੰਗ ਲਿਖ ਕਰ ਕੇ ਗਾਵਤੇ ਹੈਂ। ਕੋਈ ਪੰਚ ਰਾਤ੍ਰਿ ਮਤਵਾਲੇ ਨਾਰਦਾਦਿ ਹਾਥ ਪਾਉਂ ');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
25,3,'G',2,1,1,1,'6','','107,107,110,065,113,','107 107 110 065 113 ','kQnw kQI n AwvY qoit ]','There is no shortage of those who preach and teach.','There is no dearth of persons who dwell upon the Lord''s discourses.','ਗੋਬਿੰਦ ਦੀਆਂ ਗਿਆਨ ਗੋਸ਼ਟਾਂ ਵਿਚਾਰਨ ਵਾਲਿਆਂ ਪੁਰਸ਼ਾਂ ਦੀ ਕੋਈ ਕਮੀ ਨਹੀਂ।','Kathhanaa Kathhee N Aavai Thott ||','ਹੁਕਮ ਦੇ ਵਰਣਨ ਕਰਨ ਦੀ ਤੋਟ ਨਹੀਂ ਆ ਸਕੀ (ਭਾਵ, ਵਰਣਨ ਕਰ ਕਰ ਕੇ ਹੁਕਮ ਦਾ ਅੰਤ ਨਹੀਂ ਪੈ ਸਕਿਆ, ਹੁਕਮ ਦਾ ਸਹੀ ਸਰੂਪ ਨਹੀਂ ਲੱਭ ਸਕਿਆ);','ਜਿਤਨੇ ਸਿੰਮ੍ਰਿਤੀ, ਪੁਰਾਣ, ਸਾਸਤ੍ਰ ਕੇ ਵੇਤਾ ਹੈਂ ਤਿਨੋ ਨੇ ਪ੍ਰਮੇਸਰ ਕੇ ਸਤ੍ਯ ਸੰਕਲਪ ਆਦਿ ਬਲ ਕੀ ਕਥਾ ਨੂੰ ਕਥਨ ਕੀਆ ਹੈ। ਪਰੰਤੂ (ਤੋਟਿ) ਅੰਤੁ ਕਿਸੀ ਕੋ ਨਹੀਂ ਆਵਤਾ ਹੈ॥☬ਪ੍ਰਸ਼ਨ: ਜੇਕਰ ਬਹੁਤੇ ਮਿਲ ਕਰ ਕਹੇਂ ਤੌ ਅੰਤੁ ਮਿਲ ਜਾਵੇ?☬ਉੱਤਰ:');
INSERT INTO shabad ("_id",shabad_no,source_id,ang_id,line_id,writer_id,raag_id,vishraam,green_vishraam,first_ltr_start,first_ltr_any,gurmukhi,english_ssk,english_bms,punjabi_bms,transliteration,sggs_darpan,faridkot_teeka) VALUES (
26,3,'G',2,1,1,1,'9','','107,107,107,107,107,107,','107 107 107 107 107 107 ','kiQ kiQ kQI kotI koit koit ]','Millions upon millions offer millions of sermons and stories.','Millions give millions upon millions of descriptions and sermons regarding God.','ਕਰੋੜਾਂ ਹੀ ਬੰਦੇ ਹਰੀ ਬਾਰੇ ਕਰੋੜਾਂ ਉਤੇ ਕਰੋੜਾਂ ਬਿਆਨ ਅਤੇ ਧਰਮ-ਭਾਸ਼ਨ ਦਿੰਦੇ ਹਨ।','Kathh Kathh Kathhee Kottee Kott Kott ||','ਭਾਵੇਂ ਕ੍ਰੋੜਾਂ ਹੀ ਜੀਵਾਂ ਨੇ ਬੇਅੰਤ ਵਾਰੀ (ਅਕਾਲ ਪੁਰਖ ਦੇ ਹੁਕਮ ਦਾ) ਵਰਣਨ ਕੀਤਾ ਹੈ।','ਕ੍ਰੋੜੋਂ ਨੇ ਪੀਛੇ ਕਥਨ ਕਰੀ ਹੈ, ਕ੍ਰੋੜੋਂ ਹੀ ਅਬ ਕਥਨ ਕਰਤੇ ਹੈਂ, ਕ੍ਰੋੜੋਂ ਆਗੇ ਕਥਨ ਕਰੇਂਗੇ, ਪਰੰਤੂ ਅੰਤੁ ਨ ਮਿਲਾ, ਨਾ ਮਿਲਤਾ ਹੈ, ਨਾ ਮਿਲੇਗਾ॥☬ਪ੍ਰਸ਼ਨ: ਐਸੀ ਬਿ੍ਯੰਤ ਕਥਾ ਵਾਲਾ ਦਾਤਾ ਕੈਸਾ ਹੈ?☬ਉੱਤਰ:');

